### ISSUE TITLE
[meta] prepare deprecations/obsoletions in plugins for 7.0.0

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#10268]
Below is a list of plugins whose latest release contains deprecated and/or obsolete parameters. With the upcoming Logstash it's an opportunity to remove any obsolete fields and mark deprecated fields as obsolete.

- [x] logstash-codec-cef PR: https://github.com/logstash-plugins/logstash-codec-cef/pull/63
- [x] logstash-filter-cipher PR: https://github.com/logstash-plugins/logstash-filter-cipher/pull/25
- [x] logstash-filter-geoip PR: https://github.com/logstash-plugins/logstash-filter-geoip/pull/149
- [x] logstash-input-beats PR: https://github.com/logstash-plugins/logstash-input-beats/pull/356
- [ ] logstash-input-http
- [x] logstash-input-http_poller PR: https://github.com/logstash-plugins/logstash-input-http_poller/pull/104
- [x] logstash-input-kafka PR: https://github.com/logstash-plugins/logstash-input-kafka/pull/304
- [x] logstash-input-tcp PR: https://github.com/logstash-plugins/logstash-input-tcp/pull/139
- [x] logstash-mixin-http_client PR: https://github.com/logstash-plugins/logstash-mixin-http_client/pull/33
- [x] logstash-mixin-rabbitmq_connection PR: https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/55
- [ ] logstash-output-elasticsearch PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/828
- [x] logstash-output-kafka PR: https://github.com/logstash-plugins/logstash-output-kafka/pull/214
- [x] logstash-output-redis PR: https://github.com/logstash-plugins/logstash-output-redis/pull/60
- [x] logstash-output-sqs PR: https://github.com/logstash-plugins/logstash-output-sqs/pull/32
- [x] logstash-output-tcp PR: https://github.com/logstash-plugins/logstash-output-tcp/pull/37
