### ISSUE TITLE
Facilitate creation and maintenance for plugin docs

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#10466]
[Meta Issue] Supply information, examples, and generated files to help contributors create and maintain plugin documentation. This work is foundational for Java docs and examples.

- [x] Add new section "Documenting Your Plugin" (#9861)
Status: Largely complete. 
Goal: Move "next steps" recommended in comments to this issue and merge the PR. 

- [x] Plugin generator should create skeletal doc file and structure
Issue #8187/PR #10029  (WIP)
Next steps: Update "Documenting Your Plugin" topic to include plugin generator

- [x] Finalize and merge : [logstash-plugins/logstash-codec-example#10](https://github.com/logstash-plugins/logstash-codec-example/pull/10)
Status: The example doesn't yet contain buildable code, so we're failing CI. 
Should pass CI to be considered a good example.
Next steps: Update PR with buildable code.

- [x] Update input-example, output-example, and filter-example repos with more details and starter text.

- [x] Add docs/index.asciidoc starter files to new Java plugin examples
