### ISSUE TITLE
DLQ Meta issue

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#10493]
- [ ] Don't overwrite the "@metadata" - #8721
- [ ] Add retention mechanism - #6990
- [ ] Avoid waste of disk usage on each restart - #8022
- [ ] Implement DLQ support on more plugins - #7207
- [ ] Allow deletion of DLQ contents after processing - #8904
- [ ] Implement DLQ as an Pipeline to Pipeline - #9502

**Comment by antoniocascais** [comment]
We are starting to use DLQs and we also have the problem of the log files not being deleted after being processes.

No idea how to help with those issues though, never worked on the logstash project before.

**Comment by eedugon** [comment]
I think https://github.com/elastic/logstash/issues/8795 should be added here too (cc: @jguay )

The current behavior when the DLQ is full is not clear and documented, and the ways to prune or clear data from the queue to make it working again is also unclear. That causes uncertainty and concerns.
