### ISSUE TITLE
[META] Pipeline to pipeline communications

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#10502]
- [x] Pipeline shutdown ordering leads to stalls https://github.com/elastic/logstash/issues/9818
- [x] Metadata does not persist across pipeline output https://github.com/elastic/logstash/issues/9884
- [x] Cleanup debugging leftovers https://github.com/elastic/logstash/issues/10432
- [x] Clarify inter pipelines communication ensure_delivery option https://github.com/elastic/logstash/issues/10443
- [x] General code cleanup

**Comment by colinsurprenant** [comment]
Added #10432 and #10443
