### ISSUE TITLE
[Doc] Quality issues in plugin docs (incorrect asciidoc formatting, missing content) - continued

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#10838]
Quality issues in plugin docs (continued from #6693)

**Global:**

- [ ] Style of the description varies from plugin to plugin. Would be nice to make the descriptions for consistent in style (at least for the plugins that we maintain).

**Input plugins:**
- [ ] (plugins-inputs-redis](https://www.elastic.co/guide/en/logstash/7.x/plugins-inputs-redis.html).  Options are out of order.

**Output Plugins:**

**Filter Plugins:**

**Codec Plugins:**

**Integrations:**
- [ ] AWS docs fixes

**Comment by karenzone** [comment]
ToDo: Update plugin status in #6693, move over remaining issues, and continue tracking new ones here.
