### ISSUE TITLE
[Meta Issue] Logging Improvements

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#11074]
This issue contains a list of improvements to logging that we would like to include in future versions of Logstash:

**7.x**
- [x] Logs should include the plugin.id (see #9988 for one proposal) PR to review #11078 (7.x)

**7.6**
- [x] Avoid SourceWithMetadata collapse to plain string, use around the rich objects: PR #11456) (7.6)
- [x] Implement deprecation logging . #11049 PR #11260 (7.6)

**7.5.0**
- [x] Split logs for multiple pipelines into separate log files #10427 PR #11108 (docs PR #11177) (7.5.0)
- [x] Include `path.config` associated with `pipeline.id` #9630 PR #11123 (7.5.0)

**7.4**
- [x] Logs should include the pipeline.id #8290, #10521 (previous work: #9991) fixed by PR  #11075 (7.4)

**discarded issues/PRs**
- [x] ~~Default Plugin.id should be more useful, to discuss: Issue #11154 PR #11155 aborted because of #11456~~
- [x] ~~Expose Plugin source references through HTTP API (input/codec/filter/output) aborted #11497 because #11456 already does the job~~

**Comment by robbavey** [comment]
Thanks to the awesome work by @andsel, this meta issue can be closed!
