### ISSUE TITLE
[meta] Pipeline Java Execution important issues

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#11175]
This is a meta issue about some important Pipeline Java Execution issues.

## Priority Issues
- [X] Java execution may start inputs before compilation of filters and outputs has completed #11170 - Fixed in #11492
- [x] Java execution reorders events even with 1 pipeline worker #10938
  - Abandoned tentative fix #11020
  - Incomplete POC #11099 (does not solve the [complex aggregate filter scenario]
(https://gist.github.com/yaauie/82e199687c490a2e04fe1f0c9d9a7fee))
  - New solution PR #11524
- [X] Java execution startup is potentially slower for some configurations
- [x] fix for regression introduced by #11482 with #11564

## Followup Issues
- [x] improve `pipeline.ordered` setting to rebatch before outputs #11550 - Fixed in #11710
- [x] Document event ordering guaranties or lack thereof with multiple worker versus single worker - #11715
- [ ] Add integration harness around the expected compilation time which should be similar between single or multiple workers. #12476

## Other issues
- [x] quoted plugin options crashes logstash https://github.com/elastic/logstash/issues/11222 - Fixed in #11688

**Comment by colinsurprenant** [comment]
I have looked into the "Java execution startup is potentially slower for some configurations #11105" issue and as I commented in that issue, it is not **potentially** slower, the slowdown is a factor of the number of workers, see https://github.com/elastic/logstash/issues/11105#issuecomment-568112618. 

I will continue investigating this.

**Comment by colinsurprenant** [comment]
I have created 2 PRs with alternate implementations to solve the class compilation caching problem leading to recompiling everything per worker; the first #11479 uses the existing global cache but fixes the cache key to correctly reuse compiled classes. There are some potential problems with pipeline reloading and cache invalidation with this implementation and another PR #11482 uses a different strategy by moving the class caching at the pipeline level which solves both the potential invalidation and pipeline reloading problems.

**Comment by colinsurprenant** [comment]
Good news on the inputs starting before the workers are initialized: it is easier than I thought to fix, now just need to see if we make that configurable. Will push PR soon.

**Comment by colinsurprenant** [comment]
#11482 was merged and should considerably improve java execution pipeline compilation time as it will not be multiplied by the number of workers anymore. Fix will be included in 7.6.0 and 7.5.2.

**Comment by colinsurprenant** [comment]
PR to fix worker initialization sequence in #11492. Should we make that behaviour optional?

**Comment by colinsurprenant** [comment]
#11492 is merged and will be included in 7.6.0 and 7.5.2. We decided that it was indeed a bug fix and that adding an option to eagerly start inputs before workers are fully initialized was a feature to evaluate in #11493

**Comment by colinsurprenant** [comment]
New solution proposal for the event ordering #11524

**Comment by colinsurprenant** [comment]
#11482  addressed the multiple workers slowdown but introduced in 7.5.2 a regression for the multiple pipelines use-case. This PR will be reverted and replaced by #11564 which should correctly solve both problems.

**Comment by colinsurprenant** [comment]
About 
> Document event ordering guaranties or lack thereof with multiple worker versus single worker

I am wondering where in the docs we should introduce/document this subject. It does not feel right IMO to simply add a snipet un the settings file. /cc @karenzone @jsvd

**Comment by karenzone** [comment]
We're building out two general sections in [Troubleshooting](https://www.elastic.co/guide/en/logstash/current/troubleshooting.html) and [Tips and Best Practices](https://www.elastic.co/guide/en/logstash/current/tips.html). It seems like this new info is similar in nature, even though it doesn't fit neatly under either of those current categories.  If we renamed Tips and Best Practices or created a new section describing how things work, I'll bet we'd find other stuff to add.

**Comment by colinsurprenant** [comment]
Yeah, I like the idea of having a more general "concepts" section? we could then reference that in the settings docs for example.

**Comment by karenzone** [comment]
I like the idea of keeping the more general info (Troubleshooting, Tips and Best Practices, and a new concepts section) together.   On the other hand, it seems like a new conceptual section makes more sense in "How Logstash Works."  If I expanded that topic, I'd expect to see information such as what you want to add. 

Under "How Logstash Works"  (Pros and Cons):
+ Higher in book structure
+ Seems like a natural fit as part of "How Logstash Works"
- Nested under a higher level topic ("How Logstash Works"), and won't be visible unless somebody clicks to expand the higher level topic

A new section grouped with Troubleshooting and Tips and Best Practices (Pros and Cons):
+ Keeps general, conceptual information grouped together
+ New section could be a Level 1 heading, always visible
- The title "How Logstash Works" is already taken, so we'd need to come up with something else

WDYT?

**Comment by colinsurprenant** [comment]
The rebatching after filters #11710  which improves the `pipeline.ordered` performance has been merged and will be available starting in 7.7.0.

**Comment by colinsurprenant** [comment]
Closing this, all important work was done, one remaining testing issue has been created #12476
