### ISSUE TITLE
[Doc][Meta]Generate and merge plugin docs

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#11269]
## Generate and merge plugin docs

**2020-November/December**

- [x]  7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/976
- [x]  7.11: 
   - [x]  https://github.com/elastic/logstash-docs/pull/977
- [x]  7.10: 
   - [x] https://github.com/elastic/logstash-docs/pull/975

**2020-October**
- [x] master:   
   - [x]  https://github.com/elastic/logstash-docs/pull/954
   - [x]  https://github.com/elastic/logstash-docs/pull/948
- [x]  7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/955
   - [x]  https://github.com/elastic/logstash-docs/pull/947
- [x]  7.10: 
   - [x]  https://github.com/elastic/logstash-docs/pull/956
   - [x]  https://github.com/elastic/logstash-docs/pull/953
- [x]  7.9:
   - [x]  https://github.com/elastic/logstash-docs/pull/957
   - [x] https://github.com/elastic/logstash-docs/pull/952
- [x] 6.8:  
  - [x] https://github.com/elastic/logstash-docs/pull/950

**2020-September**
- [x] master:   
   - [x]  https://github.com/elastic/logstash-docs/pull/915
- [x]  7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/914
- [x]  7.9:
   - [x] https://github.com/elastic/logstash-docs/pull/913
- [x] 6.8:  
  - [x]  https://github.com/elastic/logstash-docs/pull/916

**2020-August**
- [x] master:   
   - [x]  https://github.com/elastic/logstash-docs/pull/904
   - [x]  https://github.com/elastic/logstash-docs/pull/899
- [x]  7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/903
   - [x]  https://github.com/elastic/logstash-docs/pull/898
- [x]  7.9:
   - [x] https://github.com/elastic/logstash-docs/pull/906
   - [x]  https://github.com/elastic/logstash-docs/pull/902
   - [x]  https://github.com/elastic/logstash-docs/pull/897
- [x]  7.8:
  - [ ]  https://github.com/elastic/logstash-docs/pull/896. Doc link regression. Closed without merging.
- [x] 6.8:  
  - [x]  https://github.com/elastic/logstash-docs/pull/901
  - [x]  https://github.com/elastic/logstash-docs/pull/895

**2020-July**
- [x] master:   
   - [x]  https://github.com/elastic/logstash-docs/pull/889
   - [x]  https://github.com/elastic/logstash-docs/pull/881
- [x] 7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/888
   - [x]  https://github.com/elastic/logstash-docs/pull/880
- [x] 7.9:
   - [x]  https://github.com/elastic/logstash-docs/pull/886
   - [x]  https://github.com/elastic/logstash-docs/pull/880 (generated from 7.x branch)
- [x] 7.8:
  - [x]  https://github.com/elastic/logstash-docs/pull/885

**2020-June**
- [x] master:   
   - [x]  https://github.com/elastic/logstash-docs/pull/876
   - [x]  https://github.com/elastic/logstash-docs/pull/874
- [ ] 7.x: 
   - [x]  https://github.com/elastic/logstash-docs/pull/875
- [ ] 7.8:
  - [ ]  No changes as of 6-23
- [ ] 6.8:  
  - [ ]  https://github.com/elastic/logstash-docs/pull/877. Closed without merge. (We don't want these changes.)

**2020-May**
- [ ] master:   
   - [x] https://github.com/elastic/logstash-docs/pull/863
   - [x] https://github.com/elastic/logstash-docs/pull/872
- [ ] 7.x: 
   - [x] https://github.com/elastic/logstash-docs/pull/860
   - [x] https://github.com/elastic/logstash-docs/pull/871
- [ ] 7.8:
  - [ ]  No additional changes on 5-31
  - [x]  https://github.com/elastic/logstash-docs/pull/865
- [ ] 7.7:  
   - [x] https://github.com/elastic/logstash-docs/pull/870
   - [x] https://github.com/elastic/logstash-docs/pull/861
- [ ] 7.6:  
   - [ ] https://github.com/elastic/logstash-docs/pull/873. Deleted PR without merging.
   - [x] https://github.com/elastic/logstash-docs/pull/862
- [ ] 6.8:  No changes

**2020-April**
- [x] master: https://github.com/elastic/logstash-docs/pull/857
- [x] 7.x: https://github.com/elastic/logstash-docs/pull/856
- [x] 7.7: https://github.com/elastic/logstash-docs/pull/855
- [x] 7.6: https://github.com/elastic/logstash-docs/pull/854
- [x] 6.8: https://github.com/elastic/logstash-docs/pull/858

**2020-March**
- [x] master:   
   - [x] https://github.com/elastic/logstash-docs/pull/850
   - [x] https://github.com/elastic/logstash-docs/pull/845
- [x] 7.x: 
   - [x] https://github.com/elastic/logstash-docs/pull/849
   - [x] https://github.com/elastic/logstash-docs/pull/844
- [ ] 7.6: No changes
- [x] 6.8:  Manual build: https://github.com/elastic/logstash-docs/pull/843

**2020-February**
- [x] master:     
   - [x] https://github.com/elastic/logstash-docs/pull/840
   - [x] https://github.com/elastic/logstash-docs/pull/833
- [x] 7.x: 
   - [x] https://github.com/elastic/logstash-docs/pull/839
   - [x] https://github.com/elastic/logstash-docs/pull/832
- [x] 7.6: 
   - [x] https://github.com/elastic/logstash-docs/pull/842
   - [x] https://github.com/elastic/logstash-docs/pull/838
   - [x] https://github.com/elastic/logstash-docs/pull/831
- [x] 7.5: https://github.com/elastic/logstash-docs/pull/830
- [x] 6.8:  
   - [x] Manual build: https://github.com/elastic/logstash-docs/pull/841
   - [x] Manual build: https://github.com/elastic/logstash-docs/pull/834 

**2020-January**
- [x] master:  
    - [x] https://github.com/elastic/logstash-docs/pull/825
    - [x] https://github.com/elastic/logstash-docs/pull/816
- [x] 7.x: 
    - [x] https://github.com/elastic/logstash-docs/pull/826
    - [x] https://github.com/elastic/logstash-docs/pull/817
- [x] 7.5: https://github.com/elastic/logstash-docs/pull/828
- [x] 7.4: https://github.com/elastic/logstash-docs/pull/829
- [x] 6.8:  https://github.com/elastic/logstash-docs/pull/818

**2019-December**
- [ ] master:  
- [ ] 7.x: 
- [x] 7.5: https://github.com/elastic/logstash-docs/pull/815
- [ ] 7.4: 
- [ ] 6.8:  
```
      `Task :generatePluginsVersion FAILED`
       `* Where:
        Build file '/Users/karenmetts/src/github/elastic/logstash/build.gradle' line: 416
        * What went wrong:
         Execution failed for task ':generatePluginsVersion'.
       > *java.lang.OutOfMemoryError: Java heap space*
```

**2019-November/December**
- [x] master:  https://github.com/elastic/logstash-docs/pull/807
- [x] 7.x: https://github.com/elastic/logstash-docs/pull/806
- [x] 7.5: https://github.com/elastic/logstash-docs/pull/803
- [x] 7.4: https://github.com/elastic/logstash-docs/pull/808
- [x] 6.8:  https://github.com/elastic/logstash-docs/pull/804

**2019-October**
- [x] master:  https://github.com/elastic/logstash-docs/pull/798 
- [x] 7.x: 
    - [x] https://github.com/elastic/logstash-docs/pull/800
    - [x] https://github.com/elastic/logstash-docs/pull/789 
- [x] 7.5: 
    - [x] https://github.com/elastic/logstash-docs/pull/799
    - [x] https://github.com/elastic/logstash-docs/pull/790 
- [x] 7.4: 
    - [x] https://github.com/elastic/logstash-docs/pull/797 
    - [x] https://github.com/elastic/logstash-docs/pull/786 
- [x] 7.3: https://github.com/elastic/logstash-docs/pull/794 
- [x] 7.2: https://github.com/elastic/logstash-docs/pull/792 
- [ ] 6.8:  Failing [on-demand gen](https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/32/).  Manual generation fails on `rake test:install-core`. 
Issue: https://github.com/elastic/docs-tools/issues/36

**Comment by karenzone** [comment]
Plugin doc generation/merge tracking continued in #12551
