### ISSUE TITLE
[meta] cloud-id support

### ISSUE THREAD

**Issue by kares** [elastic/logstash#11498]
this issue is tracking support for ES cloud_id/cloud_auth in LS
- [x] support cloud_id in ES output plugin https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/893
  https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/906
- [x] support cloud_id in ES input plugin
  https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/112
- [x] support cloud_id in ES filter plugin
  https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/122
- [x] support cloud_id in x-pack monitoring
  https://github.com/elastic/logstash/pull/11496
- [x] support cloud_id in x-pack management
  https://github.com/elastic/logstash/pull/11496
