### ISSUE TITLE
[Doc][Meta]Logstash 7.6 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#11527]
**Doc changes:**
- [x] Release notes: https://github.com/elastic/logstash/pull/11509
- [x] Docs for feature/deprecation logger adapter. 
  * [Doc]Add info about deprecation logger support mixin #11486
- [x] Prepared statements 
  - [x] logstash-filter-jdbc_streaming [#32](https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/pull/32) (Guy)
  - [x] logstash-input-jdbc [#349](https://github.com/logstash-plugins/logstash-input-jdbc/pull/349) (Guy)
  - [x] logstash-filter-jdbc_static.html [#53](https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/53) (Andrea)
- [x] Add Cloud ID and Cloud Auth to plugins (kares)
- [x] JDBC integration docs
- [x] Settings: clarify pipeline.workers (request from Support)
  * [Doc]Add details about pipeline.workers #11474 (WIP)
- [ ] Heuristics and tips for troubleshooting a pipeline (request from Support)
  * [Doc]Add tips for troubleshooting a pipeline  #11545 (WIP)

**Recurring:**
 - [x] Generate plugin docs #11269

**Ongoing/Other:**
- [ ] Hardening Guide  #11531  (TBD)
- [ ] Cloud workgroup
- [ ] Stack docs workgroup
- [x] Internal process docs
   - [x] Generating plugin documentation
   - [x] Release templates (minor/major/patch)  (WIP)
- [ ] GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)
