### ISSUE TITLE
[Doc][Meta] Improve documentation for Logstash to Cloud

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#11530]
Logstash can output to Elasticsearch on Cloud, but not everybody knows that. Current content is confusing and leads people to think that you can't send Logstash data to cloud. 

* Goal: Make capabilities more obvious and easier through better documentation and improved doc structure.
* Topic: https://www.elastic.co/guide/en/logstash/current/connecting-to-cloud.html

To Do: 
- [ ] Rework doc architecture in preparation for elevating cloud visibility. Restructure Configuring Logstash topics into *Basic* and *Optional* in preparation for reworking subsections.
- [ ] Doc and code changes to support Cloud ID (with @Kares). Related: 
   - [ ] es output
   - [ ] es filter
   - [ ] es 
- [ ] Remove "modules only" disclaimer for Cloud ID. WIP: https://github.com/elastic/logstash/pull/11469
- [ ] Move Cloud info out of Modules section 
- [ ] TBD. Should we still explain how to send ES output to Cloud using standard (not cloudID) configuration? Use cases?

Topic: https://www.elastic.co/guide/en/logstash/current/configuration.html

**Comment by kares** [comment]
> TBD. Should we still explain how to send ES output to Cloud using standard (not cloudID) configuration? Use cases?

not sure to answer this definitely but the cloud UI always shows the instance's "cloud-id". 
so we should consider that to be the common path for users setting up LS to use these ...

**Comment by JBodkin-LH** [comment]
The additional x-pack monitoring/management settings are missing from env2yaml, could these be added?

**Comment by karenzone** [comment]
@kares Let's take a look at this request and discuss.
