### ISSUE TITLE
[Meta Issue] Internal collector adjustments for 7.7

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#11573]
This issue is intended to track work on issue #11403, the task to execute are mainly:

- [x] create a configuration switch to enable the changes PR #11541
- [x] ~~document the new switch PR #11586~~
- [x] endpoint change from `_monitoring/bulk` -> `_bulk/monitoring` #11541
- [x] reshaping of the documents as discussed in https://github.com/elastic/logstash/issues/11403#issuecomment-563181908 PR #11541
- [x] when Logstash is enabled to use `_bulk/monitoring` actually we miss to set the index. We have to, still the template for that indices is managed by Elasticsearch
- [ ] ~~change monitoring index names from `.monitoring*` to `monitoring*`, removing the initial dot~~ this is excluded as per comment https://github.com/elastic/logstash/issues/11403#issuecomment-581597483
- [x] restructure the documentation regarding the new settings (`monitoring.*` instead of `xpack.monitoring.*`) for internal collectors PR #11714

**Comment by roaksoax** [comment]
All items are now complete into 7.7.0. Closing this meta issue.
