### ISSUE TITLE
[META] Implement ECS-Compatibility Mode in Bundled Plugins

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#11635]
Plugins that are bundled with Logstash need to be able to run in an ECS-Compatible mode by default in an upcoming major release of Logstash, unless explicitly configured to do otherwise.

> To determine the scope of changes needed to implement an ECS-Compatibility mode, a
> Logstash plugin will need to be categorized based on its implicit behavour to determine
> the effort to bring their defaults into ECS compliance:
> 
>  - Exclusively uses fields that _align_ with ECS (no ECS-Compatibility mode needed)
>  - Uses one or more fields that _conflict_ with ECS (ECS-Compatibility mode required)
>  - Uses one or more fields that are _undefined_ in the latest ECS and therefore at risk of future conflict (ECS-Compatibility mode recommended, aiming to minimize this risk)
>
> -- https://github.com/elastic/logstash/issues/11623

Below is our list of bundled plugins. The list will be kept up-to-date with links issues on the individual projects, along with one of the three categories (_align_, _conflict_, _undefined_).

## Input Plugins

Input Plugins are generally reliant on Codec Plugins to produce their event
structure, but many add metadata related to the source of the input (e.g.,
sender host info for inbound connections, file paths for discovered files, etc.),
and some include embedded Filter Plugins that must separately implement
ECS-Compatibility.

 - [ ] Tier 1 Supported Filters
   - [ ] [Azure_event_hubs Input](https://github.com/logstash-plugins/logstash-input-azure_event_hubs)
   - [ ] [Beats Input](https://github.com/logstash-plugins/logstash-input-beats)
   - [ ] [Elasticsearch Input](https://github.com/logstash-plugins/logstash-input-elasticsearch)
   - [ ] [File Input](https://github.com/logstash-plugins/logstash-input-file)
   - [ ] [Graphite Input](https://github.com/logstash-plugins/logstash-input-graphite)
   - [ ] [Heartbeat Input](https://github.com/logstash-plugins/logstash-input-heartbeat)
   - [ ] [HTTP Input](https://github.com/logstash-plugins/logstash-input-http)
   - [ ] [HTTP Poller Input](https://github.com/logstash-plugins/logstash-input-http_poller)
   - [ ] [JDBC Input*](https://github.com/logstash-plugins/logstash-integration-jdbc)
   - [ ] [Kafka Input*](https://github.com/logstash-plugins/logstash-integration-kafka)
   - [ ] [RabbitMQ Input*](https://github.com/logstash-plugins/logstash-integration-rabbitmq)
   - [ ] [Redis Input](https://github.com/logstash-plugins/logstash-input-redis)
   - [ ] [S3 Input](https://github.com/logstash-plugins/logstash-input-s3)
   - [ ] [Stdin Input](https://github.com/logstash-plugins/logstash-input-stdin)
   - [ ] [Syslog Input](https://github.com/logstash-plugins/logstash-input-syslog)
   - [ ] [TCP Input](https://github.com/logstash-plugins/logstash-input-tcp)
   - [ ] [UDP Input](https://github.com/logstash-plugins/logstash-input-udp)
 - [ ] Tier 2 Supported Filters
   - [ ] [Couchdb_changes Input](https://github.com/logstash-plugins/logstash-input-couchdb_changes)
   - [ ] [Dead_letter_queue Input](https://github.com/logstash-plugins/logstash-input-dead_letter_queue)
   - [ ] [Exec Input](https://github.com/logstash-plugins/logstash-input-exec)
   - [ ] [Ganglia Input](https://github.com/logstash-plugins/logstash-input-ganglia)
   - [ ] [Gelf Input](https://github.com/logstash-plugins/logstash-input-gelf)
   - [ ] [Generator Input](https://github.com/logstash-plugins/logstash-input-generator)
   - [ ] [Imap Input](https://github.com/logstash-plugins/logstash-input-imap)
   - [ ] [Jms Input](https://github.com/logstash-plugins/logstash-input-jms)
   - [ ] [Pipe Input](https://github.com/logstash-plugins/logstash-input-pipe)
   - [ ] [Snmp Input](https://github.com/logstash-plugins/logstash-input-snmp)
   - [ ] [Snmptrap Input](https://github.com/logstash-plugins/logstash-input-snmptrap)
   - [ ] [Sqs Input](https://github.com/logstash-plugins/logstash-input-sqs)
   - [ ] [Twitter Input](https://github.com/logstash-plugins/logstash-input-twitter)
   - [ ] [Unix Input](https://github.com/logstash-plugins/logstash-input-unix)

## Codec Plugins

Codec Plugins produce Events from a sequence of Bytes, and are responsible for
the basic structure of those Events, and while some implicitly take the produced
structure verbatim from the deserialized input (e.g., JSON*), others decode the
bytes they are given into their own structure (e.g., CEF). 

 - [ ] Tier 1 Supported Codecs
   - [ ] [Avro Codec](https://github.com/logstash-plugins/logstash-codec-avro)
   - [ ] [CEF Codec](https://github.com/logstash-plugins/logstash-codec-cef)
   - [ ] [ES_bulk Codec](https://github.com/logstash-plugins/logstash-codec-es_bulk)
   - [ ] [JSON Codec](https://github.com/logstash-plugins/logstash-codec-json)
   - [ ] [JSON_lines Codec](https://github.com/logstash-plugins/logstash-codec-json_lines)
   - [ ] [Line Codec](https://github.com/logstash-plugins/logstash-codec-line)
   - [ ] [Multiline Codec](https://github.com/logstash-plugins/logstash-codec-multiline)
   - [ ] [Plain Codec](https://github.com/logstash-plugins/logstash-codec-plain)
   - [ ] [RubyDebug Codec](https://github.com/logstash-plugins/logstash-codec-rubydebug)
 - [ ] Tier 2 Supported Codecs
   - [ ] [Dots Codec](https://github.com/logstash-plugins/logstash-codec-dots)
   - [ ] [EDN Codec](https://github.com/logstash-plugins/logstash-codec-edn)
   - [ ] [EDN_lines Codec](https://github.com/logstash-plugins/logstash-codec-edn_lines)
   - [ ] [Fluent Codec](https://github.com/logstash-plugins/logstash-codec-fluent)
   - [ ] [Graphite Codec](https://github.com/logstash-plugins/logstash-codec-graphite)
   - [ ] [MsgPack Codec](https://github.com/logstash-plugins/logstash-codec-msgpack)
   - [ ] [Netflow Codec](https://github.com/logstash-plugins/logstash-codec-netflow)
   - [ ] [Collectd Codec](https://github.com/logstash-plugins/logstash-codec-collectd)

## Filter Plugins

Filter plugins manipulate Events by reading and writing from their fields. To be
ECS-Compatible, a Filter must not read from or write to ECS-conflicting fields
unless the field name is explicitly given in the plugin's configuration.

 - [ ] Tier 1 Supported Filters
   - [ ] [CIDR Filter](https://github.com/logstash-plugins/logstash-filter-cidr)
   - [ ] [Clone Filter](https://github.com/logstash-plugins/logstash-filter-clone)
   - [ ] [Csv Filter](https://github.com/logstash-plugins/logstash-filter-csv)
   - [ ] [Date Filter](https://github.com/logstash-plugins/logstash-filter-date)
   - [ ] [Dissect Filter](https://github.com/logstash-plugins/logstash-filter-dissect)
   - [ ] [Dns Filter](https://github.com/logstash-plugins/logstash-filter-dns)
   - [ ] [Drop Filter](https://github.com/logstash-plugins/logstash-filter-drop)
   - [ ] [Elasticsearch Filter](https://github.com/logstash-plugins/logstash-filter-elasticsearch)
   - [ ] [Grok Filter](https://github.com/logstash-plugins/logstash-filter-grok)
   - [ ] [HTTP Filter](https://github.com/logstash-plugins/logstash-filter-http)
   - [ ] [Fingerprint Filter](https://github.com/logstash-plugins/logstash-filter-fingerprint)
   - [ ] [Geoip Filter](https://github.com/logstash-plugins/logstash-filter-geoip)
   - [ ] [JDBC Static Filter*](https://github.com/logstash-plugins/logstash-integration-jdbc)
   - [ ] [JDBC Streaming Filter*](https://github.com/logstash-plugins/logstash-integration-jdbc)
   - [ ] [JSON Filter](https://github.com/logstash-plugins/logstash-filter-json)
   - [ ] [KV Filter](https://github.com/logstash-plugins/logstash-filter-kv)
   - [ ] [Memcached Filter](https://github.com/logstash-plugins/logstash-filter-memcached)
   - [ ] [Mutate Filter](https://github.com/logstash-plugins/logstash-filter-mutate)
   - [ ] [Prune Filter](https://github.com/logstash-plugins/logstash-filter-prune)
   - [ ] [Ruby Filter](https://github.com/logstash-plugins/logstash-filter-ruby)
   - [ ] [Sleep Filter](https://github.com/logstash-plugins/logstash-filter-sleep)
   - [ ] [Split Filter](https://github.com/logstash-plugins/logstash-filter-split)
   - [ ] [Syslog_pri Filter](https://github.com/logstash-plugins/logstash-filter-syslog_pri)
   - [ ] [Translate Filter](https://github.com/logstash-plugins/logstash-filter-translate)
   - [ ] [Truncate Filter](https://github.com/logstash-plugins/logstash-filter-truncate)
   - [ ] [Urldecode Filter](https://github.com/logstash-plugins/logstash-filter-urldecode)
   - [ ] [Useragent Filter](https://github.com/logstash-plugins/logstash-filter-useragent)
   - [ ] [Uuid Filter](https://github.com/logstash-plugins/logstash-filter-uuid)
   - [ ] [Xml Filter](https://github.com/logstash-plugins/logstash-filter-xml)
 - [ ] Tier 2 Supported Filters
   - [ ] [Aggregate Filter](https://github.com/logstash-plugins/logstash-filter-aggregate)
   - [ ] [Anonymize Filter](https://github.com/logstash-plugins/logstash-filter-anonymize)
   - [ ] [De_dot Filter](https://github.com/logstash-plugins/logstash-filter-de_dot)
   - [ ] [Metrics Filter](https://github.com/logstash-plugins/logstash-filter-metrics)
   - [ ] [Throttle Filter](https://github.com/logstash-plugins/logstash-filter-throttle)

## Output Plugins

Output Plugins do not generally manipulate event structure, but are included in
this list for completeness as some may benefit from an ECS-Compatibility
mode (e.g. Elasticsearch's template management).

### Output Plugins
 - [ ] Tier 1 Supported Outputs
   - [ ] [Elasticsearch Output](https://github.com/logstash-plugins/logstash-output-elasticsearch)
   - [ ] [Email Output](https://github.com/logstash-plugins/logstash-output-email)
   - [ ] [File Output](https://github.com/logstash-plugins/logstash-output-file)
   - [ ] [HTTP Output](https://github.com/logstash-plugins/logstash-output-http)
   - [ ] [Kafka Output*](https://github.com/logstash-plugins/logstash-integration-kafka)
   - [ ] [Redis Output](https://github.com/logstash-plugins/logstash-output-redis)
   - [ ] [S3 Output](https://github.com/logstash-plugins/logstash-output-s3)
   - [ ] [Stdout Output](https://github.com/logstash-plugins/logstash-output-stdout)
   - [ ] [TCP Output](https://github.com/logstash-plugins/logstash-output-tcp)
   - [ ] [UDP Output](https://github.com/logstash-plugins/logstash-output-udp)
 - [ ] Tier 1 Supported Outputs
   - [ ] [Cloudwatch Output](https://github.com/logstash-plugins/logstash-output-cloudwatch)
   - [ ] [Csv Output](https://github.com/logstash-plugins/logstash-output-csv)
   - [ ] [Elastic_app_search Output](https://github.com/logstash-plugins/logstash-output-elastic_app_search)
   - [ ] [Graphite Output](https://github.com/logstash-plugins/logstash-output-graphite)
   - [ ] [Lumberjack Output](https://github.com/logstash-plugins/logstash-output-lumberjack)
   - [ ] [Nagios Output](https://github.com/logstash-plugins/logstash-output-nagios)
   - [ ] [Null Output](https://github.com/logstash-plugins/logstash-output-null)
   - [ ] [Pipe Output](https://github.com/logstash-plugins/logstash-output-pipe)
   - [ ] [Sns Output](https://github.com/logstash-plugins/logstash-output-sns)
   - [ ] [Sqs Output](https://github.com/logstash-plugins/logstash-output-sqs)
   - [ ] [WebHDFS Output](https://github.com/logstash-plugins/logstash-output-webhdfs)

**Comment by inqueue** [comment]
Are there any plans to add Zeek/Suricata ECS support in Logstash?

**Comment by roaksoax** [comment]
Related issue: https://github.com/elastic/logstash/issues/11306

**Comment by yaauie** [comment]
> Are there any plans to add Zeek/Suricata ECS support in Logstash?

No specific effort that I'm aware of, as both the Zeek and Suricata modules referenced are implemented in Beats (not Logstash).
