### ISSUE TITLE
upgrade all plugins to dockerized testing

### ISSUE THREAD

**Issue by kares** [elastic/logstash#11662]
we're starting to hit errors running plugin tests due the JRuby (9.2.11.0) upgrade: https://github.com/elastic/logstash/pull/11647

> LS is preferring not to use JRuby deprecated APIs so the upgrade forced us to use newer native Java methods (the existing methods printed deprecation warnings). The new methods however are not available in old JRubies (9.1.13.0) and we're starting to hit this issue of testing latest logstash-core (8.0) snapshot under JRuby 9.1.13.0. 

... from https://github.com/logstash-plugins/logstash-input-generator/pull/18 and a [sample ci failure](https://travis-ci.org/logstash-plugins/logstash-input-generator/jobs/658865932#L449-L453)

This should force us moving forward to get all plugins to use out standardized (.ci) testing.
Some plugins already use Dockerized testing but a fair amount is still left with a fixed JRuby version and installs various versions of *logstash-core*.

#### Plugins to migrate towards centralized travis setup:

- [x] logstash-codec-avro
- [x] logstash-codec-cef
- [x] logstash-codec-cloudfront
- [x] logstash-codec-cloudtrail
- [x] logstash-codec-collectd
- [x] logstash-codec-compress_spooler
- [x] logstash-codec-csv
- [x] logstash-codec-dots
- [x] logstash-codec-edn
- [x] logstash-codec-edn_lines
- [x] logstash-codec-es_bulk
- [x] logstash-codec-example
- [x] logstash-codec-fluent
- [x] logstash-codec-graphite
- [x] logstash-codec-gzip_lines
- [x] logstash-codec-json
- [x] logstash-codec-json_lines
- [x] logstash-codec-line
- [x] logstash-codec-msgpack
- [x] logstash-codec-multiline
- [x] logstash-codec-netflow
- [x] logstash-codec-nmap
- [x] logstash-codec-oldlogstashjson
- [x] logstash-codec-plain
- [x] logstash-codec-pretty
- [x] logstash-codec-protobuf
- [x] logstash-codec-rubydebug
- [x] logstash-codec-s3plain
- [x] logstash-filter-age
- [x] logstash-filter-aggregate
- [x] logstash-filter-alter
- [x] logstash-filter-anonymize
- [x] logstash-filter-bytes
- [x] logstash-filter-checksum
- [x] logstash-filter-cidr
- [x] logstash-filter-cipher
- [x] logstash-filter-clone
- [x] logstash-filter-collate
- [x] logstash-filter-csv
- [x] logstash-filter-date
- [x] logstash-filter-de_dot
- [x] logstash-filter-dissect
- [x] logstash-filter-dns
- [x] logstash-filter-drop
- [x] logstash-filter-elapsed
- [x] logstash-filter-elasticsearch
- [x] logstash-filter-emoji
- [x] logstash-filter-environment
- [x] logstash-filter-example
- [x] logstash-filter-extractnumbers
- [x] logstash-filter-fingerprint
- [x] logstash-filter-geoip
- [x] logstash-filter-grok
- [x] logstash-filter-hashid
- [x] logstash-filter-http
- [x] logstash-filter-i18n
- [x] logstash-filter-jdbc_static
- [x] logstash-filter-json
- [x] logstash-filter-json_encode
- [x] logstash-filter-kubernetes_metadata
- [x] logstash-filter-kv
- [x] logstash-filter-language
- [x] logstash-filter-math
- [x] logstash-filter-memcached
- [x] logstash-filter-metaevent
- [x] logstash-filter-metricize
- [x] logstash-filter-metrics
- [x] logstash-filter-multiline
- [x] logstash-filter-mutate
- [x] logstash-filter-oui
- [x] logstash-filter-prune
- [x] logstash-filter-punct
- [x] logstash-filter-range
- [x] logstash-filter-ruby
- [x] logstash-filter-sleep
- [x] logstash-filter-split
- [x] logstash-filter-syslog_pri
- [x] logstash-filter-throttle
- [x] logstash-filter-tld
- [x] logstash-filter-translate
- [x] logstash-filter-truncate
- [x] logstash-filter-unique
- [x] logstash-filter-urldecode
- [x] logstash-filter-useragent
- [x] logstash-filter-uuid
- [x] logstash-filter-xml
- [x] logstash-filter-yaml
- [x] logstash-input-azure_event_hubs
- [x] logstash-input-beats
- [x] logstash-input-cloudwatch
- [x] logstash-input-couchdb_changes
- [x] logstash-input-dead_letter_queue
- [x] logstash-input-drupal_dblog
- [x] logstash-input-elasticsearch
- [x] logstash-input-eventlog
- [x] logstash-input-example
- [x] logstash-input-exec
- [x] logstash-input-file
- [x] logstash-input-fluentd
- [x] logstash-input-ganglia
- [x] logstash-input-gelf
- [x] logstash-input-gemfire
- [x] logstash-input-generator
- [x] logstash-input-github
- [x] logstash-input-google_cloud_storage
- [x] logstash-input-google_pubsub
- [x] logstash-input-graphite
- [x] logstash-input-heartbeat
- [x] logstash-input-heroku
- [x] logstash-input-http
- [x] logstash-input-http_poller
- [x] logstash-input-imap
- [x] logstash-input-irc
- [x] logstash-input-jms
- [x] logstash-input-jmx
- [x] logstash-input-kinesis
- [x] logstash-input-log4j
- [x] logstash-input-lumberjack
- [x] logstash-input-meetup
- [x] logstash-input-neo4j
- [x] logstash-input-perfmon
- [x] logstash-input-pipe
- [x] logstash-input-puppet_facter
- [x] logstash-input-rabbitmq
- [x] logstash-input-rackspace
- [x] logstash-input-redis
- [x] logstash-input-relp
- [x] logstash-input-rss
- [x] logstash-input-s3
- [x] logstash-input-s3sqs
- [x] logstash-input-salesforce
- [x] logstash-input-snmp
- [x] logstash-input-snmptrap
- [x] logstash-input-sqlite
- [x] logstash-input-sqs
- [x] logstash-input-stdin
- [x] logstash-input-stomp
- [x] logstash-input-syslog
- [x] logstash-input-tcp
- [x] logstash-input-twitter
- [x] logstash-input-udp
- [x] logstash-input-unix
- [x] logstash-input-varnishlog
- [x] logstash-input-websocket
- [x] logstash-input-wmi
- [x] logstash-input-xmpp
- [x] logstash-input-zenoss
- [x] logstash-integration-internal
- [x] logstash-integration-jdbc
- [x] logstash-integration-kafka
- [x] logstash-integration-rabbitmq
- [x] logstash-mixin-aws
- [x] logstash-mixin-zeromq
- [x] logstash-output-boundary
- [x] logstash-output-circonus
- [x] logstash-output-cloudwatch
- [x] logstash-output-csv
- [x] logstash-output-datadog
- [x] logstash-output-datadog_metrics
- [x] logstash-output-elastic_app_search
- [x] logstash-output-elasticsearch
- [x] logstash-output-email
- [x] logstash-output-example
- [x] logstash-output-exec
- [x] logstash-output-file
- [x] logstash-output-ganglia
- [x] logstash-output-gelf
- [x] logstash-output-gemfire
- [x] logstash-output-google_bigquery
- [x] logstash-output-google_cloud_storage
- [x] logstash-output-google_pubsub
- [x] logstash-output-graphite
- [x] logstash-output-graphtastic
- [x] logstash-output-hipchat
- [x] logstash-output-http
- [x] logstash-output-icinga
- [x] logstash-output-influxdb
- [x] logstash-output-irc
- [x] logstash-output-jira
- [x] logstash-output-jms
- [x] logstash-output-juggernaut
- [x] logstash-output-librato
- [x] logstash-output-loggly
- [x] logstash-output-lumberjack
- [x] logstash-output-metriccatcher
- [x] logstash-output-monasca_log_api
- [x] logstash-output-mongodb
- [x] logstash-output-nagios
- [x] logstash-output-nagios_nsca
- [x] logstash-output-neo4j
- [x] logstash-output-newrelic
- [x] logstash-output-null
- [x] logstash-output-opentsdb
- [x] logstash-output-pagerduty
- [x] logstash-output-pipe
- [x] logstash-output-rackspace
- [x] logstash-output-redis
- [x] logstash-output-redmine
- [x] logstash-output-riak
- [x] logstash-output-riemann
- [x] logstash-output-s3
- [x] logstash-output-slack
- [x] logstash-output-sns
- [x] logstash-output-solr_http
- [x] logstash-output-sqs
- [x] logstash-output-statsd
- [x] logstash-output-stdout
- [x] logstash-output-stomp
- [x] logstash-output-syslog
- [x] logstash-output-tcp
- [x] logstash-output-timber
- [x] logstash-output-udp
- [x] logstash-output-webhdfs
- [x] logstash-output-websocket
- [x] logstash-output-xmpp
- [x] logstash-output-zabbix
- [x] logstash-output-zookeeper
- [x] logstash-patterns-core

**Comment by jsvd** [comment]
currently missing plugins:

- [ ] logstash-input-elasticsearch
- [ ] logstash-filter-elasticsearch
- [ ] logstash-output-elasticsearch
- [ ] logstash-filter-grok
- [ ] logstash-input-azure_event_hubs

**Comment by jsvd** [comment]
### Plugins that won't be migrated:



#### Broken plugins that haven't been used in many years:
- logstash-input-zeromq
- logstash-filter-zeromq
- logstash-output-zeromq
- logstash-input-journald

#### Already present in "logstash-integration-kafka"
- logstash-input-kafka
- logstash-output-kafka

#### Already present in "logstash-integration-rabbitmq"
- logstash-input-rabbitmq
- logstash-output-rabbitmq
- logstash-mixin-rabbitmq_connection

#### Already present in "logstash-integration-jdbc"
- logstash-input-jdbc
- logstash-filter-jdbc_static
- logstash-filter-jdbc_streaming

#### Mixins:
- logstash-mixin-deprecation_logger_support
- logstash-mixin-ecs_compatibility_support
- logstash-mixin-http_client

#### Experiments:
- logstash-integration-elasticsearch

#### Archived:
- logstash-output-appsearch
- logstash-output-elasticsearch_java

### Repositories under `logstash-plugins` org that don't have a `.travis.yml`:

- contributions
- logstash-codec-java_codec_example
- logstash-codec-json_pretty
- logstash-codec-sflow
- logstash-filter-bytesize
- logstash-filter-cloudfoundry
- logstash-filter-debug
- logstash-filter-java_filter_example
- logstash-filter-lookup
- logstash-filter-script
- logstash-input-cloudwatch_logs
- logstash-input-dynamodb
- logstash-input-googleanalytics
- logstash-input-java_input_example
- logstash-input-jmx-pipe
- logstash-input-log4j2
- logstash-input-mongodb
- logstash-input-netflow
- logstash-integration-aws
- logstash-integration-azure
- logstash-integration-zeromq
- logstash-loggable-bwc
- logstash-output-beats
- logstash-output-firehose
- logstash-output-java_output_example
- logstash-output-logentries
- logstash-output-rados
- plugins_ci_shared

**Comment by jsvd** [comment]
218 repositories in github.com/logstash-plugins have been migrated to use the travis tests in https://github.com/logstash-plugins/.ci/tree/1.x

The exceptions are listed in the [comment above](https://github.com/elastic/logstash/issues/11662#issuecomment-605097921).

Closing here 🎉

**Comment by kares** [comment]
yay, :ice_cream: :icecream: :ice_cream: thank you for doing all the house-keeping around plugins.
