### ISSUE TITLE
[Meta] Expand Logstash JDK ecosystem

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#11696]
The currently stage of Logstash support for JDKs is limited to Oracle and OpenJDK's 11. In an effort to bring Logstash forward, we are looking to improve Logstash Java support for newer versions, as well as expand its support for JDKs, such as AdoptOpenJDK and others, as well as newer versions.

To be able to move this forward there are a few considerations:

 * First, Logstash needs to have the ability to run against different JDK versions and flavors. With that, Logstash itself (and its dependencies and internals) need to be proven to work correctly with such versions and flavors.
 * Second, to be able to support this moving forward, Logstash testing infrastructure needs to be improve to be able to consistently test against all these flavors/versions to be able to support them moving forward.
 * Lastly, Logstash will bundle a default JDK flavor and version, and build all the release artifacts to provide this, including a JDK less version.

Expected Tasks
===========
Part 1:  Support AdoptOpenJDK 11/Zulu 11 & Update basic infrastructure
- [x] [andsel] Improve Logstash core to be able to run against multiple JDK versions (env variable) #11708 
- [x] [andsel] Add CI Jobs to test against AdoptOpenJDK 11 (Linux) https://github.com/elastic/infra/pull/19471
- [x] Add CI jobs to test against AdoptOpenJDK 11 (Windows)
- [x] [andsel]Add CI jobs to test aagainst Zulu 14 (Windows) #11888
- [x] Add CI Jobs to test against Zulu 11 (Windows) https://github.com/elastic/infra/pull/19599 #11865 #11869 #11878
- [x] [andsel] Add compatibility job across multiple Linux distros also for JDK matrix (Unix) https://github.com/elastic/infra/pull/19922
- [x] [andsel] set fixed list of Linux distros to avoid spurious errors (OpenSuse 43.2 and JDK 14) https://github.com/elastic/infra/pull/20204
- [x] [andsel] drop docker to run the build directly into the host OS https://github.com/elastic/infra/pull/20302 https://github.com/elastic/infra/pull/20485
- [x] [andsel] remove Zulu from Linux JDK matrix (#11898)
- [x] [andsel] ~~move OSes axes out of JJB definitions and put into Logstash repository files. https://github.com/elastic/infra/pull/20517 https://github.com/elastic/logstash/pull/11913~~

Part 2: Support JDK14  
- [x] [rob] Upgrade build infrastructure (gradle) to support newer JDKs. 
- [x] [andsel] Add CI Jobs to test against OpenJDK14 #11801
- [x] Add CI Jobs to test against AdoptOpenJDK14
- [x] Identify a list of issues that would need to be addressed before claiming support for JDK14+.
  - [x] Investigate build failures on OpenSuse-42-3 https://github.com/elastic/infra/issues/19887
  - [x] Remove OpenSuse-42-3 from list of distros to test against JDK14 https://github.com/elastic/infra/pull/19889
- [x] Address all blockers to support JDK14
  - [x] Replace use of deprecated method `getSystemCpuLoad` #11786

Part 3: Documentation
- [x] Documentation on how to change/use JAVA_HOME https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html
- [x] Update Getting started docs to reference additional Java support
- [x] Update reference to Java8 on download page
- [x] Update product support matrix

Related Issues
==========

- https://github.com/elastic/logstash/issues/11514

**Comment by ppf2** [comment]
Please also add G1GC testing and related documentation to the test plan. thx!

**Comment by roaksoax** [comment]
Moved the bundling of JDK to https://github.com/elastic/logstash/issues/12137

**Comment by roaksoax** [comment]
All items have been complete, and closing this meta issue.
