### ISSUE TITLE
[Meta] Add support for aarch64

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#11767]
Purpose
======
Logstash needs to start building aarch64 packages and docker images, have them integrated in the CI testing and release process.

Expected Tasks
===========

- [x] Fix Logstash ffi loading (Experimental branch [here](https://github.com/elastic/logstash/compare/aarch64_wip)
- [x] Add CI testing for aarch64
  - [x] Enable loading aarch64 versions of Beats and Elasticsearch in integration tests
  - [x] Add CI jobs for aarch64
- [x] Fix CI for aarch64 
- [x] Add tests for Docker images

These areas are somewhat interdependent with the JDK bundling - once the JDK bundling is in place, the packaging will need to be reworked to include the correct version of the JDK according to architecture and to create architecture specific images and docker releases.

- [x] Enable aarch64 package / docker image creation  #11866
  - [x] [INPROGRESS] Create release artifacts to publish aarch64 images
  - [x] Update release manager to build `aarch64` Docker images on `aarch64` machines
  - [x] Create aarch64 deb/rpm packages.
  - [x] Create aarch64 .tar.gz

**Comment by CpuID** [comment]
Will these new images be published on https://www.docker.elastic.co/r/logstash shortly? Thanks :)

**Comment by CpuID** [comment]
> Will these new images be published on https://www.docker.elastic.co/r/logstash shortly? Thanks :)

context: https://www.docker.elastic.co/r/elasticsearch already has arm64

**Comment by robbavey** [comment]
@CpuID Snapshot builds are currently being published - see https://www.docker.elastic.co/r/logstash?show_snapshots=true for `8.0.0-SNAPSHOT` and `7.x-SNAPSHOT`. These are still experimental builds and not suitable for production purposes, but we welcome any early feedback on these images
