### ISSUE TITLE
[meta] support for elasticsearch API key

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#11788]
This is what need to be done to support [Elasticsearch API key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html)  for access from Logstash without requiring basic authentication.

### Plugins
- [X] add support for `api_key` option in logstash-input-elasticsearch https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/131
- [x] add support for `api_key` option in logstash-filter-elasticsearch https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/132
- [x] add support for `api_key` option in logstash-output-elasticsearch https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/908 https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/934
- [x] documentation for plugins `api_key` support

### Logstash
Related issue #11748
- [x]  add support for `api_key` option in xpack monitoring and management #11864
- [x] Documentation for `api_key` for monitoring and management

**Comment by colinsurprenant** [comment]
PR for elasticsearch output https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/934

**Comment by colinsurprenant** [comment]
logstash-output-elasticsearch v10.5.0 with API ket support is published.

**Comment by colinsurprenant** [comment]
Created #11864 for xpack monitoring and management

**Comment by colinsurprenant** [comment]
PR up for elasticsearch filter https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/132

**Comment by colinsurprenant** [comment]
PR up for elasticsearch input https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/131

**Comment by colinsurprenant** [comment]
All plugins now support api_key starting at versions:
- logstash-input-elasticsearch v4.7.0
- logstash-filter-elasticsearch v3.8.0
- logstash-output-elasticsearch v10.5.0

xpack management and monitoring now support api_key in master (for v8.0.0) and in 7.x (for 7.9.0)

Closing,
