### ISSUE TITLE
Improvements to Slow Logger feature

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11811]
The slow logger is a very useful feature, meant to be the first step towards debugging a slow pipeline. When enabled, it signals that events are taking too long to be processed somewhere in the pipeline workers, which execute the filters + outputs.

But currently the feature has several limitations:
- [ ] doesn't track outputs, only filters
- [ ] doesn't track `multi_filter` calls in filters, [only single event `filter`](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/filters/base.rb#L160) (e.g. date filter is excluded)
- [ ] no support for dynamic configuration of slowlog thresholds. since slowlog is off by default it requires users to restart logstash to configure slowlog.
