### ISSUE TITLE
[Meta] Fix failing CI for plugins

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#11941]
Passing CI is a requirement for publishing updated plugins. Failing CI has no impact on currently published plugins. 

**BLOCKERS:**
- [ ] TBD  

**19 plugin jobs failing** for `master` (according to Jarvis) as of 2020-08-31, M):

```[tasklist]
### Plugins
- [x] logstash-filter-anonymize
- [x] logstash-filter-dissect
- [x] logstash-filter-grok
- [x] logstash-filter-json
- [x] logstash-filter-mutate
- [x] logstash-filter-split
- [x] ogstash-filter-throttle
- [x] logstash-filter-translate
- [x] logstash-filter-urldecode
- [x] logstash-input-http_poller
- [x] logstash-input-pipe
- [x] logstash-input-unix
- [x] logstash-output-elastic_app_search
- [x] logstash-output-elasticsearch
- [x] logstash-output-sns
- [x] logstash-filter-fingerprint
- [ ] logstash-codec-netflow
- [ ] logstash-output-email
- [ ] logstash-input-ganglia
- [ ] logstash-input-graphite
```

**Comment by karenzone** [comment]
@elastic/logstash

**Comment by karenzone** [comment]
**From 2020-0528**
Fixed:
- [ ] logstash-input-imap

**Comment by kaisecheng** [comment]
| plugin | reason | issues |
| --- | --- | --- |
| logstash-codec-netflow | LS 8 nano timestamp | |
| logstash-filter-anonymize | murmurhash3 didn't publish 0.1.7-java | |
| logstash-filter-fingerprint | murmurhash3 didn't publish 0.1.7-java | |

**Comment by kaisecheng** [comment]
The following plugins are still failing. Others are green

- logstash-codec-netflow
- logstash-input-ganglia
- logstash-input-graphite
- logstash-output-email
