### ISSUE TITLE
[Meta] Improvements in Logstash Testing

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#11950]
Logstash runs a number of different types, including unit tests, integration tests, compatibility tests and acceptance tests. Over time, these tests have accumulated a certain amount of technical debt, and issues with coverage and usefulness.

This includes basic issues, such as [key plugin tests regularly failing](#11941); coverage gaps, such as poor or non-existent test coverage for Docker and Windows; old or redundant tests, such as acceptance tests being run mostly against old versions of Linux distributions and more long term efforts, such as migrating tests away from the infra repo into the Logstash repo, to give more control over testing to the Logstash team.

This meta issue is intended to capture the issues and areas for improvement that can be made to improve the level of testing across Logstash and it's plugins to help alleviate these issues

### Expected Tasks

Part 1: Short term improvements/quick fixes

- [ ] Fix failing plugin tests #11941 
- [x] Update integration tests to branch appropriate versions of Beats #11958
- [x] Update integration tests to branch appropriate versions of Elasticsearch
- [ ] Add documentation to help users run dockerized tests for plugins

Part 2: Medium Term Improvements

- [x] Testing for official docker images #12135
- [ ] Add better support for testing on Windows
  - [ ] Smoke testing ensuring plugin installation, logstash starts...
  - [ ] Integration Test support
  - [ ] Integration testing of plugins that may have proportionally more windows users (JDBC with MSSQL Server? File Input? Beats input (WinlogBeat?)
- [ ] Improve acceptance/smoke testing for modern operating systems
- [x] Rationalize/Modernize Compatibility and Acceptance Tests
  - Do we need compatibility and acceptance tests? Perhaps ‘smoke/check’ tests that are relatively short running and can be run across a variety of platforms.
  - Do we want to continue with the Vagrant approach? Or use bare metal servers provisioned by infra?
 - [ ] [Identify](https://gist.github.com/robbavey/36046cd132523077dff14512ddbe2556) and remove/improve slowest tests.
- [ ] JDK Testing
  - [x] Add acceptance job also for JDK matrix (Unix)
  - [x] Move main jobs to no longer use docker (and use base OS)

Part 3: Longer Term Improvements

 - [x] Transition build jobs out of Infra repo into Logstash repo.
 - [ ] Regular benchmarking tests to catch performance regressions.
 - [ ] Integration tests with cloud services

**Comment by robbavey** [comment]
Closing - most of the tasks have been completed during the move from jenkins to buildkite.

Will create individual tasks if required
