### ISSUE TITLE
[Doc][Meta]Logstash 7.9 documentation roadmap 

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12008]
**Doc changes:**
- [x]  Security: API keys for monitoring and management [#12149](https://github.com/elastic/logstash/pull/12149)
- [ ]  Rework security docs (WIP)
  - [ ] TO DO: Expand content in new section
- [ ]  Cloud First work ([Meta issue #11530](https://github.com/elastic/logstash/issues/11530))
  - [ ] [[Doc]Relocate logstash-to-cloud topic for increased visibility #11884](https://github.com/elastic/logstash/pull/11884)
- [x] Monitoring: 
  - [x] [[Docs] Deprecate legacy monitoring #11979](https://github.com/elastic/logstash/issues/11979)
  - [x] Doc:Add monitoring and management to API key security content [#12149](https://github.com/elastic/logstash/pull/12149)
- [ ]  Integration plugin docs infrastructure
  - [x] Add new header for Logstash Reference: [#11891](https://github.com/elastic/logstash/pull/11891) and [#12163](elastic/logstash#12163)
  - [x] Add new integration plugin header for Versioned Plugin Reference: [#891](elastic/logstash-docs#891)
  - [ ] Implement for jdbc: [#40](https://github.com/logstash-plugins/logstash-integration-jdbc/pull/40) - pending review
  - [ ] Implement for kafka: [#46](https://github.com/logstash-plugins/logstash-integration-kafka/pull/46) - pending review
  - [ ] Implement for rabbitmq: [#34](https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/34) - pending review
- [ ]  PQ work
- [ ] Formalize process for listing external plugins- WIP
- [ ] TODO: Add issues from the Logstash 7.9 roadmap

**Recurring:**
- [x] [Meta]Generate plugin docs #11269

**Plugin quality:**
- [x] Logstash-input-elasticsearch 4.7.1 [#135](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/135)
  - [ ] [Doc:Fix links to es broken at 7.9 cutover (VPR) #893](https://github.com/elastic/logstash-docs/pull/893)
  - [x] [Doc:Update sliced scroll link to resolve to new location #894](https://github.com/elastic/logstash-docs/pull/894)

**Release notes:**
- [x] [Featured items](https://docs.google.com/document/d/1WCWWl3-J85PXhaVBpDopn8gz03mtkUJP6hXAvBMVe6Q/edit#)
- [x] PR: https://github.com/elastic/logstash/pull/12179

**Process improvements**
- [x] [Restrict docgen builds to machines equipped with the right set up #44](https://github.com/elastic/docs-tools/issues/44)
  - [x] Addressed by docs infra: [#21918](https://github.com/elastic/infra/pull/21918)

**Ongoing/Other:**
- [ ]  Hardening Guide #11531 (TBD)
- [ ]  Cloud workgroup
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)
