### ISSUE TITLE
[Meta] Bundle JDK with Logstash artifacts

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#12137]
Logstash currently ships with no bundled JDK, which requires users to install a JDK before installing Logstash (e.g. debian package or rpm require JDK to be installed first). This can lead to further issues and reduces the ease of use for a first time user. Furthermore, other products, such as Elasticsearch, are already shipped with a JDK. In order to standardize with the rest of the stack on this, we would like to ship Logstash with a bundled JDK.

Expected Tasks
===========
- [x] [andsel] Bundle AdoptOpenJDK for (creates oss/bundled for amd64):
  - [x] Linux based artifacts (tar.gz/rpm/deb #11845)
  - [x] MacOS (tar.gz #11845)
  - [x]  Windows (.zip #11845)
  - [x] rpm/deb/linux tar.gz for arm64 (~#12216~ #12267)
  - [x] update the CI to run `acceptance_tests.sh` on deb artifact for arm64 (https://github.com/elastic/infra/pull/23132)
  - [x] Docker JDK bundling (x86 #11845)
- [x] Produce platform specific artifacts (aka. publish new images) #11350 
  - [x] Publish x86_64 JDK/no JDK artifacts . (https://github.com/elastic/infra/pull/23171)
  - [x] Publish AARCH64 JDK/no_jdk artifacts. (https://github.com/elastic/infra/pull/23568)
- [x] Documentation:
   - [x] Update documentation to reflect new artifacts that include bundled JDK.
   - [x] Add an upgrade guide from non-bundled to bundled logstash
   - [x] Add release notes notifying users about the upgrade path

Future Considerations
================
- [ ] Consider bundling Zulu for Windows/Azure based artifacts

**Comment by andsel** [comment]
All the tasks were completed and the features are out in `7.10`, so close it
