### ISSUE TITLE
[meta] Create Logstash UBI-8 based docker images

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#12173]
UBI-7 based docker images were previously added in #11335, and removed in #11489 

This issue will track the necessary work required to update the logstash docker image creation to allow the building of UBI-8 based images.

Tasks
====
- [x] Update Logstash docker makefiles, rake packages and associated acceptance tests to add support for UBI-8 based images #12181
- [x] Add Jenkins job to run ubi8 tests in the acceptance tests https://github.com/elastic/infra/pull/22630
- [x] Update the Release manager task https://github.com/elastic/infra/issues/22535
