### ISSUE TITLE
[Doc][Meta]Logstash 7.10 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12183]
**Doc changes:**
- [ ]  Rework security docs (WIP) #12225
  - [ ] TO DO: Expand content in new section
- [ ]  Datastreams
- [ ]  Cloud First work [#11530](https://github.com/elastic/logstash/issues/11530)
  - [ ] Doc:Relocate logstash-to-cloud topic for increased visibility [#11884](https://github.com/elastic/logstash/pull/11884) - WIP
- [x]  Integration plugin docs infrastructure
  - [x] Add new header for Logstash Reference: [#11891](https://github.com/elastic/logstash/pull/11891) and [#12163](elastic/logstash#12163)
  - [x] Add new integration plugin header for Versioned Plugin Reference: [#891](elastic/logstash-docs#891)
  - [x] Implement for jdbc: [#40](https://github.com/logstash-plugins/logstash-integration-jdbc/pull/40)
  - [x] Implement for kafka: [#46](https://github.com/logstash-plugins/logstash-integration-kafka/pull/46)
  - [x] Implement for rabbitmq: [#34](https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/34)
- [ ] Fix links in response to Beats docs rework
  - [ ] https://github.com/logstash-plugins/logstash-input-log4j/pull/46
  - [x] https://github.com/elastic/logstash-docs/pull/918 for master with backports to 7.x, 7.9
  - [x] https://github.com/elastic/logstash-docs/pull/921 for 7.8 with backports to 7.0-7.7, 6.0-6.8, 5.3-5.6
- [ ]  PQ work
- [ ] Formalize process for listing external plugins
  - [ ] Doc:Update guidelines for contributing a plugin [#12192](https://github.com/elastic/logstash/pull/12192) - WIP
- [x] Doc:Clarify how Bulk API interacts with DLQ [#12209](https://github.com/elastic/logstash/pull/12209) - WIP
- [x] Doc:Add redirect from multiline filter to multiline codec [#12208](https://github.com/elastic/logstash/pull/12208)
- [x] Update ECS versions [#1950](https://github.com/elastic/docs/pull/1950)
- [x] Doc:Stdin input doesn't allow config reloading [#12191](https://github.com/elastic/logstash/pull/12191)
- [ ] Doc: Offline plugins
- [ ] TODO: Add issues from the Logstash 7.10 roadmap

**Recurring:**
- [ ] [Meta]Generate plugin docs #11269

**Plugins/Plugin quality:**
- [x] Doc:Add filter-wurfl to plugin list [#908](https://github.com/elastic/logstash-docs/pull/908)
- [x] [input-elasticsearch]Doc:Update sliced scroll link to resolve to new location [#135](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/135)
- [x] [logstash-filter-split]Doc:Add introductory statement to clarify purpose of plugin [#43](https://github.com/logstash-plugins/logstash-filter-split/pull/43) and [#907](https://github.com/elastic/logstash-docs/pull/907)
- [x] [logstash-kafka-integration]Doc:Add attribute for kafka client versions [#48](https://github.com/logstash-plugins/logstash-integration-kafka/pull/48)

**Release notes:**
- [ ] [Featured items](https://docs.google.com/document/d/1PlwjeYgPqgZ1jDYFTgMhWn9lstFBO9BqXLArsVtCEQc/edit)
- [ ] PR: TBD

**Process Improvements**
- [ ] Issue: Plugin docgen with no changes shouldn't be considered a `FAILURE` [#43](https://github.com/elastic/docs-tools/issues/43)
- [x] Issue: Restrict Versioned Plugin Ref doc builds to machines equipped with the right set up #22748
     Fix: [logstash-ci] Run periodic Logstash Version Plugin doc build with newer Docker #23030

**Ongoing/Other:**

- [ ]  Hardening Guide #11531 (TBD)
- [ ]  Doc rebuild initiative workgroup
- [ ] Cloud workgroup
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)
