### ISSUE TITLE
[Meta] Support JDK 15

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12243]
> JDK 15, the reference implementation of Java 15, is now Generally
> Available.  We’ve identified no P1 bugs since we promoted build 36
> over five weeks ago so that’s the official GA release, ready for
> production use.
> 
> GPL-licensed OpenJDK builds from Oracle are available here:
> 
>   https://jdk.java.net/15
> 
> Builds from other implementors will no doubt be available soon.
> 
> This release includes fourteen features [1]:
> 
>   339: Edwards-Curve Digital Signature Algorithm (EdDSA)
>   360: Sealed Classes (Preview)
>   371: Hidden Classes
>   372: Remove the Nashorn JavaScript Engine
>   373: Reimplement the Legacy DatagramSocket API
>   374: Disable and Deprecate Biased Locking
>   375: Pattern Matching for instanceof (Second Preview)
>   377: ZGC: A Scalable Low-Latency Garbage Collector
>   378: Text Blocks
>   379: Shenandoah: A Low-Pause-Time Garbage Collector
>   381: Remove the Solaris and SPARC Ports
>   383: Foreign-Memory Access API (Second Incubator)
>   384: Records (Second Preview)
>   385: Deprecate RMI Activation for Removal

https://mail.openjdk.java.net/pipermail/announce/2020-September/000291.html

Likely sources of test failures:

> 372: Remove the Nashorn JavaScript Engine

----

JDK15 introduces some changes that make Logstash to be adapted to run on this version of the JDK. 
After Nashorn JavaScript engine was deprecated since JDK 11, with version 15 it has been completely removed, [JEP 372](https://openjdk.java.net/jeps/372); this means that Logstash has to move away from using it, and it's used 2 parts:
- scripting rules in log4j configuration to separate logs per pipeline
- the ingest migration tool
Other than that with JDK 15 the CMS settings returns error, instead of warning as in JDK 14 [JEP 363](https://openjdk.java.net/jeps/363):

JDK 14 output:
```
Using JAVA_HOME defined java: /home/logstash/.sdkman/candidates/java/14.0.1.hs-adpt
OpenJDK 64-Bit Server VM warning: Ignoring option UseConcMarkSweepGC; support was removed in 14.0
OpenJDK 64-Bit Server VM warning: Ignoring option CMSInitiatingOccupancyFraction; support was removed in 14.0
OpenJDK 64-Bit Server VM warning: Ignoring option UseCMSInitiatingOccupancyOnly; support was removed in 14.0
Resolving dependencies...................................................
Sending Logstash logs to /tmp/logstash/logs which is now configured via log4j2.properties
[2020-12-16T09:30:49,011][INFO ][logstash.runner          ] Starting Logstash 
```

JDK 15 output:
```
Using JAVA_HOME defined java: /home/logstash/.sdkman/candidates/java/15.0.1.hs-adpt
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
This means that in short term we should describe how to run Logstash on JDK 15, but in long term a discussion on GC selection should be open.

To unlock Logstash on JDK 15 we have to remove the blocks imposed by JEP 372, adapt CI scripts to test on JDK 15, document how to switch to JDK 15

This issue tracks all the changes needed to make Logstash running on JDK15

**Task list**
- [x] replace the log router and filter that leveraged Javascript code with a pure Java customization PR #12512
  - [x] in backport PR to `7.x` #12591 which simply "warn & continue" instead of "error & stop"
- [x] rewrite the ingest pipeline migration tool, actually is implemented in Javascript and uses Nashorn to run, PR #12524 for `master` PR #12532 for`7.x`
- [x] introduce "conditional settings" in `jvm.options` to bind specific flags to specific JVM versions, in this case CMS GC (concurrent mark and sweep) is binded to  version between 8 and 14, PR `master`: #12530, PR `7.x`: #12593
- [x] run the build with openJDK15 #12537
- [x] update CI to use JDK15 https://github.com/elastic/infra/pull/25638
- [x] describe how to upgrade an existing installation #12614
- [x] update support matrix in documentation

**Comment by roaksoax** [comment]
Closing this meta-issue as we now fully support JDK15
