### ISSUE TITLE
[Meta] Logstash use system indices API 

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#12291]
Elasticsearch introduced the System Indices and Hidden Indices concepts to replace indices that start with a dot, eg .logstash. These dot indices are an implementation detail that users should not interact with. Logstash centralized pipeline management uses .logstash to store pipeline information. It needed to migrate to the new System Indices API. (upstream: https://github.com/elastic/elasticsearch/issues/50251)

### **Expected Tasks**
- [ ] Logstash
  - [ ] Implement new endpoint
  - [ ] Add integration test with multiple ES versions (7.9 and master) 
- [ ] Kibana
  - [ ] Investigate permission handling
  - [ ] Investigate unmapped legacy API
  - [ ] Implement new endpoint
  - [ ] Add integration test with multiple ES versions (7.9 and master)
### **Future Tasks**
After legacy API is deprecated
- [ ] clean up Logstash legacy API
- [ ] clean up Kibana legacy API
