### ISSUE TITLE
[Meta] Support wildcards in xpack.management.pipeline.id

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#12366]
Logstash allows xpack licensees to manage pipelines through centralized pipelines management in Kibana. However, whenever users add a new pipeline in Kibana, they need to update “logstash.yml” with the new pipeline id and restart Logstash to make it live. Therefore, a wildcard concept is introduced to match multiple ids (ref: https://github.com/elastic/logstash/issues/10558)

This feature targets version 7.11

## **Example Configuration**
```xpack.management.pipeline.id: ["*"]```
Logstash fetches all pipelines periodically. If pipelines are updated/ deleted or new pipelines are added, Logstash can pick up all the changes

```xpack.management.pipeline.id: ["host*_pipeline*", "awesome_pipeline"]```
This can match host1_pipeline1, host2_pipeline1 and awesome_pipeline

## **Expected Tasks**
- [x] Support pattern matching in the configuration file (https://github.com/elastic/logstash/pull/12370)
 - Use system indices API to fetch all pipelines
 - Take pipelines by pattern matching
 - Add unsupport message if version <= 7.10
- [x] Add test cases for pattern matching (https://github.com/elastic/logstash/pull/12370)
- [x] Documentation https://github.com/elastic/logstash/pull/12396
