### ISSUE TITLE
[Doc][Meta]Logstash 7.11 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12446]
#### Doc changes:
- [ ]  Rework security docs (WIP) #12225
  - [ ] TO DO: Expand content in new section
- [ ]  Datastreams
- [ ]  Cloud First work [#11530](https://github.com/elastic/logstash/issues/11530)
- [ ]  PQ work
- [ ] Formalize process for listing external plugins
  - [ ] Doc:Update guidelines for contributing a plugin [#12192](https://github.com/elastic/logstash/pull/12192) - WIP
- [ ] Doc: Offline plugins
- [ ] TODO: Add issues from the Logstash 7.10 roadmap

#### Recurring:
- [ ] [Meta]Generate plugin docs #11269

#### Plugins/Plugin quality:
- [ ] Make plugin docs more resilient for new releases (`current` cutover)
- [ ] Fix links in response to Beats docs rework
  - [ ] https://github.com/logstash-plugins/logstash-input-log4j/pull/46

#### Release notes:
- [ ] Featured items
- [ ] PR: TBD

#### Process Improvements
- [ ] Issue: Plugin docgen with no changes shouldn't be considered a `FAILURE` [#43](https://github.com/elastic/docs-tools/issues/43)

#### Ongoing/Other:
- [ ]  Hardening Guide #11531 (TBD)
- [ ]  Doc rebuild initiative workgroup
- [ ]  Cloud workgroup
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)

**Comment by karenzone** [comment]
Duplicate
