### ISSUE TITLE
[Meta] Support for darwin-aarch64 MacOS Devices

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#12461]
This issue relates to Logstash support for the new M1 MacOS devices, in terms of the developer experience building and testing Logstash core and plugins on these devices, and actually running Logstash on these devices. 

- [x] Investigate developer experience for building and testing Logstash on M1 MacOS devices.
   - [x] Building Logstash on M1 devices.
- [x] Investigate experience running regular MacOS builds on M1 MacOS devices. 
- [x] Build darwin-aarch64 Logstash images. #13426

**Comment by droberts195** [comment]
I guess this is superseded by https://github.com/elastic/logstash/issues/13426 now?

**Comment by robbavey** [comment]
@droberts195 #13426 is the last part of this meta issue, but is probably what you want to be linking to in the stack wide dev issue

**Comment by roaksoax** [comment]
Closing this issue as all the work is now complete.
