### ISSUE TITLE
[Doc][Meta]Generate and merge plugin docs

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12551]
## Generate and merge plugin docs
Continued from #11269

**2021-December**
- [ ] main : 
  - [x] https://github.com/elastic/logstash-docs/pull/1247
     - [x] https://github.com/elastic/logstash-docs/pull/1255
  - [x] https://github.com/elastic/logstash-docs/pull/1238
  - [x] https://github.com/elastic/logstash-docs/pull/1234
  - [x] https://github.com/elastic/logstash-docs/pull/1223
- [ ] 8.0: 
  - [x] https://github.com/elastic/logstash-docs/pull/1246
     - [x] https://github.com/elastic/logstash-docs/pull/1254
  - [x] https://github.com/elastic/logstash-docs/pull/1233
  - [x] https://github.com/elastic/logstash-docs/pull/1224
- [ ] 7.17: 
  - [x] https://github.com/elastic/logstash-docs/pull/1251
       - [x] https://github.com/elastic/logstash-docs/pull/1253
- [ ] 7.16: 
  - [x] https://github.com/elastic/logstash-docs/pull/1245
       - [x] https://github.com/elastic/logstash-docs/pull/1250
  - [x] https://github.com/elastic/logstash-docs/pull/1237
  - [x] https://github.com/elastic/logstash-docs/pull/1232
  - [x] https://github.com/elastic/logstash-docs/pull/1225
- [ ] 7.15: 
  - [x] https://github.com/elastic/logstash-docs/pull/1231
  - [x] https://github.com/elastic/logstash-docs/pull/1226
- [ ] 6.8: 
  - [x] https://github.com/elastic/logstash-docs/pull/1244

**2021-November**
- [ ] main (formerly `master`): 
  - [x] https://github.com/elastic/logstash-docs/pull/1210
       - [x] https://github.com/elastic/logstash-docs/pull/1212
  - [x] https://github.com/elastic/logstash-docs/pull/1203
- [ ] 8.0: 
  - [x] https://github.com/elastic/logstash-docs/pull/1208
       - [x] https://github.com/elastic/logstash-docs/pull/1211
  - [x] https://github.com/elastic/logstash-docs/pull/1202 
- [ ] 7.16: 
  - [x] https://github.com/elastic/logstash-docs/pull/1201
- [ ] 7.15: 
  - [x] https://github.com/elastic/logstash-docs/pull/1200

**2021-October**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1181
     - [x] https://github.com/elastic/logstash-docs/pull/1187
  - [x] https://github.com/elastic/logstash-docs/pull/1172
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1183
     - [ ] https://github.com/elastic/logstash-docs/pull/1188
  - [x] https://github.com/elastic/logstash-docs/pull/1173
- [ ] 7.15: 
  - [ ] No updates
- [ ] 6.8: 
  - [x] https://github.com/elastic/logstash-docs/pull/1185

**2021-September**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1167
  - [x] https://github.com/elastic/logstash-docs/pull/1157
  - [x] https://github.com/elastic/logstash-docs/pull/1144
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1168
   - [x] https://github.com/elastic/logstash-docs/pull/1156
  - [x] https://github.com/elastic/logstash-docs/pull/1143
- [ ] 7.15: 
  - [x] https://github.com/elastic/logstash-docs/pull/1169
- [ ] 7.14: 
  - [x] https://github.com/elastic/logstash-docs/pull/1158

**2021-August**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1144
  - [x] https://github.com/elastic/logstash-docs/pull/1135
  - [x] https://github.com/elastic/logstash-docs/pull/1130
  - [x] https://github.com/elastic/logstash-docs/pull/1124
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1143
  - [x] https://github.com/elastic/logstash-docs/pull/1136
  - [x] https://github.com/elastic/logstash-docs/pull/1131
  - [x] https://github.com/elastic/logstash-docs/pull/1125
- [ ] 7.15: 
  - [x] https://github.com/elastic/logstash-docs/pull/1137
- [ ] 7.14: 
  - [ ] https://github.com/elastic/logstash-docs/pull/1142
  - [x] https://github.com/elastic/logstash-docs/pull/1126
- [ ] 7.13: 
  - [ ] 
- [ ] 6.8:  
  - [ ] 

**2021-July**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1105
  - [x] https://github.com/elastic/logstash-docs/pull/1100
  - [x] https://github.com/elastic/logstash-docs/pull/1096
  - [x] https://github.com/elastic/logstash-docs/pull/1090
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1106
  - [x] https://github.com/elastic/logstash-docs/pull/1101
  - [x] https://github.com/elastic/logstash-docs/pull/1097
  - [x] https://github.com/elastic/logstash-docs/pull/1091
- [ ] 7.14: 
  - [x] https://github.com/elastic/logstash-docs/pull/1111
  - [x] https://github.com/elastic/logstash-docs/pull/1092
- [ ] 7.13: 
  - [ ] 
- [ ] 6.8:  
  - [ ] 

**2021-June**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1072
  - [x] https://github.com/elastic/logstash-docs/pull/1067
  - [x] https://github.com/elastic/logstash-docs/pull/1049
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1071
  - [x] https://github.com/elastic/logstash-docs/pull/1066
  - [x] https://github.com/elastic/logstash-docs/pull/1056
  - [x] https://github.com/elastic/logstash-docs/pull/1050
- [ ] 7.13: 
  - [x] https://github.com/elastic/logstash-docs/pull/1084
  - [x] https://github.com/elastic/logstash-docs/pull/1058
  - [x] https://github.com/elastic/logstash-docs/pull/1051
- [ ] 6.8:  
  - [ ] https://github.com/elastic/logstash-docs/pull/1085

**2021-May**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1036
  - [x] https://github.com/elastic/logstash-docs/pull/1032
  - [x] https://github.com/elastic/logstash-docs/pull/1026
  - [x] https://github.com/elastic/logstash-docs/pull/1025
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1034
  - [x] https://github.com/elastic/logstash-docs/pull/1027
- [ ] 7.13: 
  - [x] https://github.com/elastic/logstash-docs/pull/1035
  - [x] https://github.com/elastic/logstash-docs/pull/1028
- [ ] 7.12: 
  - [ ] No changes
- [ ] 6.8:  
  - [ ] No changes

**2021-April**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1024
  - [x] https://github.com/elastic/logstash-docs/pull/1019
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1023
  - [x] https://github.com/elastic/logstash-docs/pull/1017
- [ ] 7.13: 
  - [x] https://github.com/elastic/logstash-docs/pull/1022
- [ ] 7.12: 
  - [x] https://github.com/elastic/logstash-docs/pull/1015
- [ ] 6.8:  
  - [ ] No changes

**2021-March**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/1014
  - [x] https://github.com/elastic/logstash-docs/pull/1010
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/1013
  - [x] https://github.com/elastic/logstash-docs/pull/1007
  - [x] https://github.com/elastic/logstash-docs/pull/1004
  - [x] https://github.com/elastic/logstash-docs/pull/1000
- [ ] 7.12: 
  - [x] https://github.com/elastic/logstash-docs/pull/1003
- [ ] 7.11: 
   - [x] https://github.com/elastic/logstash-docs/pull/999
- [ ] 6.8:  
  - [x] No changes

**2021-February**
- [ ] master: 
  - [x] https://github.com/elastic/logstash-docs/pull/992
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/991
- [ ] 7.12: 
   - [x] https://github.com/elastic/logstash-docs/pull/988
- [ ] 7.11: 
   - [x] https://github.com/elastic/logstash-docs/pull/994
- [ ]  7.10:
   - [x] https://github.com/elastic/logstash-docs/pull/990
- [ ] 6.8:  
  - [x] https://github.com/elastic/logstash-docs/pull/993

**2021-January**
- [ ] master:   
  - [x] https://github.com/elastic/logstash-docs/pull/982
- [ ] 7.x: 
  - [x] https://github.com/elastic/logstash-docs/pull/981
- [ ] 7.11: 
   - [x]  https://github.com/elastic/logstash-docs/pull/979
   - [x]  https://github.com/elastic/logstash-docs/pull/977
- [ ]  7.10:
   - [x]  https://github.com/elastic/logstash-docs/pull/980
   - [x]  https://github.com/elastic/logstash-docs/pull/978
- [ ] 6.8:  
  - [x] https://github.com/elastic/logstash-docs/pull/983

**Comment by karenzone** [comment]
Continued in #13585 for 2022
