### ISSUE TITLE
[META] GeoIP filter download service for MaxMind license change

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#12560]
Late last year, MaxMind changed from releasing the database under a CC license to a proprietary EULA, as part of their work to comply with GDPR and CCPA. The EULA requires us to update the MaxMind database for our users within 30 days of MaxMind updating their database.

The Stack infrastructure team hosts a new endpoint for Elasticsearch and Logstash to get the latest database. Logstash needs to download the latest database and use it to resolve GeoIP on the fly.

## **Design**
geoip-filter will be removed from OSS and join the Basic license. The plugin ships with CC license database as a default database. In online mode, Logstash checks for newer database versions every day. It downloads the update and picks up on-the-fly. For any reason, Logstash fails to access infra's API for 30 days, Logstash should shut down the pipeline in order to be compliant. In offline mode, users are on their own to manage an update to date database

## **Expected Tasks**
~~- [x] Implement database update and checking in logstash-filter-geoip https://github.com/logstash-plugins/logstash-filter-geoip/pull/172~~

#### Logstash
- [x] Implement pipeline shutdown in Logstash https://github.com/elastic/logstash/pull/12582
- [x] Implement database update and checking in xpack https://github.com/elastic/logstash/pull/12675
  - [x] Fix the broken xpack unit test https://github.com/elastic/logstash/pull/12715
- [x] clean up database https://github.com/elastic/logstash/pull/12689
- [x] change infra endpoint https://github.com/elastic/logstash/pull/12727
- [ ] add LICENSE.txt and COPYRIGHT.txt 
- [ ] Documentation https://github.com/logstash-plugins/logstash-filter-geoip/pull/177
- [ ] backport logstash
#### Plugin
- [x] Fix the broken gradle script https://github.com/logstash-plugins/logstash-filter-geoip/pull/175
- [x] Ship plugin with CC license database https://github.com/logstash-plugins/logstash-filter-geoip/pull/175
- [x] Implement loading xpack database manager in logstash-filter-geoip https://github.com/logstash-plugins/logstash-filter-geoip/pull/176

**Comment by mbarretta** [comment]
Offline (air-gapped) users need to be considered here as well: how would a user configure Logstash to use a local copy of the DB?
