### ISSUE TITLE
[Doc][Meta]Logstash 7.11 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12604]
Our team is responsible for the 7.11 docs release. This release plan is lighter than usual to allow time to manage and complete those additional duties. 

### Doc changes
- [x]  Datastreams
- [x] [Adding Elastic Contributor Program to the logstash "Contributing" page #12431](https://github.com/elastic/logstash/issues/12431)
  - [x] [Doc: Add info on contributor program #12543](https://github.com/elastic/logstash/pull/12543)
- [ ]  Rework security docs (WIP) #12225
  - [ ] TO DO: Rework to distinguish between securing and communicating securely
- [ ]  PQ work
- [ ] Formalize process for listing external plugins
  - [ ] Doc:Update guidelines for contributing a plugin [#12192](https://github.com/elastic/logstash/pull/12192) - WIP
- [ ] Doc: Offline plugins

#### Plugins/Plugin quality
- [x] [[Doc] Update plugin docs to minimize broken cross-doc links at version change #12606](https://github.com/elastic/logstash/issues/12606)
  - [x] [logstash-input-beats] [Doc: Replace cross doc links with attributes #403](https://github.com/logstash-plugins/logstash-input-beats/pull/403) 
  - [x] [logstash-input-elasticsearch] [Doc: Replace cross doc links with attributes #143](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/143)
  - [x] [logstash-input-log4j] [Doc: Replace cross-doc links with attributes #47](https://github.com/logstash-plugins/logstash-input-log4j/pull/47)
  - [x] [logstash-filter-elasticsearch] [Doc: Replace cross doc links with attributes #144](https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/144)
  - [x] [logstash-output-elasticsearch] [Doc:Replace cross doc links with attributes #985](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/985)
  - [x] [logstash-output-google_bigquery] [Doc: Replace cross-document links with attributes #61](https://github.com/logstash-plugins/logstash-output-google_bigquery/pull/61)
  - [x] [logstash-output-s3] [Doc: Replace cross doc links with attributes #230](https://github.com/logstash-plugins/logstash-output-s3/pull/230) 

#### Release notes
- [ ] [Featured items](https://docs.google.com/document/d/1PlwjeYgPqgZ1jDYFTgMhWn9lstFBO9BqXLArsVtCEQc/edit)
- [ ] PR: https://github.com/elastic/logstash/pull/12596

#### Recurring
- [x] [Meta]Generate plugin docs #12551

### Process Improvements 
- [ ] Issue: Plugin docgen with no changes shouldn't be considered a `FAILURE` [#43](https://github.com/elastic/docs-tools/issues/43)
- [ ] Issue: "Destination wins" strategy - TODO: Check for open issue. If there's not one, open it. 
- [ ] Release notes automation and process improvements

### Ongoing/Other
- [ ] Doc rebuild initiative workgroup
- [ ] Content workgroup
- [ ] Cloud workgroup
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)

**Comment by karenzone** [comment]
Replaces #12446
