### ISSUE TITLE
[Doc][Meta]Logstash 7.12 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12605]
### Doc changes
- [ ]  Rework security docs (WIP) #12225
  - [ ] TO DO: Rework to distinguish between securing and communicating securely
- [ ]  Datastreams
- [ ]  Cloud First work [#11530](https://github.com/elastic/logstash/issues/11530)
  - [ ] Doc:Relocate logstash-to-cloud topic for increased visibility [#11884](https://github.com/elastic/logstash/pull/11884) - WIP
- [ ]  PQ work
- [ ] Formalize process for listing external plugins
  - [ ] Doc:Update guidelines for contributing a plugin [#12192](https://github.com/elastic/logstash/pull/12192) - WIP
- [ ] Doc: Offline plugins
- [ ] TODO: Add issues from the Logstash 7.10 roadmap

#### Plugins/Plugin quality
- [ ] TBD

#### Release notes
- [ ] [Featured items](https://docs.google.com/document/d/1PlwjeYgPqgZ1jDYFTgMhWn9lstFBO9BqXLArsVtCEQc/edit)
- [ ] PR: TBD

#### Recurring
- [ ] [Meta]Generate plugin docs #12551

### Process Improvements 
- [ ] Issue: Plugin docgen with no changes shouldn't be considered a `FAILURE` [#43](https://github.com/elastic/docs-tools/issues/43)
- [ ] Issue: "Destination wins" strategy - TODO: Check for open issue. If there's not one, open it. 

### Ongoing/Other
- [ ] Doc rebuild initiative workgroup
- [ ] Content workgroup
- [ ] Cloud workgroup
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)
