### ISSUE TITLE
[Meta] Support JDK16/17

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#12607]
JDK 16 is actually in "early-access" but is expected to be GA on 2021/03/16 https://openjdk.java.net/projects/jdk/16/
It brings:
- JEP 390: deprecates native types wrapper constructors, so no more `new Long(n)`. Logstash doesn't use these but JRuby seems to use it https://github.com/jruby/jruby/blob/48208dcb1e750013869c6f627350d4a420201adb/core/src/main/java/org/jruby/parser/RubyParser.java#L3864 and I'm not able to view if this could impact Logstash
- JEP 386: Alpine Linux support, since the Alpine uses another libc we should try to run against it
- JEP 396: Strongly Encapsulate JDK Internals by Default, we could crash against modules, not directly but for some libraries Logstash use.
-  JEP 388: Windows/AArch64 Port, this probably worth an eye

According to JEPs list in JDK 17 https://openjdk.java.net/projects/jdk/17/ we could crash against:
- JEP 411 [Deprecate the Security Manager for Removal](https://openjdk.java.net/jeps/411) this means `java.security.AccessController` usage has to be reworked
- JEP 403 [Strongly Encapsulate JDK Internals](https://openjdk.java.net/jeps/403) internal classes like `sun.misc.Unsafe` are not anymore usable, which could  maybe lead us to update some dependencies.

**JDK 16 Task list**
- [x] run the build with openJDK16 #13202
- [x] update CI to use JDK16 https://github.com/elastic/infra/pull/31324
- [x] run Logstash package with JDK 16 on Alpine Linux
   - use `Dockerfile.alpine` https://gist.github.com/andsel/38972519c366a673f7d4487e7eaa2695
   - clone the #13203 branch `https://github.com/andsel/logstash/tree/fix/jdk16_adaptations`
   - bring the `Dockerfile.alpine` into the local clone
   - build the image `docker build -t logstash_alpine . -f Dockerfile.alpine`
   - build the packages `rake artifact:archives`
   - run a shell in the image mounting the `build/` folder with ```docker run --rm -it -v `pwd`/build:/opt/logstash/build logstash_alpine sh```
   - unpack the previously created Logstash tar.gz package: in the image shell run `cd /opt/logstash/build/` and `tar zxf logstash-8.0.0-SNAPSHOT-no-jdk.tar.gz`
   - run logstash `sh bin/logstash -e "input {stdin{}} output{stdout{codec => rubydebug}}"`
- [ ] ~~fixes for the build~~  #13203
- [ ] ~~verify mostly used plugins works with JDK 16~~

**JDK 17 Task list**
 - [x] run the build with openJDK17 https://github.com/elastic/logstash/pull/13307
 - [x] update CI to use JDK 17 https://github.com/elastic/infra/pull/32212
 - [x] run LS with JDK 17 on Alpine Linux
   - verified using https://gist.github.com/robbavey/ad4cdf044ab8237a9bc4f23883f86e50 
 - [x] remove usage of Security Manager #13306
 - [x] eventually update any dependency that still use the removed `sun.misc.Unsafe` class
 - [ ] ~~bundle AdomptiumOpenJDK 17 into `8.0`~~ PR https://github.com/elastic/logstash/pull/13343
 - [x] verify tier1 and tier2 plugins works with JDK 17
 - [ ] ~~configure G1GC flags appropriately for JDK 17 (the default GC of the JVM)~~ #13378
 - [x] update plugins Gradle wrapper version to a JDK 17 compatible (Gradle >= 7)
   - [x] Azure EventHub input https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/69
   - [x] Beats input https://github.com/logstash-plugins/logstash-input-beats/pull/432
   - [x] File input https://github.com/logstash-plugins/logstash-input-file/pull/305
   - [x] Http Input https://github.com/logstash-plugins/logstash-input-http/pull/145
   - [x] Kafka integration (input and output) https://github.com/logstash-plugins/logstash-integration-kafka/pull/104
   - [x] TCP input https://github.com/logstash-plugins/logstash-input-tcp/pull/184
   - [x] Date filter https://github.com/logstash-plugins/logstash-filter-date/pull/140
   - [x] Geoip filter https://github.com/logstash-plugins/logstash-filter-geoip/pull/191
   - [x] User agent filter https://github.com/logstash-plugins/logstash-filter-useragent/pull/75
   - [x] SNMP input (Tier 2) https://github.com/logstash-plugins/logstash-input-snmp/pull/102
   - [x] Dissect filter https://github.com/logstash-plugins/logstash-filter-dissect/pull/78

**Comment by roaksoax** [comment]
As JDK 17 is now supported, we are closing this issue. Please note that JDK17 is not yet the default on 8.0, and we will re-evaluate for 8.x+.
