### ISSUE TITLE
[Meta ] Use LS_JAVA_HOME in favor of JAVA_HOME

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#12725]
Logstash launch shell scripts uses the `JAVA_HOME` to identify a JDK configured by the user, that environment variable could be too generic and Logstash should have a dedicated `LS_JAVA_HOME`.
This issue tracks the task to do in order to manage this transition.
- [x] modify launch scripts (bash and cmd) to use `LS_JAVA_HOME` giving precedence on this over the standard `JAVA_HOME` #13204
- [x] deprecate the `JAVA_HOME` on `7.x` (but allow it to be used) #13207
- [x] backport the above PRs to `7.x` (#13207 and #13204) #13213
- [x] remove completely the `JAVA_HOME` variable from scripts for version `8.0` #13214

**Comment by andsel** [comment]
Elasticsearch done a similar transition in https://github.com/elastic/elasticsearch/pull/69149

**Comment by andsel** [comment]
Close because all the PRs landed.
