### ISSUE TITLE
[Meta] Benchmark-cli improvements

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#12785]
While testing changes made to [add functionality](#12437) to the benchmark cli tool, there are some issues with the current state of the tool, and it will require some work to bring it up to full usefulness. This meta issue is intended to capture the work required to bring this tool into a more usable state..

- [ ] Benchmark CLI does not download releases after JDK was bundled #12774 
- [ ] Benchmark CLI should pass unit/integration tests
- [ ] CI should be enabled for Benchmark CLI
