### ISSUE TITLE
[Meta] Add plugin aliasing feature

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#12793]
## Overview

This issue describe the concept of aliased plugin. The feature is contained in Logstash and doesn't require any change
to the existing plugins' codebase. The core concept is that an aliased plugin can be used in Logstash's pipelines
configuration as it's a real plugin with its configuration name, but hinerit all the behaviour and configuration 
options from the original plugin.

## Definition and usage

The definition of an alias resides in Logstash core, and maps an alias name to real Logstash plugin name. It respect
the original type so that it's just a rename and not a redefinition of behavior. So if a plugin was an input plugin,
then also the alises one will be.

An aliased plugin should never conflicts with a real plugin, this means that in case a real plugin with the same name of the alias
exists then the real plugin takes precedence in every duty, from plugin instantiation during pipeline creation, to the plugin manager
utility used to manage Logstash plugins.
This is important because let us to create a real plugin from analiased and make it progress it's evolution in independent way.

This kind of approach let us to define the alias `elastic_agent` for `beats` input so that the following configuration is
handled as a `beats` configuration with same settings and behavior:

```ruby
input {
  elastic_agent {
  #beats {
    port => 5044
  }
}
```

## Plugin management

Regarding the plugin management aspects, an alias could be installed removed and should be explicit in list which plugin has an alias.

### Installation
The installation of alias is available only for rubygems, this means that an alias is usable only for published plugins, 
the local FS gems can't be istalled by alias. 
The installation checks if a real plugin corresponding to the alias exists, in afferamative case it proceed as ususal installing the gem. 
If it doesn't exists and name of the alias is resolved to real plugin, then that original plugin is installed.

### Removal
If the alias name is the one of a real plugin then the removal happens like the removal of any gem, without alias resolution.
If the alias is resolved to the name of an original plugin then a message is showed to the user asking him to remove the original. 
This behavior is dictated by a conservative principle, if the user remove `input-elastic_agent` the end result of removing `input-beats`
could be surprising for him.

### Listing
The list of plugin should clearly show which plugins contains are aliased, however if a real plugin with same of the alias and an aliased plugin are both installed, then the alias shouldn't be showed near the original plugin, this could confuse the user see a double clashing definition of the same plugin in the listing.

## Limitations
- the logger of an alias plugin is not changed, so the logs appear with same logger name of the original
- during the installation of an alias, the console show that the gem installed is the one of the original plugin and not an "alias.gem"
- `--version` specifier can't be used to install an alias
----

- [x] refactor plugin registry/lookup code base to easily introduce aliasing feature, PR #12799
- [x] make an alias usable in configuration when the sourcing plugin is installed, PR #12796
- [x] adapt plugin management CLI tools to install/uninstall plugins by alias, PR #12821
- [ ] documentation alignment meta issue #12794
- [x] after FF 7.13 share a yaml definition of alias remapping, see issue #12831, PR #12841
- [x] fix documentation build tool to consider automatically the yaml alias definitions, to avoid manual intervention when docs are built
- [ ] fix the plugin manager to include aliases as list selectors (for example `bin/logstash-plugin list agent`, actually return empty)
- [x] fix a require on the yaml file during the execution of `rake artifacts:all`, PR #12962
- [x] fix debug log of stacktrace from Reflections when process the aliases yml files, bug: #12992 PR #12991
