### ISSUE TITLE
[Doc][Meta]Logstash 7.13 documentation roadmap

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12834]
### Docs for 7.12
- [ ] Data streams as default for output-elasticsearch
- [ ] GeoIP
- [ ] Elastic Agent 
    - [ ] Docs infrastructure changes to support aliased plugin
    - [ ] [Doc: Update Logstash Reference to include Elastic Agent #12833](https://github.com/elastic/logstash/issues/12833) 

#### Release notes
- [ ] [Featured items](https://docs.google.com/document/d/1cbTd5QbeqhqWoxvchlw65gDTA0mykhb_LoxU3W0oqxc/edit)
- [ ] PR: TBD

#### Recurring
- [x] [Meta]Generate plugin docs #12551

### Other docs work
- [ ]  Rework security docs (WIP) #12225
  - [ ] TO DO: Rework to distinguish between securing and communicating securely
- [ ]  Datastreams
- [ ]  Cloud First work [#11530](https://github.com/elastic/logstash/issues/11530)
  - [ ] Doc:Relocate logstash-to-cloud topic for increased visibility [#11884](https://github.com/elastic/logstash/pull/11884) - WIP
- [ ]  PQ work
- [ ] Formalize process for listing external plugins
  - [ ] Doc:Update guidelines for contributing a plugin [#12192](https://github.com/elastic/logstash/pull/12192) - WIP
- [ ] Doc: Offline plugins
- [ ] TODO: Add issues from the Logstash 7.10 roadmap

#### Plugins/Plugin quality
- [ ] TBD

### Process Improvements 
- [ ] Issue: Plugin docgen with no changes shouldn't be considered a `FAILURE` [#43](https://github.com/elastic/docs-tools/issues/43)
- [ ] Issue: "Destination wins" strategy 
- [ ] Skiplist

### Ongoing/Other
- [ ] Doc rebuild initiative workgroup
- [ ] Content workgroup
- [ ] Cloud workgroup/Logstash-Cloud project
- [ ]  Stack docs workgroup
- [ ]  GitHub backlog - make continuous improvement by catching up on GitHub issues and PR reviews (ONGOING)
