### ISSUE TITLE
Doc: Update Logstash Reference to include Elastic Agent

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#12833]
Selectively replace references and steps for Beats to Elastic Agent. 

Beats
- [ ]  TBD

Metricbeat
- [ ] Monitoring
- [ ] Azure module redirect

Filebeat
- [ ] TBD

###To Do:
- [ ] Consistently use shared attribute `{agent}`
- [ ] Figure out what to do with anchors that include references to beats
