### ISSUE TITLE
[META] unified (ECS) target support in plugins

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13018]
This is a sub-task of https://github.com/elastic/logstash/issues/11635

Some of the plugins do not pollute the default name-space explicitly, however they accept arbitrary user data (e.g. json).
Which means in terms of ECS compatibility they should use a `target` name-space to avoid ECS name collisions.

To handle such plugins we should warn the user with a generic message in `ecs_compatibility` mode.

- [x] a target check helper: https://github.com/logstash-plugins/logstash-mixin-ecs_compatibility_support/pull/6
- [x] logstash-filter-json https://github.com/logstash-plugins/logstash-filter-json/pull/49
- [x] logstash-filter-csv https://github.com/logstash-plugins/logstash-filter-csv/pull/86
- [x] logstash-filter-kv https://github.com/logstash-plugins/logstash-filter-kv/pull/96
- [x] logstash-codec-csv https://github.com/logstash-plugins/logstash-codec-csv/pull/7
- [x] logstash-codec-json (also needs event_factory_support)
- [x] logstash-codec-json_lines (also needs event_factory_support)
- [x] ~~logstash-codec-line~~
- [x] ~~logstash-codec-multiline~~
- [x] ~~logstash-codec-plain~~
- [x] logstash-codec-avro https://github.com/logstash-plugins/logstash-codec-avro/pull/36
---

*NOTE: target support (wout ECS) has been added to several Tier 2 codecs ...*
