### ISSUE TITLE
[META] event factory support

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13021]
Introduce a `new_event` (factory) interface for the (Ruby) plugin API.

The proposal is motivated by having a way of re-using `LogStash::Event.from_json` with `target => [namespace]` (e.g. in the JSON codec). We [benchmarked](https://gist.github.com/kares/03fee52a0618e4b94a8dc4fcdd52b68d#file-_results-out) the generic `LogStash::Json` parsing (which has JRuby parsing hooks) and found it noticeably slower compared to the Java native `Event.fromJson`.

A clean way forward would be to introduce a notion of an `EventFactory` with a `new_event` interface.

### Why is it important/What is the impact to the user?

It impacts plugin development which gets simpler as we'll provide a recommended way to create new events.
In the future we can leverage event factories to deprecate legacy event behavior and introduce better ECS defaults.

### Implementation

The scope is to introduce an `EventFactory` interface with a single method `EventFactory#new_event` and two implementations (perhaps `BasicEventFactory` and `TargetedEventFactory`), and to effectively add three methods to the API of `LogStash::Plugin`:

 - `Plugin#event_factory`: returns a _memoized_ `EventFactory` instance, that can be used to create events
 - `Plugin#targeted_event_factory`: returns a _memoized_ `EventFactory` that respects the plugin's `target` configuration.
   - if no `target` is provided, this effectively is equivalent to `Plugin#event_factory`.
   - if a `target` is provided, returns a `TargetedEventFactory` that wraps the return value of `Plugin#event_factory`.
 - `Plugin#create_event_factory`: returns a _new_ `EventFactory` based on the plugin's configuration and state. We may want to mark this as an "internal" or "advanced" API. 

### TO-DO

- [x] introduce `EventFactorySupport` with the outlined API in logstash-core https://github.com/elastic/logstash/pull/13017
- [x] provide an adapter mixin for plugins so they can depend on an API on older LS versions 
     https://github.com/logstash-plugins/logstash-mixin-event_support/pull/2
  * [x] the adapter gem should provide a way to use `Event.from_json` with an event factory implementation
- [x] leverage the gem in plugins (*json* and *json_lines* codec) to implement `target => ...` support

**Comment by kares** [comment]
initial event_factory support is now complete, we might still need to review (supported) plugins for actually using the factory.
this is tracked at: https://github.com/elastic/logstash/issues/13033 (most codecs will be reviewed as part of their ECS-ification)
