### ISSUE TITLE
[META] review plugins for event factory usage

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13033]
In https://github.com/elastic/logstash/issues/13021 we started providing plugins with event factory abstraction.
We are planning to leverage this work as part of LS' ECS efforts (all codecs will likely start using event factories).

Plugins should still be reviewed for `LogStash::Event.new` and potentially updated to use out adapter mixin:
- [x] **codecs** (part of the ECS effort - they should all be updated to use `event_factory`)
    - [x] *avro*
    - [x] *cef*
    - [x] *csv*
    - [x] *es_bulk*
    - [x] *json*
    - [x] *json_lines*
    - [x] *line*
    - [x] *multiline*?
    - [x] *plain*
    - [x] ~~*rubydebug*~~ only encodes
    - [x] *collectd*
    - [x] *edn*
    - [x] *edn_lines*
    - [x] *fluent*
    - [x] *graphite*
    - [x] *msgpack*
    - [x] *netflow*
- [x] *input jdbc*
- [x] *input elasticsearch*
- [x] *input beats*
- [x] *input http_poller*
- [x] *input heartbeat*
---
tier 2 inputs/filters
- [ ] *[input couchdb_changes](https://github.com/logstash-plugins/logstash-input-couchdb_changes/blob/master/lib/logstash/inputs/couchdb_changes.rb#L235)*
- [ ] *input gelf*
- [x] *input generator*
- [ ] *input graphite*
- [x] *input jms*
- [x] *input snmp*
- [x] *input snmptrap* (not tier 2 but semi-supported)
- [x] *input twitter*
- [x] ~~*input jmx*~~ not supported plugin
- [ ] *filter aggregate*
- [ ] *filter elapsed* (unsupported?)
