### ISSUE TITLE
[META] (full) ecs_compatibility implementation

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13109]
In https://github.com/elastic/logstash/issues/11635 we implemented `ecs_compatibility`, where necessary, for (supported) plugins. 

---

For codecs we often warn on a missing `target` and fill `event.original`, if possible, when `ecs_compatibility` is enabled.
This hasn't been implemented for Tier 2 codecs only Tier 1 (we still added `target` to most so users can manage ECS conflicts).
 - [ ] (Tier 2 Supported) Codecs
   - [ ] [EDN Codec](https://github.com/logstash-plugins/logstash-codec-end)
   - [ ] [EDN Lines Codec](https://github.com/logstash-plugins/logstash-codec-end_lines)
   - [ ] [Fluent Codec](https://github.com/logstash-plugins/logstash-codec-fluent)
   - [ ] [Graphite Codec](https://github.com/logstash-plugins/logstash-codec-graphite)
   - [ ] [MsgPack Codec](https://github.com/logstash-plugins/logstash-codec-msgpack)
   - [ ] [Netflow Codec](https://github.com/logstash-plugins/logstash-codec-netflow)
   - [ ] [Collectd Codec](https://github.com/logstash-plugins/logstash-codec-collectd)

---
Follow-up work after https://github.com/elastic/logstash/issues/11635
