### ISSUE TITLE
[Meta] Upgrade Gradle to version 7

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#13177]
Gradle 7 is the first Gradle version to be able to run on JDK 16+ and Logstash requires to keep ontrack with JDK vesions.

Gradle 7 introduced some checks on implicit tasks dependencies, so if a task produces some output that's consumed by some subsequent task without defining a dependency, the build will print warnings. 
With the close of JCenter, the `jcenter()` repository has been deprecated.

**Tasks**
- [x] Fix the problem with implicit task dependencies #13183
- [x] Switch from `Gradle-License-Report` plugin which is not yet compatible with Gradle 7 to a custom task to generate the CSV files needed by the report generator tool #13182
- [x] Remove `jcenter` and upgrade to Gradle 7 https://github.com/elastic/logstash/pull/13184
- [x] Backport to `7.x` #13212

Draft PR #13151 that the 3 steps above fixes the move to Gradle 7

**Comment by andsel** [comment]
Changes bakported to `7.x` to be released with next minor, `7.16`
