### ISSUE TITLE
[Meta] Add `user-agent` header to all Elasticserach plugins (input/filter/output)

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#13206]
Elasticsearch needs to know which is the agent it's sending data, for example it has to distinguish between Beats, Elasticsearch Agent or Logstash. In this context all Elasticsearch plugin needs to introduce a `user-agent` header, which contains the default value in the format:
```
logstash/<LS_version> (<OS, CPU arch, JVM details>) logstash-<plugin type>-<plugin name>/<plugin_version>
``` 

like for example :
```
logstash/7.14.1 (OS=Linux-5.4.0-84-generic-amd64; JVM=AdoptOpenJDK-11.0.11) logstash-output-elasticsearch/11.0.1
```

- [x] add the header to Elasticsearch Input PR https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/158
- [x] add the header to Elasticsearch Filter PR https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/152
- [x] add the header to Elasticsearch Output 
    - Issue: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1037
    - PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1038
    
----

Followup [issue](https://github.com/elastic/logstash/issues/13256) to share copied and pasted code between the three plugins.

**Comment by roaksoax** [comment]
@andsel as per the code review, the user agent should always be set and not be something that's configurable by the user. We should be setting to something like the following as a minimum:

Logstash/<version> (<plugin>/version)

Ideally, we should also be adding platform information/architecture/etc.

**Comment by andsel** [comment]
All three gems were published
