### ISSUE TITLE
[Meta] Drop support/Remove references to java `1.8`

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#13332]
We intend to drop support for Java `1.8` in Logstash `8.x` - java `1.8` is due to be "end of life-d" in early 2022, and we would prefer logstash users to use more modern versions of Java, in particular the version of Java that we bundle with Logstash, in order to provide the best, most tested experience.

This issue will contain sub issues related to removing support for Java 1.8 in Logstash `8.x`. 

- [x] Remove Java 8 from [ci matrix](https://github.com/elastic/logstash/blob/master/.ci/matrix-runtime-javas.yml) - #13344
- [x] Remove references to Java 8 from documentation #13350 
- [x] Remove Java 8 only settings from [jvm.options](https://github.com/elastic/logstash/blob/master/config/jvm.options) - #13349
 - [x] Add helpful error message on startup for Logstash `8.x` #13533
- [x] Update download page to state 'Java 11 or above' is required for Logstash `8.x`
- [x] Update support matrix to drop support for java 8 on Logstash `8.x`
- [x] Add deprecation notices for users running java 8 #13358 
- [x] Remove Java 8 specific [ByteBufferCleaner code] #13430
- [ ] Replace use of deprecated `finalize` method in [secret store] (https://github.com/elastic/logstash/blob/aa8305f1d4b942c8c3d036cc95d4496b57e6bb6d/logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java#L159) #14043
- [x] Update build workers to use Java 11 , https://github.com/elastic/infra/pull/32818, https://github.com/elastic/infra/pull/33275
- [x] Fix docker, unix and windows compatibility jobs to not use java 8 #13367, #13369
  - [x] https://github.com/elastic/infra/pull/33489

**Comment by robbavey** [comment]
Note that `download` page task marked as complete as page no longer mentions required versions of java as JDK is shipped with Logstash
