### ISSUE TITLE
[Meta] Publish Logstash artifacts for M1 Mac

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#13426]
This meta issue will capture the requirements to enable us to deliver a native M1 version of logstash and publish at the elastic.co download page along with the other released versions

- [x] Update version of bundled JDK to 17 https://github.com/elastic/logstash/pull/13343
  - Current version of bundled JDK does not come with an `aarch64` mac download, we will need to update to jdk17 if we want to use adoptium across the board.
- [x] Update artifacts to build darwin artifacts for `aarch64` https://github.com/elastic/logstash/pull/13425
- [x] Fix issues that arise during testing
- [x] Add darwin artifacts to release manager https://github.com/elastic/infra/pull/36804
- [x] Update download pages to include darwin artifacts.

Issues discovered during testing
- [x] #13428 
- [x] https://github.com/logstash-plugins/logstash-input-file/issues/306
- [x] https://github.com/elastic/logstash/issues/13463
- [x] `stat` shows incorrect results - https://github.com/jnr/jnr-posix/pull/173

**Comment by roaksoax** [comment]
This will now be available starting LS 8.4
