### ISSUE TITLE
[Doc][Meta] Logstash doc flight plan 

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#13420]
#### Strategic
- [ ] Use attributes for ECS messaging
- [ ] Security on by default
- [ ] Stack monitoring for Logstash
- [ ] Breaking changes 8.0 (add security on by default) 

#### Issues and enhancements
- [ ] #13415 
- [ ] #13419 
- [ ] #13257
- [ ] #13090

#### Issues and enhancements (plugins)
- [ ] https://github.com/logstash-plugins/logstash-input-snmp/issues/103

#### PRs in progress
- [ ] PQ-v2
- [ ] Security

#### Pending review
- [ ] #13084

#### Ongoing
- [ ] #12551
