### ISSUE TITLE
Doc: Create and apply attributes for ECS default messaging

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#13464]
We need a way to consistently message ECS default status across plugins. By carefully crafting and applying a shared attribute, we can ensure that the messaging is consistent across plugins. This approach also ensures that the text doesn't diverge over time from plugin to plugin. 

#### Set up framework
- [ ] Create shared attribute files for use in plugin docs. Set up `:include:` statements to make attributes available. 
    - [ ] LSR: 
    - [ ] VPR: 
- [ ] Refine messaging for ecs_compatibility defaults
    - [ ] LSR: 
    - [ ] VPR: 
- [ ] Test. Test. Test.
    - [ ] LSR: 
    - [ ] VPR:

#### Next steps
- [ ] Apply attribute to plugin doc source files, bump versions, and publish.
