### ISSUE TITLE
Update log4j dependency on Logstash to 2.17.0

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#13532]
- [x] [logstash-filter-date](https://github.com/logstash-plugins/logstash-filter-date): https://github.com/logstash-plugins/logstash-filter-date/pull/144
- [x] [logstash-filter-dissect](https://github.com/logstash-plugins/logstash-filter-dissect): https://github.com/logstash-plugins/logstash-filter-dissect/pull/81
- [x] [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip): https://github.com/logstash-plugins/logstash-filter-geoip/pull/198
- [x] [logstash-input-azure_event_hubs](https://github.com/logstash-plugins/logstash-input-azure_event_hubs): https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/72
- [x] [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats): https://github.com/logstash-plugins/logstash-input-beats/pull/439
- [x] [logstash-input-dead_letter_queue](https://github.com/logstash-plugins/logstash-input-dead_letter_queue):  https://github.com/logstash-plugins/logstash-input-dead_letter_queue/pull/31
- [x] [logstash-input-http](https://github.com/logstash-plugins/logstash-input-http): https://github.com/logstash-plugins/logstash-input-http/pull/148
- [x] [logstash-input-tcp](https://github.com/logstash-plugins/logstash-input-tcp): https://github.com/logstash-plugins/logstash-input-tcp/pull/190

For Logstash 6.8.x some plugins use older major versions and need to be branched off.

- [x] https://github.com/logstash-plugins/logstash-filter-geoip/pull/199
- [x] https://github.com/logstash-plugins/logstash-input-beats/pull/440
- [x] https://github.com/logstash-plugins/logstash-input-tcp/pull/191

Logstash Core:

- [x] main: https://github.com/elastic/logstash/pull/13544/
- [x] 6.8: https://github.com/elastic/logstash/pull/13545/
- [x] Backport to 8.0: https://github.com/elastic/logstash/pull/13546
- [x] Backport to 7.17: https://github.com/elastic/logstash/pull/13547
- [x] Backport to 7.16: https://github.com/elastic/logstash/pull/13548
- [x] Update lockfile on 7.16 https://github.com/elastic/logstash/pull/13549
- [x] Update lockfile on 7.17 https://github.com/elastic/logstash/pull/13550
- [x] Update lockfile on 6.8 https://github.com/elastic/logstash/pull/13553
- [x] Update lockfile on 8.0 https://github.com/elastic/logstash/pull/13557
- [x] Release note for 7.16.2 https://github.com/elastic/logstash/pull/13551
- [x] Release note for 6.8.22 https://github.com/elastic/logstash/pull/13555

**Comment by yaauie** [comment]
While we are at it, we should make an attempt to ensure that `log4j-core` is _only_ included in the dependency graph for `test*` (as generated with `./gradlew -q dependencies`). Many of our plugins already satisfy this by declaring compile/implementation dependencies on `log4j-api` and testCompile/testImplementation dependencies on `log4j-core`.

**Comment by jsvd** [comment]
With the talk of a 2.17.0 release, we may retarget all these PRs to that version instead, depending on the release timing and severity of the bugs it fixes.

**Comment by vinay32724** [comment]
Any tentative date when the new version will be out ?

**Comment by jsvd** [comment]
Retargeting these prs to the recently released 2.17.0

**Comment by octavialarentisgsa** [comment]
Is v7.16.2 released ? The Elastic release notes here ([https://www.elastic.co/guide/en/logstash/current/releasenotes.html]) list the version, but its not released here.
