### ISSUE TITLE
[META] problems surfacing due switching docker base image

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13572]
Logstash is (recently) [switched it's base Docker image](https://github.com/elastic/logstash/pull/13442) from CentOS 7 to Ubuntu 20.04

This issue is meant to track (mostly plugin testing) related issues caused by the switch.

- [x] https://github.com/logstash-plugins/logstash-input-beats/pull/442
- [ ] ?trying to upgrade [rufus-scheduler](https://github.com/elastic/logstash/issues/12931) in [http_poller input](https://github.com/logstash-plugins/logstash-input-http_poller/pull/130) leads to an issue while [interrupting the plugin](https://app.travis-ci.com/github/logstash-plugins/logstash-input-http_poller/jobs/553759457#L663)
  * [ ] interrupt example failing on [input ES](https://app.travis-ci.com/github/logstash-plugins/logstash-input-elasticsearch/jobs/563200404#L929) and others -> cause is likely not due rufus-scheduler upgrade
- [x] input exec long sub-process spawn times [sample run](https://app.travis-ci.com/github/logstash-plugins/logstash-input-exec/jobs/554055755#L520-L525) https://github.com/logstash-plugins/logstash-input-exec/pull/32
- [x] a lot of integration test failures on JMS input, [sample](https://app.travis-ci.com/github/logstash-plugins/logstash-input-jms/jobs/553401730) https://github.com/logstash-plugins/logstash-input-jms/pull/53

**Comment by kares** [comment]
since https://github.com/elastic/logstash/commit/94d04f8044b88ebab1e9cabde0a3eada8c446107 this should now be surfacing with 7.x SNAPSHOT builds as well

**Comment by kares** [comment]
the interrupt issue is related to the rufus-scheduler update after all, the initialization of `Scheduler#start`
executing a `EoTime.now` (rufus 3.0 wasn't using a custom Time impl and did a `Time.now`) which causes local time-zone detection using tzinfo which has some heavy initialization esp. on CI, the scheduler is still stuck in loading .rb files which we try to shut it down.

a work-around of avoiding execution of such code in a separate thread will be in place:
```ruby
begin
  # TODO: CI work-around - will most likely be moved to the scheduler mixin
  require 'et-orbi.rb' # a dependency of rufus-scheduler since 3.4
  ::EtOrbi::EoTime.now # might take a long time to initialize - loading timezones
  # from tz-info and thus gets un-predictable on CI, since the scheduler worker
  # might be stuck loading dependencies while we
rescue LoadError
end
```
