### ISSUE TITLE
[Doc][Meta] Security docs: restructure, refactor, expand, update

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#13573]
While generally correct, the Logstash security docs need some rework and expansion. Most of the information is generally correct. However, the topics are thrown together without a lot of _important conceptual information_ and _context_ that less experienced users need. 

### User goal 
We will provide a better content architecture and additional information to help users understand what they need to do and to help them make the best decisions for their environment.  

### Purpose
The purpose of this meta issue is to:
- outline and scope the work
- provide a single place to collection information and allow for comment
- share the vision so that people have a sense of how this effort will unfold

### To Do
- [ ] Foundational: Restructure source files and apply doc standards and best practices
- [ ] Develop a better content architecture (to include new information and much needed conceptual information) 
- [ ] Figure out how to partner with Elasticsearch documentation to give users the best possible information experience (by linking, sharing, consolidating info, etc.) 
- [ ] Security ON by default: Add CA and fingerprint information for connecting to a secure
