### ISSUE TITLE
[META] Update log4j dependencies to `2.17.1`

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#13580]
- [x] [logstash-filter-date](https://github.com/logstash-plugins/logstash-filter-date): https://github.com/logstash-plugins/logstash-filter-date/pull/145
 (update unnecessary - log4j is provided dependency)
- [x] [logstash-filter-dissect](https://github.com/logstash-plugins/logstash-filter-dissect): logstash-plugins/logstash-filter-dissect#82
 (update unnecessary - log4j provided dependency)
- [x] [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip): logstash-plugins/logstash-filter-geoip#203
 (update unnecessary - log4j is provided dependency)
- [x] [logstash-input-azure_event_hubs](https://github.com/logstash-plugins/logstash-input-azure_event_hubs): (1.4.3: log4j-api is provided dependency)
- [x] [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats): (6.2.5: log4j-api provided dependency)
- [x] [logstash-input-dead_letter_queue](https://github.com/logstash-plugins/logstash-input-dead_letter_queue):  logstash-plugins/logstash-input-dead_letter_queue#32
- [x] [logstash-input-http](https://github.com/logstash-plugins/logstash-input-http): (3.4.5: log4j-api provided dependency)
- [x] [logstash-input-tcp](https://github.com/logstash-plugins/logstash-input-tcp):  https://github.com/logstash-plugins/logstash-input-tcp/pull/196

For Logstash 6.8.x branched versions of plugins:

- [x] [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip): (5.0.5) logstash-plugins/logstash-filter-geoip#202
- [x] [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats): (5.1.11)logstash-plugins/logstash-input-beats#444
- [x] [logstash-input-tcp](https://github.com/logstash-plugins/logstash-input-tcp): (5.2.7)  https://github.com/logstash-plugins/logstash-input-tcp/pull/195

Logstash Core:

- [x] main: https://github.com/elastic/logstash/pull/13564
- [x] 6.8: https://github.com/elastic/logstash/pull/13568
- [x] Backport to 8.0: https://github.com/elastic/logstash/pull/13565
- [x] Backport to 7.17: https://github.com/elastic/logstash/pull/13566
- [x] Backport to 7.16: https://github.com/elastic/logstash/pull/13567
- [x] Update lockfile on 6.8: https://github.com/elastic/logstash/pull/13583
- [x] Update lockfile on 7.16: https://github.com/elastic/logstash/pull/13581
- [x] Update lockfile on 7.17: https://github.com/elastic/logstash/pull/13582
- [x] Update lockfile on 8.0: https://github.com/elastic/logstash/pull/13584
- [x] Release note for 7.16.3: 
- [x] Release note for 6.8.23:

**Comment by nova-sangeeth** [comment]
@robbavey Can you please let me know when the changes for logstash will be complete and published with the latest log4j version.

**Comment by robbavey** [comment]
@nova-sangeeth This was completed and released as part of the `6.8.23` and `7.16.3` stack release.
