### ISSUE TITLE
[Doc][Meta] Research and fix `Edit` links on doc pages

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#13619]
The `Edit` links on docs pages are not 100% accurate. We need to research and fix them.  
The `Edit` links on each page in our documentation send the user to our source files in github. We value contributions from our community, and want to make contributing as easy as possible. 

Improvements in Elastic.co docs tooling (approximately 2019) made the "Edit" links better at guessing the  source URL for editing. Every link in the Logstash Reference was hard-coded to enable edits to plugin documents (because they live in their own repos). We've replaced some hard-coding over time, but we need to do more. 

- [x] Renaming `master` branch to `main` in several repos (including all plugin repos) means that `Edit` links for plugin docs don't resolve correctly. This should be easily remedied with a selective search/replace pass. 
- [x] Other pages in the Logstash Reference are behaving inconsistently, with some pages resolving correctly and others not. Track down the root cause and resolve the issues. 
- [x] General cleanup to hard-coded `Edit` links in the core of the Logstash Reference
- [x] Fix any other inconsistencies uncovered as part of this effort.
