### ISSUE TITLE
[Doc][Meta] General security doc improvements

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#13620]
This issue serves as a place to capture and track security-related comments and issues.

In the course of a phased docs overhaul, important and valuable comments surface that may be out of scope for a particular PR. We want to be sure that we capture and address them as part of  the broader scope of work. This issue is that place. 

- [ ] `logstash-*`/indexes for the`logstash_writer` role
   - [ ] https://github.com/elastic/logstash/pull/13597#issuecomment-1011086158
- [ ] Passwords in examples
   - [ ] https://github.com/elastic/logstash/pull/13597#issuecomment-1011134897
