### ISSUE TITLE
Automation: Releases, Documentation, Plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#13812]
This is a meta issue that collects automation work that would greatly simplify the life of a Logstash committer: from facilitating Logstash releases to automating docs generation.

For the on-demand tasks, care should be taken to place them close to the code/project whenever it is possible. For example:  to backport a PR, a user should only have to type a comment in the PR that was merged.

### Logstash

- [x] Bump the Logstash version to the next major/minor/patch: on demand GH Action to create a PR 
- [ ] Create an issue w/ release checklist: on demand GH Action
- [x] Prepare release notes draft: on demand GH Action to create a PR (currently: [in jenkins](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+logstash-generate-release-notes/))
- [ ] Update the [logstash_releases.json](https://github.com/elastic/logstash/blob/main/ci/logstash_releases.json): on demand GH Action 
- [x] Backport merged PR to another branch: PR Comment driven action
- [x] Update the lock file in preparation for a release: on demand GH Action (currently: [in jenkins](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+logstash-bump-plugin-versions/))

### Plugins

- [x] Publish a plugin: (on demand + PR comment) GH Action (Currently in https://github.com/logstash-plugins/publisher)
- [x] Bump a plugin version and draft release notes: PR Comment driven action (WIP: https://github.com/elastic/logstash-github-hooks)
- [x] Backport merged PR to another branch: PR Comment driven action

### Documentation

- [x] Generate documentation for a given Logstash branch: on demand GH Action (currently: [in jenkins](https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/))
- [x] Regenerate the Versioned Plugin Reference: Periodic + On demand action (currently: [in jenkins](https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+main+logstash-versioned-plugin-docs/))
