### ISSUE TITLE
[Meta] Plugin Build Issues (not related to jruby-9.3.4.0 upgrade)

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14235]
Test Failures

- [x] [logstash-filter-grok](https://github.com/logstash-plugins/logstash-filter-grok):  https://github.com/logstash-plugins/logstash-filter-grok/issues/178
- [x] [logstash-filter-fingerprint](https://github.com/logstash-plugins/logstash-filter-fingerprint): https://github.com/logstash-plugins/logstash-filter-fingerprint/issues/68
- [x] [logstash-filter-useragent](https://github.com/logstash-plugins/logstash-filter-useragent): https://github.com/logstash-plugins/logstash-filter-useragent/issues/81
- [x] [logstash-input-syslog](https://github.com/logstash-plugins/logstash-input-syslog): https://github.com/logstash-plugins/logstash-input-syslog/issues/70
- [x] [logstash-input-snmp](https://github.com/logstash-plugins/logstash-input-snmp): https://github.com/logstash-plugins/logstash-integration-snmp/issues/35
- [x] [logstash-filter-date](https://github.com/logstash-plugins/logstash-filter-date): https://github.com/logstash-plugins/logstash-filter-date/issues/149
- [x] [logstash-input-stdin](https://github.com/logstash-plugins/logstash-input-stdin): https://github.com/logstash-plugins/logstash-input-stdin/issues/22
- [x] [logstash-codec-netflow](https://github.com/logstash-plugins/logstash-codec-netflow): https://github.com/logstash-plugins/logstash-codec-netflow/issues/198
- [ ] [logstash-output-sqs](https://github.com/logstash-plugins/logstash-output-sqs): https://github.com/logstash-plugins/logstash-output-sqs/issues/37

Build Failures
- [ ] [logstash-input-websocket](https://github.com/logstash-plugins/logstash-input-websocket): https://github.com/logstash-plugins/logstash-input-websocket/issues/25
- [x] [logstash-output-websocket](https://github.com/logstash-plugins/logstash-output-websocket): https://github.com/logstash-plugins/logstash-output-websocket/issues/18
- [x] [logstash-input-google_cloud_storage](https://github.com/logstash-plugins/logstash-input-google_cloud_storage): https://github.com/logstash-plugins/logstash-input-google_cloud_storage/issues/19
- [x] [logstash-output-google_bigquery](https://github.com/logstash-plugins/logstash-output-google_bigquery): https://github.com/logstash-plugins/logstash-output-google_bigquery/issues/66

**Comment by robbavey** [comment]
@robbavey to review and close if irrelevant

**Comment by robbavey** [comment]
Closing - the remaining two plugins with failures have not been touched or had an issue raised in over 4 years
