### ISSUE TITLE
[Meta] Support JDK18

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#14230]
[JDK 18](https://openjdk.java.net/projects/jdk/18/) is GA since 2022/03/22 and we need to support it.

The list of non preview non incubating JEPs is:
- 400: UTF-8 by Default. 
- 408: Simple Web Server
- 413: Code Snippets in Java API Documentation
- 416:  Reimplement Core Reflection with Method Handles
- 418: Internet-Address Resolution SPI
- 421: Deprecate Finalization for Removal

### Task list
- [x] verify the build and Logstah can run with JDK18 #14240
- [x] update CI to use JDK 18
- [x] test run JDK 18 on CI
- [ ] ~~update documentation to list JDK 18 is supported~~ (Mac M1?)
- [x] verify building of tier1 and tier2 plugins works with JDK 18
   - [x] Azure EventHub input 
   - [x] Beats input 
   - [x] File input 
   - [x] Http Input 
   - [x] Kafka integration (input and output) 
   - [x] TCP input 
   - [x] Date filter 
   - [x] Geoip filter 
   - [x] User agent filter 
   - [x] SNMP input (Tier 2) 
   - [x] Dissect filter 

To test the plugins, configure local Ruby to the same version of the one shipped with Logstash (9.3.4) and then configure the modules export, because the code doesn't start Logstash using the `JvmOptionsParser` that handle this and prepares the opening of JVM modules.

```sh
export JRUBY_OPTS="-J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED"
```
