### ISSUE TITLE
[Meta] Native Java plugin improvements

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14379]
This meta issue is to track issues with native Java plugins, to determine what we need to ensure that they have parity with traditional ruby/mixed ruby and java plugins

Improve Getting Started Experience
- [ ] Ensure example plugin projects compile and build against logstash
  - [ ] https://github.com/logstash-plugins/logstash-output-java_output_example/pull/14
  - [ ] https://github.com/logstash-plugins/logstash-filter-java_filter_example/pull/30
  - [ ] https://github.com/logstash-plugins/logstash-input-java_input_example/pull/16
  - [ ] Fix codec example code to compile and build against logstash
- [ ] Identify and fix documentation gaps 

Improve Development Experience
 - [ ] Identify and fix gaps in implementation between ruby and java plugins
   - [ ] #14306 

Improve User Experience
- [ ] Identify and fix gaps in experience between ruby and java plugins for deployment and availability and use of plugin after deployment 
  - [ ] #14060
