### ISSUE TITLE
[Meta] Logstash and Kubernete - Phase 1

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14380]
This project is intended to provide users with the best experience for using Logstash in a Kubernetes environment.

In particular we should document and provide examples including any pain points, surprises and places for improvement for the user experience when using Logstash with Kubernetes.

The first phase is expected to include these basic configuration flows:

- [ ] Basic setup Beats/Agent -> Logstash -> Elasticsearch
  - [ ] Add PQ and DLQ using persistent volumes
  - [ ] Point to Elastic Cloud and local instance
  - [ ] Configure with security/TLS
- [ ] Setup logstash monitoring
  - [ ] Elastic cloud
  - [ ] Local cluster
- [ ] Use Logstash as an agent output in Fleet managed mode
   Follow existing [user guide](https://github.com/elastic/observability-docs/issues/1691) describing the flow, ensuring that  . Follow this guide to ensure that it works with a K8S logstash, documenting any areas where it does not
- [ ] Add a second pipeline that requires the use of local state
  - [ ] This exercises the use of pipelines.yml, which wasn’t documented, or given as an example in the helm chart
  - [ ] Sincedb usage will require state storage.

**Comment by roaksoax** [comment]
I'm closing this issue in favor of https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash.html
