### ISSUE TITLE
Doc: Review and update Transforming Data topics

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#14433]
- [ ] [Transforming Data](https://www.elastic.co/guide/en/logstash/current/transformation.html)
         Source: 

   - [ ] [Performing Core Operations](https://www.elastic.co/guide/en/logstash/current/core-operations.html)
          Source: 
   - [ ] [Deserializing Data](https://www.elastic.co/guide/en/logstash/current/data-deserialization.html)
          Source: 
   - [ ] [Extracting Fields and Wrangling Data](https://www.elastic.co/guide/en/logstash/current/field-extraction.html)
          Source: 
   - [ ] [Enriching Data with Lookups](https://www.elastic.co/guide/en/logstash/current/lookup-enrichment.html)
          Source:

**Comment by robbavey** [comment]
@karenzone Is this still a relevant topic?
