### ISSUE TITLE
[Meta] Logstash Update Gradle version and dependencies for Google plugins

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#14474]
Update client libraries and transitive dependencies of Google (PubSub, BigQuery and Cloud Storage) plugins so that they don't have binary incompatibilities with current Logstash (`8.4.1`).
Originates mainly from Guava version, that was updated in Logstash `8.2` from `24.1.1`  to `31.0.1`.
Also `jackson-core` should match the same version, Logstah `8.3.0` switched from `2.9.10` to `2.13.3`.

plugin | PR | CI status | Merge & Pub
:------------ | :-------------| :-------------| :-------------
logstash-input-google_pubsub | https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/58| :heavy_check_mark: |  :heavy_check_mark: |
logstash-output-google_pubsub | https://github.com/logstash-plugins/logstash-output-google_pubsub/pull/27| :heavy_check_mark: |  :heavy_check_mark: |
logstash-input-google_cloud_storage | https://github.com/logstash-plugins/logstash-input-google_cloud_storage/pull/20| :heavy_check_mark: |  |
logstash-output-google_cloud_storage | https://github.com/logstash-plugins/logstash-output-google_cloud_storage/pull/48| :heavy_check_mark: |  :heavy_check_mark: |
logstash-output-google_bigquery | https://github.com/logstash-plugins/logstash-output-google_bigquery/pull/67| :heavy_check_mark: | :heavy_check_mark:  |

- [x] https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/58
- [x] https://github.com/logstash-plugins/logstash-output-google_pubsub/pull/27
- [ ] https://github.com/logstash-plugins/logstash-input-google_cloud_storage/pull/20
- [x] https://github.com/logstash-plugins/logstash-output-google_cloud_storage/pull/48
- [x] https://github.com/logstash-plugins/logstash-output-google_bigquery/pull/67

**Comment by kellypug** [comment]
Please also update the libraries in the latest version of v7 (v7.17.6)

**Comment by andsel** [comment]
@kellypug this can't be done because Logstash `7.17.x` already ships with `24.1.1` and it's not updated. The new versions of plugins has a strict requirements to run on Logstash `>= 8.2.0`

**Comment by kellypug** [comment]
Can the jackson-databind library versions be udpated?
