### ISSUE TITLE
[Meta] Logstash and Kubernetes - Phase 2 [wip]

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14520]
[Phase 1](https://github.com/elastic/logstash/issues/14380) of the Logstash/Kubernetes project was an exploratory phase to gain a better understanding of Logstash when run with Kubernetes, and to scope the work needed to improve the experience of users running Logstash in a kubernetes environment.

Phase 2 of the Logstash and Kubernetes project is to provide resources for users to help them with get started with running Logstash on Kubernetes, and provide guidance on best practices on how to run and operate Logstash on Kubernetes

These meta issue will contain the tasks needed to complete

- [ ] Create Documentation structure for Logstash Kubernetes documentation
  - [ ] Create table of contents/proposed outline of documentation
  - [ ] Create documentation skeleton structure

- [ ] Create Logstash/Kubernetes recipes
  - Create a set of recipes to provide samples for how best to implement Logstash in Kubernetes for a number of 
  - [ ] Create place in elastic organization as a repo for logstash k8s recipes 
  - [ ] Beats/Agent -> Logstash -> Elasticsearch
    - [ ] Simple quickstart case
      - Autoscaling too?
  - [ ] Beats/Agent -> Logstash -> Elasticsearch with PQ and DLQ and secure config to Elasticsearch CRD 
  - [ ] Beats/Agent -> Logstash -> Elasticsearch in the cloud
  - [ ] Kafka -> Logstash -> Elasticsearch
    - Example of a pull-based plugin that allows autoscaling as work is partitioned automatically and work state is stored externally to logstash
  - [ ] JDBC -> Logstash -> Elasticsearch
    - Requires `last_run_metadata_path`
    - Requires "external" jar files to be added to classpath

- [ ] Implement documentation topics (TBD)
  - [ ] Overview/Introduction
  - [ ] Getting started guide
  - [ ] Troubleshooting
  - [ ] **TBD**
