### ISSUE TITLE
Kubernetes Guidelines Documentation - Getting Started Guide

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14576]
- [ ] Step-by-step walkthrough of simple logstash example
  - [x] Pre-requisites before installing logstash https://github.com/elastic/logstash/pull/14532
  - [ ] Annotated walkthrough of example Covered by #14655
  - [ ] Expected results after completion, with pointers to troubleshooting guide Covered by #14655
  - [ ] #14759
- [ ]  Mapping Logstash concepts to Kubernetes Covered in #14655
  - [ ] logstash.yml
  - [ ] pipeline config
  - [ ] log4j properties
  - [ ] jvm options
