### ISSUE TITLE
Pipeline Health API - Plugin Level Metrics

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#14601]
Part of #14463

**Plugin-level Metrics**

We will use the pipeline-level metrics as a prototype for plugin-level metrics, so that users can dig into the cause of degraded status, whether it is an output that is experiencing back-pressure resulting in a throughput drop, a filter that is taking more CPU-time per event than usual, an input that is not receiving events from upstream, etc.

Because the filter-and-output phase of a pipeline is typically run in parallel, filters and outputs will likely benefit from having their metric rates against both the wall-clock and the CPU clock.

---

_**Purpose of this task:**_ Heavily optimize for only providing known-useful signals and very intentionally avoiding adding noise. 
- On _**filters and outputs**_, 
  - a `worker_utilization (duration / (uptime * worker count))` shows what percent of available resources an individual plugin instance is taking and can help identify where the blocker is.
  - we also provide a (to be named) cost-per-event metric (duration / event) to surface issues with a plugin that operates on a very small subset of events (via conditionals) but contributes disproportionately to the cost of getting its events through.
- On **_codecs_**, we simplify to a single throughput metric, since they may or may not be running in workers.
- On **_inputs_**, we also simplify throughput since the value add is the rate at which they are pushing events. We do NOT have a per-plugin `queue_backpressure` since this provides no value beyond the pipeline-level metric of the same name and is more likely to cause users to inspect the inputs when this signal is trying to tell them to check the downstream pipeline to identify the source of the back-pressure.

We provide the plugin level flow metrics under already exist node and pipeline `stats` metrics: `/_node/stats` & `/_node/stats/pipelines`, under the corresponding pipeline settings as follow:

API response share of **_inputs_** flow:
```
"plugins": {
  "inputs": [
  {
    "flow": {
      "throughput": 0
    },
    …
  }],
```

API response share of **_codecs_** flow:
```
  "codecs": [
  {
    "flow": {
      "throughput": 0
    },
    …
  }],
```

API response share of **_filters_** flow:
```
  "filters": [
  {
    "flow": {
      "workers_cost_per_event": 0,
      "workers_utilization": 0
    },
    …
  }],
```

API response share of **_outputs_** flow:
```
  "outputs": [
  {
    "flow": {
      "workers_cost_per_event": 0,
      "workers_utilization": 0
    },
    …
  }]
}
```

---
**Implementation plan**
- [x] Introduce combined flow metric provides to calculate codec throughput
- [x] Implement calculation of `worker-cost-per-event` &  `worker-utilization` flow metrics
- [x] Integration tests
- [x] Documentation, including troubleshooting

**Comment by kaisecheng** [comment]
#root-cause : https://github.com/elastic/logstash/issues/16275
