### ISSUE TITLE
[Meta] Upgrade code and plugins to Jruby 9.4

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#14802]
> https://www.jruby.org/2022/11/23/jruby-9-4-0-0.html
> The release of JRuby 9.4 represents a leap forward to Ruby 3.1 compatibility

> Ruby Compatibility
>  * Compatibility is updated to Ruby 3.1 level. This includes all Ruby 2.7, 3.0, and 3.1 features except where noted below. ([#6464](https://github.com/jruby/jruby/issues/6464), [#6878](https://github.com/jruby/jruby/issues/6878), [#7015](https://github.com/jruby/jruby/issues/7015))
>     * Ractor is not yet supported. JRuby users can achieve better parallelism by using threaded libraries and frameworks.
>     * The scheduler interface for IO, locks, and fibers is not yet supported. It will be added in an update release.
>
> * Nearly all features from CRuby’s NEWS file have been implemented. Most new tests and specs pass.
> * Remaining 3.0 and 3.1 features will be implemented in an update release. See [#7459](https://github.com/jruby/jruby/pull/7459) and [#7460](https://github.com/jruby/jruby/pull/7460).
>
> Standard Library
>  * Much of the standard library has moved out to gems, and JRuby supports a large subset of these gems. See [lib/pom.rb](https://github.com/jruby/jruby/blob/9.4.0.0/lib/pom.rb) for the complete list of default and bundled gems.
> * Greatly improved PTY and spawn support thanks to the subspawn gem, which is included as part of the standard library. [#7393](https://github.com/jruby/jruby/pull/7393)
> 
> JVM Integration
> * Java setFoo methods that do not match JavaBean standards (return value other than void, for example) will now also generate a foo= method when imported into Ruby. ([#7340](https://github.com/jruby/jruby/issues/7340), [#7352](https://github.com/jruby/jruby/pull/7352))
>
> Platform Support
>
> * The JRuby launcher script has been ported to POSIX shell (/bin/sh) and no longer requires Bash. ([#7024](https://github.com/jruby/jruby/pull/7024))
> * Initial support for the LoongArch64 platform has been inherited from the Java Native Runtime libraries.
>
> Third-party Libraries and Frameworks
> * Initial support for Rails 7. SQLite and MySQL are largely functional, but work remains to update the m and PostgreSQL.

```[tasklist]
### Tasks
- [ ] #14861
- [ ] #14945
- [ ] #14996
- [x] Check `bin/logstash -i irb` works properly and doesn't break the shell on exit, there is an existing issue for this in JRuby 9.4.2.0: https://github.com/jruby/jruby/issues/7740 (published with JRuby `9.4.3.0`). It happens also on JRuby `9.4.3.0` https://github.com/jruby/jruby/issues/7727
- [ ] https://github.com/elastic/logstash/issues/15113
- [ ] https://github.com/elastic/logstash/issues/15160
```

```[tasklist]
### Plugin Updates
- [ ] https://github.com/logstash-plugins/logstash-integration-jdbc/issues/133
```

**Comment by roaksoax** [comment]
Closed as complete.
