### ISSUE TITLE
[Maintenance] Test all tier 1 and tier 2 plugins against JRuby 9.4

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#14996]
# Tier 1

```[tasklist]
### Tier 1 - Input Plugins
- [x] azure_event_hubs
- [x] beats
- [x] elasticsearch
- [x] file
- [x] generator
- [x] heartbeat
- [x] http
- [x] http_poller
- [x] jdbc https://github.com/logstash-plugins/logstash-integration-jdbc/pull/125
- [x] kafka (remember to `./kafka_test_setup.sh` and at the end `./kafka_test_teardown.sh`)
- [x] rabbitmq
- [x] redis
- [x] s3 (provided by https://github.com/logstash-plugins/logstash-integration-aws) PR: https://github.com/logstash-plugins/logstash-integration-aws/pull/29
- [x] stdin FAIL for other existing causes as described in: https://github.com/logstash-plugins/logstash-input-stdin/issues/22
- [x] syslog FAIL for other existing causes as described in: https://github.com/logstash-plugins/logstash-input-syslog/issues/70
- [x] udp
- [x] elastic_agent (beats input alias)
```
```[tasklist]
### Tier 1 - Codec Plugins
- [x] avro
- [x] cef
- [x] es_bulk
- [x] json
- [x] json_lines
- [x] line
- [x] multiline
- [x] plain
- [x] rubydebug
```

```[tasklist]
### Tier 1 - Filter Plugins
- [x] cidr https://github.com/logstash-plugins/logstash-filter-cidr/pull/26
- [x] clone
- [x] csv
- [x] date https://github.com/logstash-plugins/logstash-filter-date/pull/156
- [x] dissect https://github.com/logstash-plugins/logstash-filter-dissect/pull/87
- [x] dns https://github.com/logstash-plugins/logstash-filter-dns/pull/71
- [x] drop
- [x] elasticsearch
- [x] fingerprint
- [x] geoip https://github.com/logstash-plugins/logstash-filter-geoip/pull/215
- [x] grok https://github.com/logstash-plugins/logstash-filter-grok/pull/190
- [x] http
- [x] jdbc_static https://github.com/logstash-plugins/logstash-integration-jdbc/pull/125
- [x] jdbc_streaming https://github.com/logstash-plugins/logstash-integration-jdbc/pull/125
- [x] json (failure is already addressed by PR  https://github.com/logstash-plugins/logstash-filter-json/pull/52)
- [x] kv https://github.com/logstash-plugins/logstash-filter-kv/pull/104
- [x] memcached
- [x] mutate https://github.com/logstash-plugins/logstash-filter-mutate/pull/169
- [x] prune
- [x] ruby https://github.com/logstash-plugins/logstash-filter-ruby/pull/66
- [x] sleep
- [x] split https://github.com/logstash-plugins/logstash-filter-split/pull/46
- [x] syslog_pri
- [x] translate https://github.com/logstash-plugins/logstash-filter-translate/pull/98
- [x] truncate
- [x] urldecode https://github.com/logstash-plugins/logstash-filter-urldecode/pull/11
- [x] useragent https://github.com/logstash-plugins/logstash-filter-useragent/pull/86
- [x] uuid
- [x] xml https://github.com/logstash-plugins/logstash-filter-xml/pull/81
```

```[tasklist]
### Tier 1 - Output Plugins
- [x] elastic_app_search
- [x] elasticsearch (verified skipping integration `bundle exec rspec -fd --tag "~integration" --tag "~secure_integration"`)
- [x] email ( existing erro https://github.com/logstash-plugins/logstash-output-email/issues/67)
- [x] file
- [x] http
- [x] kafka
- [x] rabbitmq
- [x] redis
- [x] s3 (provided by https://github.com/logstash-plugins/logstash-integration-aws)
- [x] stdout
- [x] tcp
- [x] udp
```

# Tier 2

```[tasklist]
### Tier 2 - Input Plugins
- [x] couchdb_changes (already fails on `main`)
- [x] gelf
- [x] graphite
- [x] jms
- [x] snmp
- [x] sqs  (provided by https://github.com/logstash-plugins/logstash-integration-aws)
- [x] twitter
```

```[tasklist]
### Tier 2 - Codec Plugins
- [x] collectd ( invoke vendor before testing, `rake vendor`)
- [x] dots
- [x] fluent
- [x] graphite
- [x] msgpack
- [x] netflow FAIL as https://github.com/logstash-plugins/logstash-codec-netflow/issues/198
```

```[tasklist]
### Tier 2 - Filter Plugins
- [x] aggregate
- [x] de_dot
- [x] throttle
```

```[tasklist]
### Tier 2 - Output Plugins
- [x] csv https://github.com/logstash-plugins/logstash-output-csv/pull/25
- [x] graphite
```
