### ISSUE TITLE
Use better default values for workers/pools/buffers

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#1512]
Things to tune and/or make default:

- [x] workers, based on number of CPU cores
- [x] review pool/buffer sizes w/ tests for performance
- [x] Change default protocol in ES output from `node` to `http` https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/150
- [x] Audit existing defaults for Kafka consumer https://github.com/logstash-plugins/logstash-input-kafka/issues/36
- [x] Change the default bulk size to 500 instead of 5000 documents https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/181
- [ ] Remove original/temporary timestamp field by default https://github.com/logstash-plugins/logstash-filter-date/issues/24

Specific to plugins:
* redis: use batch operations by default.
* enable batch operations by default where possible

Specific Issues:

Will be updated as we file more individual issues against plugins

**Comment by guyboertje** [comment]
I want to begin a discussion about which 'values' are considered default and important.

**Comment by guyboertje** [comment]
pipeline.rb
- [ ] [line 36](https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L36) ```SizedQueue.new(20)```
- [ ] [line 44](https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L44) ```@settings = { "filter-workers" => 1 }```
- [ ] [line 165](https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L160) ```Thread.new { Stud.interval(5) { @input_to_filter.push(LogStash::FLUSH) } }```

**Comment by guyboertje** [comment]
agent.rb

- [ ] [line 22](https://github.com/elastic/logstash/blob/master/lib/logstash/agent.rb#L22) ```option ["-w", "--filterworkers"], "COUNT",``` default = 1
- [ ] [line 26](https://github.com/elastic/logstash/blob/master/lib/logstash/agent.rb#L26) ```option "--watchdog-timeout", "SECONDS",``` default = 10
- [ ] [line 131](https://github.com/elastic/logstash/blob/master/lib/logstash/agent.rb#L131) ```Thread.new(@logger) {|logger| sleep 5; logger.warn(I18n.t("logstash.agent.slow_shutdown"))```

**Comment by guyboertje** [comment]
/outputs/base.rb

- [ ] [line 71](https://github.com/elastic/logstash/blob/master/lib/logstash/outputs/base.rb#L71) ```@worker_queue = SizedQueue.new(20)```

**Comment by ph** [comment]
The current implementation of the watchdog will go alway, I'll make a PR to remove it completely.
It's not currently used and it was a source of problems for some plugins DNS IIRC.

**Comment by suyograo** [comment]
@guyboertje `@settings = { "filter-workers" => 1 }` is definitely candidate for changing. IMO we should default that to # of cores in the system. But we need to be careful of one usecase: multiline filter which needs events to be in order (and will not work with `-w`). But, we can just check of existence of that filter at start up and not do it.

**Comment by guyboertje** [comment]
@suyograo - there are checks for in-order events AFAIK.

**Comment by guyboertje** [comment]
inputs/elasticsearch.rb

- [ ] [line 50](https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/lib/logstash/inputs/elasticsearch.rb#L50) ``` config :size, :validate => :number, :default => 1000 ```
- [ ] [line 55](https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/lib/logstash/inputs/elasticsearch.rb#L55) ``` config :scroll, :validate => :string, :default => "1m" ```

**Comment by guyboertje** [comment]
inputs/http.rb

- [ ] [line 50](https://github.com/logstash-plugins/logstash-input-http/blob/master/lib/logstash/inputs/http.rb#L50) ``` config :threads, :validate => :number, :default => 4 ``` should be no. of cpus

**Comment by guyboertje** [comment]
inputs/imap.rb

- [ ] [line 26](https://github.com/logstash-plugins/logstash-input-imap/blob/master/lib/logstash/inputs/imap.rb#L26) ``` config :fetch_count, :validate => :number, :default => 50 ```
- [ ] [line 28](https://github.com/logstash-plugins/logstash-input-imap/blob/master/lib/logstash/inputs/imap.rb#L28) ``` config :check_interval, :validate => :number, :default => 300 ```

**Comment by guyboertje** [comment]
inputs/kafka.rb

- [ ] [line 56](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L56) ``` config :consumer_threads, :validate => :number, :default => 1 ``` should this be called 'partitions'?
- [ ] [line 58](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L58) ``` config :queue_size, :validate => :number, :default => 20 ```
- [ ] [line 63](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L63) ``` config :rebalance_max_retries, :validate => :number, :default => 4 ```
- [ ] [line 65](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L65) ``` config :rebalance_backoff_ms, :validate => :number, :default => 2000 ```

**Comment by guyboertje** [comment]
inputs/lumberjack.rb

- [ ] [line 40](https://github.com/logstash-plugins/logstash-input-lumberjack/blob/master/lib/logstash/inputs/lumberjack.rb#L40) ``` BUFFERED_QUEUE_SIZE = 1 ```
- [ ] [line 41](https://github.com/logstash-plugins/logstash-input-lumberjack/blob/master/lib/logstash/inputs/lumberjack.rb#L41) ``` RECONNECT_BACKOFF_SLEEP = 0.5 ```

**Comment by guyboertje** [comment]
inputs/rabbitmq.rb

- [ ] [line 76](https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq.rb#L76) ``` config :prefetch_count, :validate => :number, :default => 256 ```

**Comment by guyboertje** [comment]
inputs/redis.rb

- [ ] [line 59](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L59) ``` config :batch_count, :validate => :number, :default => 1 ``` should this start at queue size (20) and, possibly, dynamically change to grab as many as would fill the queue?

**Comment by guyboertje** [comment]
NOTE:  Magic numbers/strings, just convert the magic value into a descriptive method call from `LogStash::Util::Defaults`

**Comment by purbon** [comment]
done the timestamp behaviour at -> https://github.com/logstash-plugins/logstash-filter-date/pull/36
