### ISSUE TITLE
[Meta] Logstash - Support Diagnostics - Flow + Diagnostics + Analyser improvements

### ISSUE THREAD

**Issue by edmocosta** [elastic/logstash#15144]
## Description

The primary goal of this effort is to make it easier for customers to participate in diagnosing their own problems, by connecting tools that are already present in Logstash itself and in our Support toolchain

## Goals

To achieve this, we have identified three orthogonal goals

### Flow Metrics in Diagnostics Analyzer

In 8.5-8.7, we introduced and then expanded Flow Metrics in the Logstash node stats API, which means they are already available as part of capture from our official Elastic diagnostic tool. Flow metrics give us current, recent, and lifetime flow rates for many meaningful metrics, allowing us to compare a pipeline or process's current behavior to _itself_ over time.

But the Support Diagnostics Analyzer does not yet incorporate Flow Metrics and still requires two-spaced captures to provide meaningful rate-of-flow insights. Additionally, the as-presented rate-of-flow metrics in the analyzer tool are not standardized or cohesive (mixing units or mixing wall-clock vs CPU clock)

We want to improve the Analyzer so that it includes process-, pipeline-, and plugin-level Flow Metrics so that it can provide guidance and insights from a single capture.

### Bundle Diagnostics Analyzer with the Capture Tool

There's no reason why our Support Diagnostics Analyzer needs to live separately from the tool that captures the diagnostic and bundling the two together would allow our customers to run the analyzer themselves.

### Bundle Diagnostics Capture and Analyzer with Logstash distribution

We would like to explore adding functionality to Logstash to make it able to capture its own Diagnostics in response to an API call, initially targeting a local on-disk tarball and potentially a path back to Elasticsearch (e.g., monitoring cluster)

## Tasks

```[tasklist]
##### Others
- [ ] https://github.com/elastic/logstash/issues/15145
- [ ] Logstash - Support Diagnostics - Convert and migrate the existing ruby diagnostics into the support-diagnostic tool
- [ ] Logstash - Support Diagnostics - Bundle the diagnostics capture and analyzer with the Logstash distribution
```

---
Diagnostic tool: https://github.com/elastic/support-diagnostics
