### ISSUE TITLE
Doc: Add/update docs for Logstash-to-Logstash communication

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#15169]
Related: #15163

```[tasklist]
### Tasks
- [ ] Add documentation for new [logstash-integration-logstash](https://github.com/logstash-plugins/logstash-integration-logstash)
    - [ ] /docs/index.asciidoc
    - [ ] input-logstash.asciidoc
    - [ ] output-logstash.asciidoc
- [ ] Add new integration plugin docs to [Logstash Reference](https://www.elastic.co/guide/en/logstash/current/index.html)
- [ ] Verify that integration plugin docs have been picked up for [Versioned Plugin Reference](https://www.elastic.co/guide/en/logstash-versioned-plugins/current/index.html)
- [ ] Update existing [Logstash-to-Logstash communication](https://www.elastic.co/guide/en/logstash/current/ls-to-ls.html) docs
```

**Comment by robbavey** [comment]
@karenzone Can this be closed?
