### ISSUE TITLE
[Meta] Remove deprecated SSL settings from core and plugins

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16352]
In #14905, we embarked on a process to standardize SSL settings across Logstash and its plugins. 

We should continue this process by obsoleting old, deprecated settings for the `9.0` release of Logstash

## Problem Statement

During https://github.com/elastic/ingest-dev/issues/1340, we embarked on a standardization process of SSL Settings, and added standardized settings to Logstash-core, and our most used plugins.
During that process, we deprecated the old settings, keeping both sets of settings in place to provide continuity.

The next phase of this plan is to remove the old deprecated settings for the `9.0` release - the old settings have been marked as deprecated for over 18 months, and having two sets of settings for these products may be confusing for users.

We should go through the process of removing the old settings, marking them as obsolete.

#### Core
* Ensure that all unit and integration tests still pass
* Add details of change to the `9.0` breaking changes documentation in core.

#### Plugins
* Create new `version.x` branch from last commit.
* All plugin changes that remove SSL settings should be in a new `major` release
* Mark old SSL settings as obsolete
* Add details of change to the `9.0` breaking changes documentation in core.
* Add breaking change entry to plugin changelog
* Verify that any integration tests in core that rely on SSL settings still work. Fix any broken integration tests

## Tasks

```[tasklist]
- [ ] https://github.com/elastic/logstash/issues/16652
- [ ] https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/210
- [ ] https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/179
- [ ] https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1190
- [ ] https://github.com/logstash-plugins/logstash-input-beats/issues/506
- [ ] https://github.com/logstash-plugins/logstash-output-tcp/issues/56
- [ ] https://github.com/logstash-plugins/logstash-input-tcp/issues/225
- [ ] https://github.com/logstash-plugins/logstash-input-http/issues/181
- [ ] https://github.com/logstash-plugins/logstash-filter-http/issues/53
- [ ] https://github.com/logstash-plugins/logstash-input-http_poller/issues/147
- [ ] https://github.com/logstash-plugins/logstash-output-http/issues/145
- [ ] https://github.com/logstash-plugins/logstash-input-elastic_serverless_forwarder/issues/9
```
