### ISSUE TITLE
Gradle 9.0 preparation

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#16641]
Currently Logstash uses the Gradle `8.7`, there are some deprecations happening in Gradle`9.0` that we should fix to be ready for that release.

Running 
```sh
./gradlew test --warning-mode all
```
hit 2 warning:
```
 % ./gradlew test --warning-mode all
To honour the JVM settings for this build a single-use Daemon process will be forked. 
For more on this, please refer to https://docs.gradle.org/8.7/userguide/gradle_daemon.html#sec:disabling_the_daemon 
in the Gradle documentation.
Daemon will be stopped at the end of the build
Relying on the convention for Test.classpath in custom Test tasks has been deprecated. 
This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: 
https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#test_task_default_classpath

...

> Task :logstash-core:javaTests
Relying on the convention for Test.testClassesDirs in custom Test tasks has been deprecated. 
This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: 
https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#test_task_default_classpath
```

# `build.gradle` scripts changes
- [ ] avoid to use `rootProject.buildDir` and use `rootProject.layout.buildDirectory`
- [ ] `shadowJar` is using old API `FileTreeElement.getMode()` instead of `FileTreeElement.getPermissions()`. Update shadowing plugin, from `com.github.johnrengelman.shadow` to `com.gradleup.shadow`.
- [ ] update wrapper to the latest `9.x` and resolve possible deprecations for `10.x`.

# Plugins that leverages Gradle

## Tier 1
- [ ] https://github.com/logstash-plugins/logstash-input-beats
- [ ] https://github.com/logstash-plugins/logstash-input-tcp
- [ ] https://github.com/logstash-plugins/logstash-input-http
- [ ] https://github.com/logstash-plugins/logstash-integration-kafka
- [ ] https://github.com/logstash-plugins/logstash-integration-snmp
- [ ] https://github.com/logstash-plugins/logstash-integration-jdbc
- [ ] https://github.com/logstash-plugins/logstash-integration-aws
- [ ] https://github.com/logstash-plugins/logstash-filter-geoip
- [ ] https://github.com/logstash-plugins/logstash-input-azure_event_hubs
- [ ] https://github.com/logstash-plugins/logstash-filter-date
- [ ] https://github.com/logstash-plugins/logstash-input-file
- [ ] https://github.com/logstash-plugins/logstash-input-dead_letter_queue
- [ ] https://github.com/logstash-plugins/logstash-filter-useragent
- [ ] https://github.com/logstash-plugins/logstash-filter-dissect

## Unsopported
- [ ] https://github.com/logstash-plugins/logstash-output-google_bigquery
- [ ] https://github.com/logstash-plugins/logstash-output-google_cloud_storage
- [ ] https://github.com/logstash-plugins/logstash-output-google_pubsub
- [ ] https://github.com/logstash-plugins/logstash-input-google_cloud_storage
- [ ] https://github.com/logstash-plugins/logstash-input-google_pubsub
- [ ] https://github.com/logstash-plugins/logstash-output-webhdfs

## Example plugins
- [ ] https://github.com/logstash-plugins/logstash-input-java_input_example
- [ ] https://github.com/logstash-plugins/logstash-filter-java_filter_example
- [ ] https://github.com/logstash-plugins/logstash-output-java_output_example
- [ ] https://github.com/logstash-plugins/logstash-codec-java_codec_example
