### ISSUE TITLE
Dependencies pollution wrap-up

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#16673]
# Abstract

From the discussion of https://github.com/logstash-plugins/logstash-integration-kafka/pull/178#discussion_r1827579467 during the development of a PR to include AWS IAM as a SASL mechanism in Kafka integration plugin.
Adding that extension posed the problems:
- the size of the overall transitive dependencies kicked in is not negligible. The gem size reach 65Mb from the original 13MB, and just for AWS service provider. If in a foreseeable future it would include also GCP IAM, the size could increment even more.
- shadowing of class names. Some transitive dependencies included (i.e: Netty) are also included by other plugins (like TCP or Beats inputs) and not necessarily at the same version.  Due to the flat classpath, shared between core and all plugins, this could pose some binary compatibility issues that aren't easy to resolve, or simply couldn't be resolved.

## Shadowing of class names (pollution of classpath)
This typical problem can be resolved in two ways:
- shading the conflicting dependencies under a specific package name (like something related to the plugin).
- implement a child classloader that could handle loading of classes for each plugin.

Following, we are going to discuss pros and cons of each solution.

### Shading dependencies
Shading all transitive dependencies under a package name related to the plugin is doable by leveraging the Gradle's `GradleUp/shadow` plugin https://github.com/GradleUp/shadow. 
Before apply the shading we have to keep in mind some points:
- don't include libraries that have pretty stable APIs, those that doesn't change during the development of minor releases. For example the API changes to Netty from version `4.1.n`and `4.1.n+20` suppose, shouldn't change so much (like also log4j2-api), so those can be kept out of shading process.
- don't shade class names that can be used in configuration. In the `logstash-input-kafka` https://github.com/logstash-plugins/logstash-integration-kafka/pull/178 there are a couple of settings (`sasl_jaas_config` and `sasl_client_callback_handler_class`) that receives public AWS classes (like `software.amazon.msk.auth.iam.IAMLoginModule` and `software.amazon.msk.auth.iam.IAMClientCallbackHandler`). Those classes are an implicit interface used by user that couldn't be shaded.
- some shading best practices include to create a new library (or submodule) for each shaded tree. For example, if a project depends on library `software.amazon.msk:aws-msk-iam-auth:2.2.0` a new submodule (like `input-kafka-aws-msk-iam-auth-shaded`) which only contains the dependency to shade and shading instructions, must be created.

**Pros & cons**
Pros:
- easier to implement, there is a Gradle plugin that can do this in excellent way.
- no headaches in get into the classloading mechanism of Java and JRuby.

Cons:
- changes has to be made on each plugin that uses external jars.
- attention has to be made to not shade (full) class names that are also used in configuration strings.
- not all dependencies has good reason to be shaded, for example netty or log4j2-api, which has pretty stable API.
- dimension of the uber-jar.
- could require to handle the publishing of the uber-jar .
- minimal class reuse and potential class space explosion.

### Classloader per plugin
Another way to solve the classpath pollution problem is to isolate each plugin in its own classloader, so that different versions of same class can co-exists under different classloaders, one per plugin.
This is harder to implement because nests and intertwines into the operation of JRuby. This classloader segregation has to work also for mixed plugins, plugins that are ruby gems, contains some shim Ruby code but bundles jar classes used to operate. In this context, the classloader should co-operate with JRuby so that when the JRuby plugin's code load a Java class it uses the segregation classloader and not the standard JRuby classloading.
There is more things to understand if an how it's feasible, plus classloading code could be hard.

**Pros & cons**
Pros:
- more elegant way to solve the problem.
- no need to change plugins build script.
- no need to potentially ship and handle the lifecycle of the uber-jar.

Cons:
- nesting into the classloaders hierarchy could be tough.
- doesn't eliminate the problem of big gems with a lot of transitive dependencies, because those have to be however vendored in the gem.
- remains the need to select which jar dependencies has to be vendored.

## Size of the generated plugin gem
The other side of this problem regards the size of the gem can reach. In particular, like in SASL configuration use case, a gem could reach considerable dimension just to ship transitive dependencies that are needed in specific settings. Probably in majority of the uses cases those dependencies are not used but the users pays the penalty to use a gem bundled with everything.
To limit the size of transitive dependencies in a gem the idea is to offload those not mandatory into another artifact, for example: 
- another gem that can be installed once needed.
- an uber-jar that can be downloaded and put into the class loader's path.

### Gem with optional dependencies
In this case the plugin that has optional dependencies would also generate and publish (how?) on rubygems a set of additional gems containing the full set of transitive dependencies required just for optional behaviours. In such case the Logstash plugin documentation has to be updated to explain **how** and **when** those optional artifacts needs to be installed.
The answer for **when** question is: the documentation itself.
The question related to **how**, an extension to `bin/logstash-plugin` tool can be imagined, so that it can installs also those kind of `extension` gems.

### Uber-jar that can be downloaded and put into the class loader's path
In this case a strategy similar to JDBC plugin driver could be followed, asking the user to manually download an uber-jar which contains all the transitive dependencies, and set a path into the plugin configuration so that it can explicitly load the jar, like in:
```ruby
require uber.jar
```
This poses a couple of questions: **where to publish the uber jar** and **when to update it**.

#### Where to publish?
As first though, being a Java jar, the answer could be the Maven repository, but has to be checked if there are any limitation to the size of the jar that can be uploaded, and is strictly related to the next question.

#### When to update it?
A new version of the uber-jar should be published when the requiring plugin updates its library dependency version and release a new gem version. The uber-jar creation and publish could be either a task of the Gradle build script or could be shaped as an external CI pipeline, to be manually triggered. The optimal solution is to automate also that step, so that the plugin developer doesn't have to remember that step.

# Final decision
The summary of the decision are:
- create an uber jar for each cloud provider, where the version of the jar match the version of the client library, for example if AWS has it's principal client in GAV `software.amazon.msk:aws-msk-iam-auth:2.2.0` the uber jar will have the same version number (`2.2.2`).
- the jar shadow the dependencies that could have higher risk of classpath clashing with other plugins.
- the Kafka input plugin exposes a new setting to define the paths to the uber jars to be loaded.

## Action plan
- [x] ~~in Kafka integration plugin add a tasks to create uberjar for AWS AIM and shadow the classes that could clash with other plugins.~~ was created a separate repo to host the uber jars: https://github.com/elastic/logstash-kafka-iams-packages
- [ ] update the Kafka plugin to expose setting to load optionally the uber jar containing the full dependency tree for AWS AIM.
- [x] resolve the problem to publish the uber jar, in particular define an automation to get notified when a new version of the client library is released.

**Comment by kaisecheng** [comment]
I have less concern about the size of the plugin and will try to avoid the complexity of the ClassLoader. Adding support for GCP and Azure may add another 100MB. With today's network speed, it increases the download time from a few seconds to minutes.

My concern is the reliability of JRuby and Ruby Maven, which give us build issues from time to time. I would try to avoid further integration with JRuby class loading. Shading dependencies is a durable solution with less follow-up maintenance work

**Comment by yaauie** [comment]
On the shading-dependencies front, I've [successfully used r8/"proguard"](https://github.com/biesemeyer/funlock/blob/main/build.gradle.kts#L22-L30) to shadow/shade, and have been impressed with just how efficiently it can pack things. The caveat is that we need to [define rules](https://github.com/biesemeyer/funlock/blob/main/packaging-rules.pro) for the entry-points, and any form of shading is going to be suseptable to issues when reflection is involved.

**Comment by jsvd** [comment]
From the user's perspective, what is the form of the experience we want to provide?
Do you think we should provide:
a) individual uber jars the user downloads and configures
b) individual "extension" gems the user installs through the logstash plugin manager?

I'm guessing that a shaded uber jar works for solution a) and b), the isolated classloader path only work for the extension gem, right?

I'm not sure if the open questions (e.g where to deploy a jar) are blockers to deciding the publishing envelope (uber jar vs extension gem) and the pollution solution (shading vs isolated classloader).

The sizes of extra jar/gem shouldn't be a deciding factor given we already publish >50mb gems to rubygems, and there are >50mb jars in maven.

Also, we can find a solution for the integration kafka cloud iam support that doesn't have to be a solution for all dependency pollution issues in Logstash core + plugins. The individual solution can end up being something we then expand to other issues in the future, though, especially if changing the uber jar vs extension gem or the shading vs isolated classloader doesn't introduce a breaking change.

**Comment by andsel** [comment]
@jsvd from user perspective I  would prefer to install such extensions, asking the user to download a jar an install in a specific path could be demanding. It's better to have the extension also to debug issues, when ask the list of installed plugins/extensions. In that case we could immediately know if the extension is installed or not, and in case is installed with the plugin manager, we know is in the right place for the plugin to grab and use it.

>The sizes of extra jar/gem shouldn't be a deciding factor given we already publish >50mb gems to rubygems, and there are >50mb jars in maven.

It's not just a problem of size I think, could be also intended as an attack surface. If I'm a user that want to connect just to AWS IAM it's useless to have also the dependencies related to Google IAM and if those depends on libraries that suffer of some security issue, then also AWS users has to update the extension.

Maybe is an overkill for the problem at this step, an just shading all transitive dependencies inside the Kafka plugin could be  enough, also if we create such a big gem. Shading is the mandatory part I think, it avoids classpath pollution and interference with other plugins.

**Comment by jsvd** [comment]
> asking the user to download a jar an install in a specific path could be demanding. 

We do this already for the jdbc plugins. Not saying I'm against it, just that there's precedent.
The concept of a plugin extension requires at this point an unknown amount of work where plugin extension gems will have their own metadata to be accepted but differentiated from the logstash plugins by the plugin manager. We may need to dig a bit more into what's involved before going this route.

> It's not just a problem of size I think, could be also intended as an attack surface. If I'm a user that want to connect just to AWS IAM it's useless to have also the dependencies related to Google IAM and if those depends on libraries that suffer of some security issue, then also AWS users has to update the extension.

Not necessarily, we could have one uber jar per cloud provider, like we have different driver jars for different databases.

The user would have to dowload the jar for their CSP and configure it in kafka, like they have to do for a serializer:

```
input {
   kafka {
     bootstrap_servers => ..
     value_deserializer_class => "org.apache.kafka.common.serialization.StringDeserializer"
     iam_jar_path => '/tmp/path/azure_iam_uber.jar'
     iam_class => 'a.b.c.e.d'
     iam_setting1 => 
     iam_setting2 => 
```

I'd guess that if we do the plugin extension, you'd skip `iam_jar_path`, but still define `iam_class` ?

**Comment by andsel** [comment]
> still define iam_class ?

Yes that's mandatory is a settings that currently is going to be passed down to the Kafka client, as proposed in https://github.com/logstash-plugins/logstash-integration-kafka/pull/178 it's name is `sasl_client_callback_handler_class`

> Not necessarily, we could have one uber jar per cloud provider,

That's fine for me, should we create those uber jars during the build process of the plugin gem, and publish also as part of the gem publishing process?

**Comment by andsel** [comment]
Close this as https://github.com/logstash-plugins/logstash-integration-kafka/pull/178 was published with version `11.16.1`
