### ISSUE TITLE
Please garbage collect few obsolete PRs

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#2165]
- [x] #1993 - codec removed in 1.5
- [x] #1099 - already fixed in #1164
- [x] #1232 - makefile is dead
- [x] #1234 - obsolete with 1.5
- [x] #1245 - obsolete with 1.5
- [x] #1027 - obsolete with 1.5
- [x] #1845 - superseed by https://github.com/logstash-plugins/logstash-input-pipe/pull/1
- [x] #1266 - replaced by #2164
- [x] #1457 - already fixed 

and some obsolete/duplicate issues
- [x] #1265 - issue related to #1266, covered by #2164 
- [x] #1464 - fixed in 1.5.0 by #769 
- [x] #1615 - covered by https://github.com/logstash-plugins/logstash-filter-date/pull/2
- [x] #1502 - fixed by #1354
- [x] #1602 - inactive question
- [x] #1659 - inactive question
- [x] #1662 - duplicate of #1709 
- [x] #1733 - answered
- [x] #2057 - covered by #2164 
- [x] #1917 - answered
- [x] #1862 - anwered in googlegroups
