### ISSUE TITLE
review & merge plugins new Timestamp & Json API updates

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3060]
- [x] https://github.com/logstash-plugins/logstash-input-puppet_facter/pull/1
- [x] https://github.com/logstash-plugins/logstash-output-redmine/pull/1
- [ ] https://github.com/logstash-plugins/logstash-output-mongodb/pull/1
- [x] https://github.com/logstash-plugins/logstash-output-graphtastic/pull/1
- [x] https://github.com/logstash-plugins/logstash-output-metriccatcher/pull/1
- [x] https://github.com/logstash-plugins/logstash-output-google_bigquery/pull/2
- [x] https://github.com/logstash-plugins/logstash-output-datadog/pull/1
- [ ] https://github.com/logstash-plugins/logstash-output-datadog_metrics/pull/1
- [x] https://github.com/logstash-plugins/logstash-output-circonus/pull/1

**Comment by ph** [comment]
@colinsurprenant I think you can go ahead and merge most of theses PR.

**Comment by ph** [comment]
@colinsurprenant You can merge the PRs, only 1 or 2 have minor comments.

**Comment by suyograo** [comment]
Merged an published all but mongo
