### ISSUE TITLE
Logstash document improvements

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3417]
Meta issue to track improvements to Logstash [reference docs](https://www.elastic.co/guide/en/logstash/current/index.html)

- [x] Add deployment guide section for Logstash https://github.com/elastic/logstash/issues/3416
https://github.com/elastic/logstash/issues/3410
- [x] Improve getting started docs/tutorial https://github.com/elastic/logstash/issues/3414
- [x] Organize plugin documentation better https://github.com/elastic/logstash/issues/3418
- [x] Add glossary of Logstash terms
- [x] Add section for handling multiline logs #3659 
- [x] Consistency pass over plugin reference docs across 1.5 and 1.4 https://github.com/elastic/logstash/issues/3413
- [x] Upgrading Logstash
- [x] Add xref for LS input plugins to ES integrations page

**Comment by jother2** [comment]
Please add a section explaining the upgrade process with steps

**Comment by suyograo** [comment]
@jother2 thx for the feedback..to be specific, which upgrade process do you need documentation on?

**Comment by kurtado** [comment]
I have an asciidoc glossary which I wrote a while back... LMK if you'd like to scope that in, or treat separately, or ignore completely :)

**Comment by suyograo** [comment]
@kurtado for sure. Would be great to have a glossary. I'll add it here

**Comment by palecur** [comment]
https://github.com/elastic/elasticsearch/pull/13446 is up to handle Logstash integrations, please have a look.
