### ISSUE TITLE
Roadmap for v1.6.0

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3604]
Meta issue to cover the release-defining enhancements for v1.6. This does not include bug fixes

- [ ] Stalled outputs will prevent proper shutdown #3451 
- [ ] Operational concern: Offline plugin installation #2376 
- [ ] Event class rewrite
- [ ] Use better defaults for workers/pools/buffers #1512

For all issues currently targeted to 1.6.0, see [here](https://github.com/elastic/logstash/issues?q=is%3Aopen+label%3Av1.6.0+is%3Aissue)

**Comment by suyograo** [comment]
1.6.0 was canceled. See explanation in https://www.elastic.co/blog/logstash-2-0-0-beta1-released
