### ISSUE TITLE
release 1.5.4 and 1.4.5

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3680]
- [x] PR update lock
- [x] PR update the changelog
- [x] Release RC1 gem
- [x] Create RC1 package
- [x] Smoke test
- [x] remove RC tag official release
- [x] Official package
- [x] Create blog post
- [x] Update discuss
- [x] tweet
