### ISSUE TITLE
Plugins without tests

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3740]
Hi,
  there are a bunch of plugins without no test at all, this is a situation that should be amended soon. If you are getting test to any of this plugin feel free to update this issue.

If you don't know how to start tracking test, please don't hesitate to ask, we're more than willing to help. This would be also a good starting point to start contributing to logstash.
### Plugin list
- [x] logstash-codec-dots **merged**
- [x] logstash-codec-fluent **merged**
- [x] logstash-filter-sleep **merged**
- [x] logstash-filter-syslog_pri **merged**
- [x] logstash-filter-uuid **merged**
- [x] logstash-input-eventlog (windows expert for this, @gmoskovicz @jsvd @ph ? )
- [x] logstash-input-ganglia **merged**
- [x] logstash-input-graphite **merged**
- [x] logstash-input-irc **merged**
- [x] logstash-input-rabbitmq **merged**
- [X] logstash-input-sqs **merged**
- [x] logstash-input-udp **merged**
- [x] logstash-input-unix  **merged**
- [x] logstash-input-zeromq **merged**
- [x] logstash-output-ganglia **merged**
- [x] logstash-output-gelf **merged**
- [x] logstash-output-hipchat **merged**
- [x] logstash-output-http **merged**
- [x] logstash-output-irc **merged** 
- [x] logstash-output-lumberjack **merged**
- [x] logstash-output-nagios **merged**
- [x] logstash-output-nagios_nsca **merged**
- [x] logstash-output-null **merged**
- [x] logstash-output-pagerduty **merged**
- [x] logstash-output-pipe **merged**
- [ ] logstash-output-sqs (ph on it, will be done in a v2 update.)
- [x] logstash-output-stdout **merged**
- [ ] logstash-output-tcp (@ph on it)
- [x] logstash-output-udp **merged**
- [ ] logstash-output-zeromq

Happy testing.

**Comment by purbon** [comment]
@suyograo @guyboertje reviews and or help here more than welcome! :P

**Comment by purbon** [comment]
Reviews on the plugins who just got test would be super nice, specially to the ganglia one as it has been broken since the 1.5 release. @suyograo

**Comment by kureus** [comment]
Hey @suyograo. How come this issue was closed when there are still plugins missing tests?
