### ISSUE TITLE
Plugin manager refactoring and internal cleanups

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3821]
This issue tries to sum up the different issues regarding plugin refactoring, internal cleanups  the current open tasks/issues are:

* [ ] Plugin install --development should be sticky #2631 
* [ ] refactor of pluginmanager/utils.rb #3746 
* [ ] Upgrade validation of validate_major_version #3744 #3818 
* [ ] Logging in the plugin manager #3656 #2627
* [ ] Lock file to prevent concurrent access to the Gemfile #2622
* [ ] Only install logstash plugins with the plugin manager #2047
