### ISSUE TITLE
Documentation needs for LS 2.0

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#3845]
Tracking the documentation needs for LS 2.0 launch.

* [x] Breaking changes for LS 2.0
* [x] New API for shutdown
* [x] Upgrade instructions 
* [x] Doc dependency changes https://github.com/elastic/logstash/issues/3911
