### ISSUE TITLE
Remove deprecated options in plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3858]
Something to consider for a major release. Here is the list of deprecated options in plugins as of August 27th, 2015:

* [x] logstash-output-email => deprecated option already removed on master
* [x] logstash-input-xmpp => https://github.com/logstash-plugins/logstash-input-xmpp/issues/8
* [x] logstash-input-redis => https://github.com/logstash-plugins/logstash-input-redis/issues/44
* [x]  logstash-output-redis => https://github.com/logstash-plugins/logstash-output-redis/issues/34
* [x] logstash-output-gelf => https://github.com/logstash-plugins/logstash-output-gelf/issues/17
* [x] logstash-input-lumberjack => https://github.com/logstash-plugins/logstash-input-lumberjack/issues/75
* [x] logstash-output-lumberjack => https://github.com/logstash-plugins/logstash-output-lumberjack/issues/20
* [x] logstash-output-graphite => https://github.com/logstash-plugins/logstash-output-graphite/issues/29
* [x] logstash-output-opentsdb => https://github.com/logstash-plugins/logstash-output-opentsdb/issues/5
* [x] logstash-output-statsd => https://github.com/logstash-plugins/logstash-output-statsd/issues/23
* [x] logstash-output-syslog => https://github.com/logstash-plugins/logstash-output-syslog/issues/31
* [x] /logstash-output-tcp => https://github.com/logstash-plugins/logstash-output-tcp/issues/17
* [x] logstash-output-http => https://github.com/logstash-plugins/logstash-output-http/issues/40
* [x] logstash-input-exec => https://github.com/logstash-plugins/logstash-input-exec/issues/9
* [x] logstash-output-s3 => https://github.com/logstash-plugins/logstash-output-s3/issues/83
* [x] logstash-input-s3 => https://github.com/logstash-plugins/logstash-input-s3/issues/83
* [x] logstash-filter-mutate=>  https://github.com/logstash-plugins/logstash-filter-mutate/issues/75
* [x] logstash-filter-grok => https://github.com/logstash-plugins/logstash-filter-grok/issues/84
* [ ] logstash-input-rabbitmq =>
* [ ] logstash-output-rabbitmq =>
* [ ] logstash-output-elasticsearch =>

**Comment by wiibaa** [comment]
@suyograo now that the plugins use different branches for 2.x and 5.0 with the change to event API, can this cleanup be started on master branches ?

**Comment by suyograo** [comment]
Absolutely. This should definitely be done for 5.0 timeframe.

**Comment by wiibaa** [comment]
@suyograo Here are a first chunk of PRs :gift:  
Please note travis build is failing due to https://github.com/elastic/logstash/issues/5361

About your mention of major version, I will make a second round to change the gemspec / changelog

**Comment by suyograo** [comment]
@wiibaa you are the boss! thanks so much man... I will split the work with you as well.. I turned this into a meta issue with check boxes :)

**Comment by wiibaa** [comment]
Correction of version, raising minor instead of major:

* [x] logstash-input-xmpp
* [ ]  logstash-output-redis#34
* [ ] logstash-output-gelf#17
* [ ] logstash-input-lumberjack#75
* [ ] logstash-output-lumberjack#20
* [ ] logstash-output-graphite#29
* [ ] logstash-output-opentsdb#5
* [ ] logstash-output-statsd#23
* [ ] logstash-output-syslog#31
* [ ] /logstash-output-tcp#17
* [ ] logstash-output-http#40
* [ ] logstash-input-exec#9
* [ ] logstash-output-s3#83
* [ ] logstash-input-s3#83

**Comment by wiibaa** [comment]
@suyograo can you please put this checklist as the main description

* [x] logstash-output-email => deprecated option already removed on master
* [ ] logstash-input-xmpp => https://github.com/logstash-plugins/logstash-input-xmpp/issues/8
* [ ] logstash-input-redis => https://github.com/logstash-plugins/logstash-input-redis/issues/44
* [ ]  logstash-output-redis => https://github.com/logstash-plugins/logstash-output-redis/issues/34
* [ ] logstash-output-gelf => https://github.com/logstash-plugins/logstash-output-gelf/issues/17
* [ ] logstash-input-lumberjack => https://github.com/logstash-plugins/logstash-input-lumberjack/issues/75
* [ ] logstash-output-lumberjack => https://github.com/logstash-plugins/logstash-output-lumberjack/issues/20
* [ ] logstash-output-graphite => https://github.com/logstash-plugins/logstash-output-graphite/issues/29
* [ ] logstash-output-opentsdb => https://github.com/logstash-plugins/logstash-output-opentsdb/issues/5
* [ ] logstash-output-statsd => https://github.com/logstash-plugins/logstash-output-statsd/issues/23
* [ ] logstash-output-syslog => https://github.com/logstash-plugins/logstash-output-syslog/issues/31
* [ ] /logstash-output-tcp => https://github.com/logstash-plugins/logstash-output-tcp/issues/17
* [ ] logstash-output-http => https://github.com/logstash-plugins/logstash-output-http/issues/40
* [ ] logstash-input-exec => https://github.com/logstash-plugins/logstash-input-exec/issues/9
* [ ] logstash-output-s3 => https://github.com/logstash-plugins/logstash-output-s3/issues/83
* [ ] logstash-input-s3 => https://github.com/logstash-plugins/logstash-input-s3/issues/83
* [ ] logstash-filter-mutate=>  https://github.com/logstash-plugins/logstash-filter-mutate/issues/75
* [ ] logstash-filter-grok => https://github.com/logstash-plugins/logstash-filter-grok/issues/84
* [ ] logstash-input-rabbitmq =>
* [ ] logstash-output-rabbitmq =>
* [ ] logstash-output-elasticsearch =>

**Comment by suyograo** [comment]
@wiibaa Done. removed your comment with items because it will be confusing.

**Comment by wiibaa** [comment]
@jordansissel So the point is to keep a small section in the plugin with the obsolete config. Make sense. Just curious about how long should we keep obsolete config ? forever, x months ?
@suyograo can you clear the checklist for this additional phase ?

**Comment by suyograo** [comment]
Closing this for now since all the items here were merged
