### ISSUE TITLE
Expose metrics in Logstash pipeline

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3908]
See functional requirements here: https://github.com/elastic/logstash/issues/2611. This issue is mostly for tracking sub-tasks for implementation.

Currently in Logstash there is no way to easily collect metrics from a runnings instance, lets define our needs, do we need to build a custom solution or we can leverage existing code. We have to keep in mind that we are currently rewriting important parts of the pipeline in pure java to leverage more speed from the JVM, so we need to have an hybrid solution that will grow and adapt with the code base.

## Phase1: Use cases of metrics collection in the current system.
We want to collect metrics from different part of the system, I think we should try to have a low level library usable in both scenario, we can provide helpers method via metaprogramming hiding away the complexity of the data collection, this would allow us to turn on of off stats collecting for some part of the code.

- From the pipeline itself
  - In/out of the queues
  - In/out of the filter method of different plugins
  - Metrics from conditionals branching (detecting slow part)
- From the plugins
  - Webservice latencies
  - heavy computations (grok)
  - retries count
  - Error count
  - Internal Buffering (like multilines filter, lumberjack output and elasticsearch output)
  - custom metrics defined by plugins authors
- From the event itself?

#### Metrics framework in core:

- [x] #3898 - Reporting Metrics to external services
- [x] #3897 - Provide a common interface for collecting metrics in pipeline
- [x] #3894 - Plugin specific metric collection framework (no conditionals for now)
- [x] #3901 - Add support for multiples pipelines
- [x] #3892 - Add a unique ID on every plugin and allow user to override it.
- [x] #3900 - Every Logstash node or instance should have their own unique id
- [x] #4461 - Internal: Filter metrics by namespaces
- [ ] #4549 - Add hidden flag for a pipeline
- [x] #4542 - Delete metrics when pipeline is stopped
- [ ] #4536 - Make the pipeline retrieve the node nae.
- [ ] #4506 - Add guards for the metric store
- [x] #4529 - Hide the implementations details for the metric store
- [x] #4503 - Collect plugin metrics by default

#### Exposing metrics through REST API
- [x] https://github.com/elastic/logstash/issues/4446 Design: Metrics API endpoints for Logstash
- [x] #3909 - API: Hot Threads information
- [x] #3802 - Evaluate framework or routing strategy for the API endpoints
- [x] #3801 - Evaluate how we are exposing the api endpoints
- [ ] #3799 - API: The pipeline should return the current active plugins
- [ ] #4575 - Implement basic logging
- [ ] #4576 - Add an option to output access and error logging.
- [x] #4574 - Locate logstash-core/lib/api inside  logstash-core/lib/logstash/api
- [ ] #4464 - Add runtime documentation (aka map) for the metric api.

#### Integration tests for metrics
- [ ] #4573 - Add integration test for the metrics collection when dealing with backpressure in the shipping pipeline 

#### Benchmarking

- [x] #4572 - Benchmarking the new metrics feature.

**Comment by elvarb** [comment]
These config options are valuable to know of, expecially if you are trying to run two or more instances of logstash on the same machine :)
 --http-host WEB_API_HTTP_HOST Web API binding host (default: "127.0.0.1")
 --http-port WEB_API_HTTP_PORT Web API http port (default: 9600)

**Comment by suyograo** [comment]
Closing this since we shipped v1 of metrics in alpha1. We'll move the remaining issues to another meta issue
