### ISSUE TITLE
Default plugins test failures on master/2.0

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3997]
Failure on Jenkins: http://build-eu-00.elastic.co/view/LS%202.0/job/Logstash_Default_Plugins_20/296/console

Reasons for failure:
- [x]  .lock file needs to be updated
- [x] several plugins override "input" logstash_helper using RSpec.configure.include which breaks all other plugins that use it: ganglia, irc, relp, udp, zeromq
- [x] logstash-input-exec has a utf-8 encoding issue: fixed with https://github.com/logstash-plugins/logstash-input-exec/pull/5
- [x] logstash-filter-uuid tests are not passing http://build-eu-00.elastic.co/job/logstash-plugin-filter-uuid-unit/7/jdk=JDK7,nodes=metal-pool/console
- [x] enabling abort_on_exception breaks logstash-input-log4j test suite
- [x] enabling abort_on_exception breaks logstash-input-unix test suite
- [x] eventlog spec suite should only run on windows
- [x] graphite input tests are failing https://github.com/elastic/logstash/issues/4018
- [x] logstash-input-exec fails randomly https://github.com/logstash-plugins/logstash-input-exec/issues/6
- [x] logstash-input-log4j fails randomly https://github.com/logstash-plugins/logstash-input-log4j/issues/22
- [x] logstash-input-unix fails randomly https://github.com/logstash-plugins/logstash-input-unix/issues/13
- [x] logstash-output-s3 specs depend on obsolete "tags" https://github.com/logstash-plugins/logstash-output-s3/issues/39
- [x] logstash-output-statsd fails https://github.com/logstash-plugins/logstash-output-statsd/issues/14
- [x] logstash-filter-clone specs depend on obsolete "tags" https://github.com/logstash-plugins/logstash-filter-clone/issues/2

**Comment by purbon** [comment]
Fixed some of the issues of using ```RSpec.configure```, list are in:

* https://github.com/logstash-plugins/logstash-input-ganglia/pull/13
* https://github.com/logstash-plugins/logstash-input-irc/pull/18
* https://github.com/logstash-plugins/logstash-input-udp/pull/15

still missing:

* https://github.com/logstash-plugins/logstash-input-relp
* https://github.com/logstash-plugins/logstash-input-zeromq

__for the relp__ case the change is easy, however encountered some issues when running the test and the client starting before the pipeline, having problems connecting.

__for the zeromq__ case is more complex as this plugins test aim to make use of the configure section, to add ```  config.filter_run_excluding({ :zeromq => true, :integration => true }) ``` the zeromq tag on it.

need to so more work on both to make them work properly.

**Comment by ph** [comment]
The lock file need to be update with the mass update.

**Comment by ph** [comment]
Make sure you merge, update the gem version and publish it.

**Comment by jsvd** [comment]
perfect. I'd suggest holding the lock file update until all this is fixed.

**Comment by purbon** [comment]
Relp work as now been updated in https://github.com/logstash-plugins/logstash-input-relp/pull/12 please enjoy the review :+1:

**Comment by colinsurprenant** [comment]
`RSpec.configure` fixed in input-tcp and input-graphite

**Comment by colinsurprenant** [comment]
input-relp fix is now in logstash-plugins/logstash-input-relp#13

**Comment by ph** [comment]
Fixed for s3 output is in https://github.com/logstash-plugins/logstash-output-s3/pull/41

**Comment by colinsurprenant** [comment]
input graphite solved.

**Comment by jsvd** [comment]
![screen shot 2015-10-14 at 15 03 00](https://cloud.githubusercontent.com/assets/31809/10485967/b53ff8ca-7284-11e5-8f4d-e857cd49927b.png)
