### ISSUE TITLE
Handling Logstash offline plugin installs

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4086]
- [x] Core Logstash distribution with all latest plugins installed, shipped at a regular minor release cadence
- [x] Option to install plugins on an offline box from a local Rubygems mirror
- [x] Option to install plugins on an offline box from an online Logstash staging instance

**Comment by purbon** [comment]
related to #3583 #3404 #3571 #3424 #2376

**Comment by purbon** [comment]
https://github.com/elastic/logstash/pull/3404 fot merged.

**Comment by acchen97** [comment]
Done.
