### ISSUE TITLE
Logstash Plugin Doc Improvements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4134]
- [ ] New "Logstash Plugins" parent section, restructure under here anything related to plugins
- [x] Migrating plugins from links into table structure https://github.com/elastic/logstash/issues/3418
- [x] Contributing a patch section
- [x] Submitting your Logstash plugins section

**Comment by suyograo** [comment]
Bumping this to 2.3
