### ISSUE TITLE
Logstash docs enhancements for 2.1

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4137]
- [ ] [Logstash Plugin Doc Improvements](https://github.com/elastic/logstash/issues/4134)
- [x] LSF -> Filebeat doc [changes](https://github.com/elastic/logstash/issues/4168)
- [x] [Offline plugin documentation](https://github.com/elastic/logstash/issues/4086) - Pere + Paul
- [x] Shutdown semantics doc update - Joao
- [x] [Command flag changes, verbose config-test](https://github.com/elastic/logstash/issues/3243) - done
- [x] [Multiline doc changes](https://github.com/elastic/logstash/issues/4185) - Guy+PH

**Comment by untergeek** [comment]
@acchen97 you can now do verbose config-test, with output like this: https://gist.github.com/untergeek/e31bedbe5b34f21d1cba

Note the command line in the gist. It does require the `--debug` flag in conjunction with `--configtest`

**Comment by acchen97** [comment]
@untergeek awesome! we should document this - command-line flags docs?

**Comment by untergeek** [comment]
As far as command-line docs go, just add to the current `--configtest` documentation.  Making this known in a blog, or release will likely suffice beyond that.

**Comment by palecur** [comment]
PR #4223 is up to addres LFS>Filebeat.

**Comment by palecur** [comment]
PR #4230 is up to address Offline Plugins.

**Comment by palecur** [comment]
PR #4255 is up to incorporate new shutdown stall detection, release notes.
