### ISSUE TITLE
[meta] plugins specs fixes tracking for logstash-core-event-java

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4264]
As I work on having all the plugins specs pass using logstash-core-event-java I will update this tracking list of the related issues/PRs. relates to #4191

- [x] filter-grok in logstash-plugins/logstash-filter-grok#62 and #4265
- [x] input-sqs in #4278
- [x] codec-edn #4279
- [x] filter-geoip logstash-plugins/logstash-filter-geoip#56
- [x] filter-kv  logstash-plugins/logstash-filter-kv#20 ogstash-plugins/logstash-filter-kv#21
- [x] filter-mutate logstash-plugins/logstash-filter-mutate#59 logstash-plugins/logstash-filter-mutate#61 #4279
- [x] filter-json logstash-plugins/logstash-filter-json#18
- [x] filter-xml logstash-plugins/logstash-filter-xml#21
- [x] filter-ruby logstash-plugins/logstash-filter-ruby#15
- [x] filter-csv logstash-plugins/logstash-filter-csv#20
- [x] output-file logstash-plugins/logstash-output-file#23
- [x] filter-useragent logstash-plugins/logstash-filter-useragent#20
- [x] output-graphite logstash-plugins/logstash-output-graphite#20
- [x] codec-json_lines logstash-plugins/logstash-codec-json_lines#12
- [x] input-elasticsearch logstash-plugins/logstash-input-elasticsearch#35
- [x] codec-netflow logstash-plugins/logstash-codec-netflow#29
- [x] filter-date logstash-plugins/logstash-filter-date#45
- [x] input-imap logstash-plugins/logstash-input-imap#11

and also but not specific to Java Event

- [x] codec-rubydebug see logstash-plugins/logstash-codec-rubydebug#8

**Comment by jsvd** [comment]
Can you also open issues for the plugins that are failing but don't have a PR yet?

**Comment by colinsurprenant** [comment]
as of now, these are the remaining failures:

```
Finished in 1 minute 37.3 seconds (files took 9.64 seconds to load)
889 examples, 14 failures

Failed examples:

rspec ./vendor/bundle/jruby/1.9/gems/logstash-filter-useragent-2.0.3/spec/filters/useragent_spec.rb:101 # LogStash::Filters::UserAgent Replace source with target "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.31 (K..." when processed
rspec ./vendor/bundle/jruby/1.9/gems/logstash-filter-useragent-2.0.3/spec/filters/useragent_spec.rb:18 # LogStash::Filters::UserAgent defaults "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.31 (K..." when processed
rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-imap-2.0.2/spec/inputs/imap_spec.rb:108 # LogStash::Inputs::IMAP with multiple values for same header should add more than 2 values as array in event
rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-2.0.2/spec/inputs/elasticsearch_spec.rb:251 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document information to the specified field
rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-2.0.2/spec/inputs/elasticsearch_spec.rb:272 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should allow to specify which fields from the document info to save to the @metadata field
rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-2.0.2/spec/inputs/elasticsearch_spec.rb:192 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo merges the values if the `docinfo_target` already exist in the `_source` document
rspec ./vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-2.0.2/spec/inputs/elasticsearch_spec.rb:241 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document info to the @metadata field
rspec ./vendor/bundle/jruby/1.9/gems/logstash-output-graphite-2.0.2/spec/outputs/graphite_spec.rb:40 # LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match one key should generate one element
rspec ./vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/spec/codecs/json_lines_spec.rb:89 # LogStash::Codecs::JSONLines#encode should return json data
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-codec-rubydebug/spec/codecs/rubydebug_spec.rb:24 # LogStash::Codecs::RubyDebug#decode should not be implemented
rspec ./vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/spec/codecs/netflow_spec.rb:203 # LogStash::Codecs::Netflow Netflow 9 should serialize to json
rspec ./vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/spec/codecs/netflow_spec.rb:116 # LogStash::Codecs::Netflow Netflow 5 should serialize to json
rspec ./vendor/bundle/jruby/1.9/gems/logstash-filter-date-2.0.2/spec/filters/date_spec.rb:330 # LogStash::Filters::Date failing to parse should apply tag_on_failure "{"thedate":"2013/Apr/21"}" when processed
rspec ./vendor/bundle/jruby/1.9/gems/logstash-filter-date-2.0.2/spec/filters/date_spec.rb:370 # LogStash::Filters::Date LOGSTASH-34 - Default year should be this year "Sun Jun 02 20:38:03" when processed

Randomized with seed 34052
```

**Comment by colinsurprenant** [comment]
done useragent

**Comment by colinsurprenant** [comment]
ALL DONE!! default plugins are all passing :beers:

**Comment by colinsurprenant** [comment]
did a pass of merge and versions push. the remaining PRs need to be reviewed /cc @guyboertje

**Comment by colinsurprenant** [comment]
woa! DONE!

**Comment by colinsurprenant** [comment]
all good! closing!
