### ISSUE TITLE
[meta] failing plugins specs under master

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4371]
Here's the survey of the currently failing specs under master at 066e778f63109d9fde2b4f00a70a68106ebe0204

#### devutils pipeline mocking
- [x] https://github.com/elastic/logstash-devutils/issues/42

#### bad in-specs pipeline mocking
- [x] https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/37
- [x] https://github.com/logstash-plugins/logstash-input-file/issues/86
- [x] https://github.com/logstash-plugins/logstash-input-pipe/issues/12
- [x] https://github.com/logstash-plugins/logstash-input-gelf/issues/31
- [x] https://github.com/logstash-plugins/logstash-input-ganglia/issues/15
- [x] https://github.com/logstash-plugins/logstash-input-generator/issues/12
- [x] https://github.com/logstash-plugins/logstash-input-tcp/issues/36

#### out-of-order batches?
- [x] https://github.com/logstash-plugins/logstash-output-file/issues/25

## unknown origin

I suspect this are actually related to https://github.com/elastic/logstash-devutils/issues/42

#### hanging specs
- [x] https://github.com/logstash-plugins/logstash-input-tcp/issues/37
- [x] https://github.com/logstash-plugins/logstash-input-syslog/issues/24

## other
- [x] https://github.com/logstash-plugins/logstash-codec-rubydebug/issues/8
- [x] https://github.com/logstash-plugins/logstash-input-log4j/issues/27

## solutions
- [x] short term fix proposal in #4373
- [ ] real refactor required in #4382

**Comment by colinsurprenant** [comment]
I just added the devutils pipeline mocking problems issue.

**Comment by colinsurprenant** [comment]
proposed short-term fix by @andrewvc https://github.com/elastic/logstash/pull/4373

**Comment by colinsurprenant** [comment]
real "long-term" refactor required in #4382

**Comment by colinsurprenant** [comment]
#4384 solves most issues. updated the description tasks.

**Comment by colinsurprenant** [comment]
added https://github.com/logstash-plugins/logstash-input-log4j/issues/27 can either @andrewvc or @jsvd  take a look? not sure if related to changes introduced by your last pipeline modifications

**Comment by colinsurprenant** [comment]
log4j fixed by https://github.com/logstash-plugins/logstash-input-log4j/pull/28  thanks @andrewvc

**Comment by ph** [comment]
@colin Where is this list coming from a local run of a Jenkins task?
This list is different from http://build-eu-00.elasticsearch.org/view/LS%20Master/job/Logstash_Master_Default_Plugins/899/console

**Comment by ph** [comment]
I have fixed the other issues found from running this [job](http://build-eu-00.elasticsearch.org/view/LS%20Master/job/Logstash_Master_Default_Plugins/899/console)

https://github.com/logstash-plugins/logstash-filter-date/pull/53
https://github.com/logstash-plugins/logstash-output-s3/pull/64

**Comment by jsvd** [comment]
pr for the rubydebug issue https://github.com/logstash-plugins/logstash-codec-rubydebug/pull/9

**Comment by jordansissel** [comment]
Looks like most of the items in this check list are now checked. Is it OK to close any tickets that are marked w/ a check here?

**Comment by colinsurprenant** [comment]
this is all done now for the exception of #4382 which will be dealt with eventually.  closing.
