### ISSUE TITLE
Logstash Plugin Docs Enhancements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4469]
**Phase 1**
- [ ] **Show plugin versions explicitly**
  - Logstash x.x - show version/doc bundled with the release
  - Logstash master - show all latest versions/docs, periodic update

- [ ] **Show Logstash core version compatibility for each plugin page based on version**

- [ ] **Plugin banner enhancements** - clearly display bundled plugins and community plugins.  Basically two categories:
  - Non-community plugin and not bundled with core (Note community + how to update)
  - Community plugin not bundled with core (Note how to update)

**Future**
- [ ] **Easy navigation between plugin versions** - i.e. version in URL resource

- [x] **New Plugin List Structure for Docs** - for our plugin docs, we’re implementing a new table structure with the below columns:

- *Plugin Name* [Done]
- *Description* [Done]
- *Github Link* [Done]
- Total Downloads
- For Logstash master:
  - Latest Version
  - Latest Version Downloads
- For Logstash x.x:
  - For plugins bundled in core:
    - Bundled Version
    - Bundled Version Downloads
  - For plugins NOT bundled in core:
    - Latest Version
    - Latest Version Downloads

**Comment by acchen97** [comment]
Closed in favor of https://github.com/elastic/logstash/issues/5148
