### ISSUE TITLE
default to logstash-core-event-java implementation

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4480]
switch to use the core Java Event implementation by default. 

For this we need to complete the following:
- [x] jar-dependencies cleanups in logstash-core-event-java #4176 
- [x] add logstash-core-event-java specific build requirements in the build rake tasks #4479
- [x] default to java event and dependencies cleanups #4494

**Comment by colinsurprenant** [comment]
all these are solved by #4494

**Comment by colinsurprenant** [comment]
merging the result of #4563 in master and closing this issue. Starting from this merge master will default to Java Event and jenkins will be able to run tests in preparation for 2.3.
