### ISSUE TITLE
Support Elastic packs

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4872]
## Intro
Starting in 5.0, we want to align the plugin managers across the Elastic stack. This has (at least) two goals - having a consistent syntax and behavior for installing extensions (plugins) across the Elastic Stack, and to introduce the concept of "Packs" - a single zip that contains 0 or 1 plugin for each system.

## Packs 
Packs is more than just a plugin for a specific system, and extends the whole stack, rather than making a single extension for a single system. A pack is a zip that contains 0 or 1 plugins for each of Elasticsearch, Logstash, Kibana. Since LS uses RubyGems to host plugins, and is heavily based on gem infrastructure, we'll continue to support RubyGems and existing plugins in addition to new packs.

## Consistency with Kibana and Elasticsearch products
This behavior will make it consistent with [Elasticsearch](https://github.com/elastic/elasticsearch/pull/16454) and [Kibana](https://github.com/elastic/kibana/pull/6252).

This is a meta issue to achieve the goal - install a pack from shared resource

--------------------------------------------------------------------------------------

- [x] Deprecate `bin/plugin` in 2.3.0 (#4891)
- [x] Create bin/logstash-plugin to replace bin/plugin (https://github.com/elastic/logstash/issues/4871)
- [ ] Plugin Manager: Extend functionality to installation plugin packs  (https://github.com/elastic/logstash/issues/4585)
