### ISSUE TITLE
[meta] 2.3.1, 2.2.4 release problems tracking

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4981]
This is a tracking issue for the identified problems in 2.3 and the planing for the upcoming 2.3.1.

- [x] #4996 Test failling on the 2.3 branch.
- [x] #4952 password leak in shutdown stall 2.3/2.2
- [x] #5001 config leak on output delegator close (5.0,2.3,2.2)
- [x] #4965 password leak in debug mode
  - [x] #4987 2.3 backport of #4965 (password leak in debug mode)
  - [x] #5000 2.2 backport of #4965
- [x] #4970 conditionals with pipeline reload
- [x] #4946 config-test broken
  - [x] merge in 2.3 #4944
- [x] #4963 env var in config
  - [x] merge in 2.3 #5003 
- [x] #4977 jruby regex thread safety regression
  - [x] review #4995
- [x] document/blog on ruby filter fields mutability change per logstash-plugins/logstash-filter-ruby/issues/21
- [x] changelog
 - [x] review #4994  2.3.1
 - [x] review #4981 2.2.4
- [x] #4992 package (init.d) stop function broken for ubuntu
- [x] https://github.com/logstash-plugins/logstash-filter-useragent/pull/27 Remove now useless mutex around UserAgent regexp
- [x] #5027 Ensure docs around ruby event rollback are accurate
- [x] #5023 Revert to ruby event 
  - [x] #5024 Fix big decimal 
- [x] #5034 Document the new '--allow-env' flag

**Comment by ph** [comment]
The only things missing is the https://github.com/elastic/logstash/pull/5000 for the 2.2.4, something broke that branch and it need investigation.

**Comment by andrewvc** [comment]
Released today!
