### ISSUE TITLE
[meta] Event API refactor

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5140]
This is a tracking issue related to the Event API refactor which will **break compatibility** for the 5.0 release. 

Historically it was assumed that the returned values from the Ruby Event hash-like interface or the `Event#to_hash` method were returning references to the Event inner data and that modifying these references in turn also update the Event inner data. 

Moving forward, this is an implementation specific side-effect that we will not support. To help in avoiding the confusion that the Ruby hash-like interface provides and also to force a breaking change in the API we have decided to completely remove the Ruby hash-like interface and instead expose proper getters and setters.

The direct consequence is that all unmodified plugins and Ruby filters are likely to crash and we believe this is better than having Ruby filters or plugins that will silently stop to work correctly.

#### Required Modifications

- [x] remove Ruby hash-like API and expose new getter and setter using fieldref arguements, #5141 #5227
- [ ] add ~~~Event#from_hash~~~ and Event#merge_hash, #4326

#### Optional Modifications

- [ ] ~~~add Event#message and Event#message=~~~, #4327
- [ ] add new Event#mutate or similar as suggested in #5121

**Comment by suyograo** [comment]
Focusing on #5141 for now
