### ISSUE TITLE
[meta] defaults plugins migration to new Event interface and plugin-api 2.0

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5227]
This is a meta issue to track progress for refactoring the defaults plugins. Core plugins migration has been completed per #5170. Related #5140.

This migration recipe goals are:
- avoid publishing any core plugins for the refactor
- be able to test refactored plugins within their refactor branch in Travis
- be able to test/build logstash using the refactored plugins within their branches

### Plugin Migration Recipe

- create branch `feature/plugin-api-2_0`
- this branch should be published upstream in the `logstash-plugins` repo.
- `.travis.yml` should be updated to

 ```
 sudo: false
 jdk:
   - oraclejdk8
 language: ruby
 cache: bundler
 rvm:
   - jruby-1.7.25
 before_install:
   - git clone -b feature/event_interface https://github.com/elastic/logstash
 script:
   - bundle exec rspec spec
 ```
- minimally these gems need to be added to the plugin `Gemfile`

 ```
 # this is temporary for the feature/plugin-api-2_0 branch and is meant for travis testing
 gem "logstash-core", :path => "./logstash/logstash-core"
 gem "logstash-core-plugin-api", :path => "./logstash/logstash-core-plugin-api"
 gem "logstash-core-event-java", :path => "./logstash/logstash-core-event-java"
 gem "logstash-devutils", :github => "elastic/logstash-devutils", :branch => "feature/plugin-api-2_0"
 ```
- add any other plugins in the gemspec required by this plugin, for example, if `logstash-codec-plain` is a required plugin add this:

 ```
 gem "logstash-codec-plain", :github => "logstash-plugins/logstash-codec-plain", :branch => "feature/plugin-api-2_0"
```
- modify the gemspec to bump the plugin-api version constrain to 2.0:

 ```
 s.add_runtime_dependency "logstash-core-plugin-api", "~> 2.0"
 ```
- and finally, refactor code and specs for new Event interface

### Running local specs

- if you want to test locally you will have to create a symbolic link to the logstash code base with the `feature/event_interface` shared branch

 ```
 ln -s /you/path/to/logstash .
 bundle
 bundle exec rspec spec
 ```

### Helpful Scripts
@ph has added this ruby script to automate much of the initial work: https://gist.github.com/e28dddccfbe32c3985ab51d6f9b9ec41

### Plugins for core specs
- [x] https://github.com/elastic/logstash-devutils/pull/46
- [x] https://github.com/logstash-plugins/logstash-filter-clone/pull/9 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-clone.svg?branch=feature/plugin-api-2_0)
- [x] https://github.com/logstash-plugins/logstash-patterns-core/pull/149  | ![travis](https://travis-ci.org/logstash-plugins/logstash-patterns-core.svg?branch=feature/plugin-api-2_0)
- [x] https://github.com/logstash-plugins/logstash-filter-grok/pull/81 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-grok.svg?branch=feature/plugin-api-2_0)
- [x] https://github.com/logstash-plugins/logstash-filter-mutate/pull/72 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-mutate.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-filter-multiline/pull/27 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-multiline.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-codec-plain/pull/2 | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-plain.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-input-generator/pull/13 | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-generator.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-codec-line/pull/9 | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-line.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-codec-json/pull/27 | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-json.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-codec-json_lines/pull/26 | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-lines.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-input-stdin/pull/10 | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-stdin.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-input-tcp/pull/52 | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-tcp.svg?branch=feature/plugin-api-2_0) 
- [x] https://github.com/logstash-plugins/logstash-output-stdout/pull/8 | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-stdout.svg?branch=feature/plugin-api-2_0) 

- [x] [logstash-input-heartbeat](https://github.com/logstash-plugins/logstash-input-heartbeat) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-heartbeat.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-output-zeromq](https://github.com/logstash-plugins/logstash-output-zeromq) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-zeromq.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-collectd](https://github.com/logstash-plugins/logstash-codec-collectd) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-collectd.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-output-xmpp](https://github.com/logstash-plugins/logstash-output-xmpp) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-xmpp.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-dots](https://github.com/logstash-plugins/logstash-codec-dots) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-dots.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-edn](https://github.com/logstash-plugins/logstash-codec-edn) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-edn.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-edn_lines](https://github.com/logstash-plugins/logstash-codec-edn_lines) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-edn_lines.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-fluent](https://github.com/logstash-plugins/logstash-codec-fluent) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-fluent.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-es_bulk](https://github.com/logstash-plugins/logstash-codec-es_bulk) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-es_bulk.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-graphite](https://github.com/logstash-plugins/logstash-codec-graphite) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-graphite.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-msgpack](https://github.com/logstash-plugins/logstash-codec-msgpack) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-msgpack.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-multiline](https://github.com/logstash-plugins/logstash-codec-multiline) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-multiline.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-netflow](https://github.com/logstash-plugins/logstash-codec-netflow) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-netflow.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-oldlogstashjson](https://github.com/logstash-plugins/logstash-codec-oldlogstashjson) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-oldlogstashjson.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-codec-rubydebug](https://github.com/logstash-plugins/logstash-codec-rubydebug) | ![travis](https://travis-ci.org/logstash-plugins/logstash-codec-rubydebug.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-anonymize](https://github.com/logstash-plugins/logstash-filter-anonymize) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-anonymize.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-checksum](https://github.com/logstash-plugins/logstash-filter-checksum) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-checksum.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-clone](https://github.com/logstash-plugins/logstash-filter-clone) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-clone.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-csv](https://github.com/logstash-plugins/logstash-filter-csv) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-csv.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-date](https://github.com/logstash-plugins/logstash-filter-date) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-date.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-dns](https://github.com/logstash-plugins/logstash-filter-dns) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-dns.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-drop](https://github.com/logstash-plugins/logstash-filter-drop) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-drop.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-fingerprint](https://github.com/logstash-plugins/logstash-filter-fingerprint) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-fingerprint.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-geoip.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-json](https://github.com/logstash-plugins/logstash-filter-json) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-json.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-kv](https://github.com/logstash-plugins/logstash-filter-kv) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-kv.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-metrics](https://github.com/logstash-plugins/logstash-filter-metrics) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-metrics.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-ruby](https://github.com/logstash-plugins/logstash-filter-ruby) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-ruby.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-sleep](https://github.com/logstash-plugins/logstash-filter-sleep) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-sleep.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-split](https://github.com/logstash-plugins/logstash-filter-split) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-split.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] [logstash-filter-syslog_pri](https://github.com/logstash-plugins/logstash-filter-syslog_pri) | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-syslog_pri.svg?branch=feature/plugin-api-2_0) @suyograo
- [x] https://github.com/logstash-plugins/logstash-filter-throttle/pull/11 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-throttle.svg?branch=feature/plugin-api-2_0) @ph
- [x] https://github.com/logstash-plugins/logstash-filter-urldecode/pull/7 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-urldecode.svg?branch=feature/plugin-api-2_0) @ph
- [x] https://github.com/logstash-plugins/logstash-filter-useragent/pull/29 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-useragent.svg?branch=feature/plugin-api-2_0) @ph
- [x] https://github.com/logstash-plugins/logstash-filter-uuid/pull/5 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-uuid.svg?branch=feature/plugin-api-2_0) @ph
- [x] https://github.com/logstash-plugins/logstash-filter-xml/pull/29 | ![travis](https://travis-ci.org/logstash-plugins/logstash-filter-xml.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-couchdb_changes](https://github.com/logstash-plugins/logstash-input-couchdb_changes) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-couchdb_changes.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-elasticsearch](https://github.com/logstash-plugins/logstash-input-elasticsearch) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-elasticsearch.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-eventlog](https://github.com/logstash-plugins/logstash-input-eventlog) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-eventlog.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-exec](https://github.com/logstash-plugins/logstash-input-exec) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-exec.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-file](https://github.com/logstash-plugins/logstash-input-file) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-file.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-ganglia](https://github.com/logstash-plugins/logstash-input-ganglia) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-ganglia.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-gelf](https://github.com/logstash-plugins/logstash-input-gelf) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-gelf.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-graphite](https://github.com/logstash-plugins/logstash-input-graphite) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-graphite.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-http](https://github.com/logstash-plugins/logstash-input-http) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-http.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-http_poller.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-imap](https://github.com/logstash-plugins/logstash-input-imap) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-imap.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-irc](https://github.com/logstash-plugins/logstash-input-irc) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-irc.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-jdbc](https://github.com/logstash-plugins/logstash-input-jdbc) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-jdbc.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-log4j](https://github.com/logstash-plugins/logstash-input-log4j) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-log4j.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-lumberjack](https://github.com/logstash-plugins/logstash-input-lumberjack) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-lumberjack.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-pipe](https://github.com/logstash-plugins/logstash-input-pipe) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-pipe.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-rabbitmq](https://github.com/logstash-plugins/logstash-input-rabbitmq) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-redis](https://github.com/logstash-plugins/logstash-input-redis) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-redis.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-s3](https://github.com/logstash-plugins/logstash-input-s3) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-s3.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-snmptrap.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-sqs](https://github.com/logstash-plugins/logstash-input-sqs) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-sqs.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-syslog](https://github.com/logstash-plugins/logstash-input-syslog) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-syslog.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-twitter](https://github.com/logstash-plugins/logstash-input-twitter) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-twitter.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-udp](https://github.com/logstash-plugins/logstash-input-udp) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-udp.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-unix](https://github.com/logstash-plugins/logstash-input-unix) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-unix.svg?branch=feature/plugin-api-2_0) @ph
- [x] [logstash-input-xmpp](https://github.com/logstash-plugins/logstash-input-xmpp) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-xmpp.svg?branch=feature/plugin-api-2_0) @guyboertje
- [x] [logstash-input-zeromq](https://github.com/logstash-plugins/logstash-input-zeromq) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-zeromq.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-input-kafka](https://github.com/logstash-plugins/logstash-input-kafka) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-kafka.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats) | ![travis](https://travis-ci.org/logstash-plugins/logstash-input-beats.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-cloudwatch](https://github.com/logstash-plugins/logstash-output-cloudwatch) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-csv](https://github.com/logstash-plugins/logstash-output-csv) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-csv.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-email](https://github.com/logstash-plugins/logstash-output-email) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-email.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-exec](https://github.com/logstash-plugins/logstash-output-exec) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-exec.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-file](https://github.com/logstash-plugins/logstash-output-file) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-file.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-ganglia](https://github.com/logstash-plugins/logstash-output-ganglia) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-ganglia.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-gelf](https://github.com/logstash-plugins/logstash-output-gelf) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-gelf.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-graphite](https://github.com/logstash-plugins/logstash-output-graphite) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-graphite.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-hipchat](https://github.com/logstash-plugins/logstash-output-hipchat) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-hipchat.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-http](https://github.com/logstash-plugins/logstash-output-http) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-http.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-irc](https://github.com/logstash-plugins/logstash-output-irc) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-irc.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-juggernaut](https://github.com/logstash-plugins/logstash-output-juggernaut) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-juggernaut.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-lumberjack](https://github.com/logstash-plugins/logstash-output-lumberjack) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-lumberjack.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-nagios](https://github.com/logstash-plugins/logstash-output-nagios) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-nagios.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-nagios_nsca](https://github.com/logstash-plugins/logstash-output-nagios_nsca) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-nagios_nsca.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-null](https://github.com/logstash-plugins/logstash-output-null) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-null.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-opentsdb](https://github.com/logstash-plugins/logstash-output-opentsdb) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-opentsdb.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-pagerduty](https://github.com/logstash-plugins/logstash-output-pagerduty) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-pagerduty.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-pipe](https://github.com/logstash-plugins/logstash-output-pipe) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-pipe.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-rabbitmq](https://github.com/logstash-plugins/logstash-output-rabbitmq) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-rabbitmq.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-redis](https://github.com/logstash-plugins/logstash-output-redis) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-redis.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-s3](https://github.com/logstash-plugins/logstash-output-s3) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-s3.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-sns](https://github.com/logstash-plugins/logstash-output-sns) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-sns.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-sqs](https://github.com/logstash-plugins/logstash-output-sqs) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-sqs.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-statsd](https://github.com/logstash-plugins/logstash-output-statsd) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-statsd.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-tcp](https://github.com/logstash-plugins/logstash-output-tcp) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-tcp.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-udp](https://github.com/logstash-plugins/logstash-output-udp) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-udp.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-output-kafka](https://github.com/logstash-plugins/logstash-output-kafka) | ![travis](https://travis-ci.org/logstash-plugins/logstash-output-kafka.svg?branch=feature/plugin-api-2_0) @talevy
- [x] [logstash-mixin-aws](https://github.com/logstash-plugins/logstash-mixin-aws) @talevy
- [x] [logstash-mixin-http_client](https://github.com/logstash-plugins/logstash-mixin-http_client/pull/21) |  ![travis](https://travis-ci.org/logstash-plugins/logstash-mixin-http_client.svg?branch=feature/plugin-api-2_0) @ph 
- [x] https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/21 | ![travis](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection.svg?branch=feature/plugin-api-2_0) @ph

**Comment by ph** [comment]
We can automate all of the heavy work minus the actual code/spec?
Are we fine doing that?

**Comment by suyograo** [comment]
@ph +1 for automating..

**Comment by colinsurprenant** [comment]
it might be tricky to automate the addition of dependent plugins from the gemspec but the basic block 
```
# this is temporary for the feature/plugin-api-2_0 branch and is meant for travis testing
gem "logstash-core", :path => "./logstash/logstash-core"
gem "logstash-core-plugin-api", :path => "./logstash/logstash-core-plugin-api"
gem "logstash-core-event-java", :path => "./logstash/logstash-core-event-java"
gem "logstash-devutils", :github => "elastic/logstash-devutils", :branch => "feature/plugin-api-2_0"
```
can be easily automated

**Comment by colinsurprenant** [comment]
also I've seen a bit different `.travis.yml`, with the integration tests flag?

**Comment by suyograo** [comment]
Btw, all plugins should have the integration flag set if its not already there..

**Comment by colinsurprenant** [comment]
I added the list of plugins done so far for passing core specs.

**Comment by ph** [comment]
@suyograo  logstash-codec-oldlogstashjson is marked as completed but I can't find the PR.

**Comment by suyograo** [comment]
Here's the merge plan:

- [ ] merge https://github.com/elastic/logstash/pull/5170 to master and 5.0 after cleaning up temp stuff in there (@colinsurprenant)
- [ ] Generate new lock file for 5.0 and release new 5.0.0-beta1.snapshot1 (@suyograo)
- [ ] Create new branches off master in all plugins repo (@ph)
- [ ] Script merge of `feature/plugin-api-2_0` to master in all plugins (@ph)
- [ ] Revert `.travis.yml` to old state via mass update (@ph)
- [ ] Make sure tests are green for all plugins
- [ ] Bump major version for all default plugins, add CHANGELOG entry, and mass publish (@ph)
- [ ] Generate new lock file for 5.0 and release new 5.0.0-beta2.snapshot1 for testing (@suyograo)

**Comment by colinsurprenant** [comment]
@suyograo 
- the plugins branches off master will be `2.x` ?
- we need to revert both `.travis.yml` and `Gemfile` in mass update
- you mean new `5.0.0-beta1.snapshot2` ?

**Comment by suyograo** [comment]
@colinsurprenant updated.

**Comment by colinsurprenant** [comment]
@suyograo @ph also, `.travis.yml` should not be updated to *old state*, we certainly want to keep the Java 8 selection?

**Comment by colinsurprenant** [comment]
@suyograo @ph `core-api-v1` (not v2) branch for LS 2.x development.

**Comment by ph** [comment]
@colinsurprenant We already have v1, it was before the shutdown change for 1.5?

**Comment by colinsurprenant** [comment]
@ph how is that possible? we only recently introduced the plugin-core-api gem recently
ah yes, ok, I think I remember - it's **core-api**, we  need to create **plugin-api-v1**

**Comment by suyograo** [comment]
@colinsurprenant `core-api-v1` branch already exists and was created to continue development of plugins under v1 core API (pre shutdown changes, < LS 2.0). `core-api-v2` once branched will match v2 of plugin APIs and continue development for them (pre Java Event, < LS 2.0).

Also, here is a `.travis.yml` we can mass update with: https://gist.github.com/suyograo/331f6384e143b147c09db51a854540c4

Includes `Java 8` and `--integration` tags

**Comment by ph** [comment]
> Also, here is a .travis.yml we can mass update with: https://gist.github.com/suyograo/331f6384e143b147c09db51a854540c4

I am not sure we should mass update with the `bundle exec rspec --tag integration`, since `integration` usually mean that we need to add some steps in the travis file to make sure the environment is ready to be used for integration testing. Like installing redis, rabbitmq or supporting libraries. 

But this could be a good way to find which plugins are failling and change their travis.yml manually.

@colinsurprenant @suyograo `core-api-v2` I agree is a weird name, another option would be to make it explicit and rename them logstash-1.5.x and logstash-2.x ;)

**Comment by ph** [comment]
@suyograo After discussing on zoom I am ok to move ahead with the `core-api-v2`, its only a branch name, if we change our mind in the future we can always rename it/them.

@colinsurprenant Can we move forward?

**Comment by colinsurprenant** [comment]
@ph @suyograo it is still confused. 
- core-api-v1 branch was introduced for supporting the pre-shutdown changes for the 1.5 series. At this point we had no notion of plugin-api, we came up with that ad-hoc branch name

- we need a branch to be able to continue to support le LS versions that are using the **plugin-api v1** which are all pre-5.0 releases. if we use the name "v2" in that branch name it will be extremely confusing.

- since we now have a concept of plugin-api formal versioning I think we **need** to use **that** concept to name branches and use corresponding names and versions numbers.

- in that respect, the problem here is the original "core-api-v1" branch name which does not make sense with the new **plugin-api** concept. 

For this I suggest we simply leave the **core-api-v1** branch name as-is, for legacy reasons, which will be not needed anymore, and introduce branches with the **plugin-api** name and versions.

**Comment by suyograo** [comment]
> For this I suggest we simply leave the core-api-v1 branch name as-is, for legacy reasons, which anyway will not be needed anymore, and introduce branches with the plugin-api name and versions.

@colinsurprenant @ph I am fine with naming the branch based on plugin API version. Good with `plugin-api-v1`

**Comment by colinsurprenant** [comment]
@suyograo, @ph and myself just reviewed the tasks sequence and Houston, all engines go!
