### ISSUE TITLE
[meta] Acceptance test framework phase 1

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5340]
TODO list for pending stuff before we decide acceptance test phase 1 is ready to merge to master:

* [x] merge cli test (see https://github.com/elastic/logstash/pull/5259)
* [ ] snapshot/restore fix (worst case restore in favor of install/uninstall and open follow up issue)  (see https://github.com/elastic/logstash/issues/5324 )
* [x] test that  platforms bootstrap. (see #5346)
* [x] merge the ca certificate issue. (fix included in #5346)

**Comment by purbon** [comment]
As tested, all current vms can bootstrap, see:

```bash
purbon@slave-524707:~/logstash/qa$ vagrant status
Current machine states:

centos-6                  running (virtualbox)
centos-7                  running (virtualbox)
debian-8                  running (virtualbox)
fedora-22                 running (virtualbox)
oel-6                     running (virtualbox)
oel-7                     running (virtualbox)
opensuse-13               running (virtualbox)
sles-12                   running (virtualbox)
ubuntu-1204               running (virtualbox)
ubuntu-1404               running (virtualbox)
ubuntu-1504               running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by purbon** [comment]
merged!
