### ISSUE TITLE
2.4 Release Highlights

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5596]
- [x] Backport set/get API shim to support 5.x plugins on 2.4 https://github.com/elastic/logstash/issues/5449
- [x] Backport null metrics to 2.4 to help support 5.x plugins which use metrics API. https://github.com/elastic/logstash/issues/5539
- [x] Internal Logging in JSON format with a flag. https://github.com/elastic/logstash/issues/1569
- [x] Threadsafe ES output which handles resources efficiently.
- [x] Mass update plugins gemspec to use Ruby set/get API https://github.com/elastic/logstash/issues/5496
- [x] Deprecate warning for transport protocol (update performance throughput from latest ES output changes)
- [x] ES output compatibility with both 5.x and 2.x https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/401
- [x] Deprecate `bin/logstash-plugin uninstall` in favor of `remove` to be consistent with the Stack 

Potential Candidate:
- [x] Beats Input Rewrite: https://github.com/logstash-plugins/logstash-input-beats/issues/92
