### ISSUE TITLE
Final touches on monitoring API

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5607]
Final monitoring API bug fixes for beta1 readiness:

- [x] Pipeline stats from `/_node/stats/pipeline` should also be included in the parent `/_node/stats` resource for completeness; verbosity shouldn’t be an issue as this API should be for computers not humans
- [x] `/_node/stats/mem` resource should be removed and the object should instead be nested under `/_node/stats/jvm` along with the ‘thread’ stats
- [x] `/_node/stats/events` object+resource should be removed as these metrics now instead reside under the pipeline stats `/_node/stats/pipeline`
- [x] There is a bug in `/_node/stats/pipeline` where the plugin specific stats should be keyed by “plugins” and not “pipeline"
- [x] Adding input plugin specific stats, like what we have for filters/outputs already
- [x] `/_node/hot_threads?human=true` human option needs to be fixed, currently returns in JSON
- [x] Enabling specification of a comma-separated list of resources https://github.com/elastic/logstash/issues/5609

/cc @jordansissel @suyograo @andrewvc

**Comment by acchen97** [comment]
@purbon thanks for hopping on this. Added one more item at the end here https://github.com/elastic/logstash/issues/5609. Please let me know if it won't fit into beta1. /cc @suyograo

**Comment by purbon** [comment]
Added metrics to tcp input, pending review. see https://github.com/logstash-plugins/logstash-input-tcp/pull/56

**Comment by acchen97** [comment]
> as of now only Adding input plugin specific stats, like what we have for filters/outputs already is missing. investigating working on this.

Cool, this is important to gain monitoring parity across the stages of the pipeline. 👍

**Comment by acchen97** [comment]
This is complete for alpha5, will open a new issue for tracking beta1 readiness.
