### ISSUE TITLE
[meta] first persistence implementation release tracking

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5638]
This issue list and track progress toward the first release of the persistence integration into logstash.
## Related issues
- Persistence design issue #5636 
- DLQ issue #5283
### Pre-GA
- [ ] sweep code TODOs and convert to tasks/issues and prioritize
- [ ] Add bootstrap checks to persistent queue https://github.com/elastic/logstash/issues/6552 (@original-brownbear)
- [ ] performance & benchmarks (@colinsurprenant)

### Post-GA
- [ ] batched queue and multi write integration (@colinsurprenant)
- [ ] blog post (@colinsurprenant)
- [ ] code sweep for proper exception handling (@original-brownbear)
- [ ] more queue recovery tests
- [ ] more *pages tests
- [ ] refactor acking bitset to use ES LocalCheckpointService (@original-brownbear)
- [x] refactor *Settings classes into a builder pattern #7053, also see https://github.com/elastic/logstash/pull/5958#discussion_r83122350 (@original-brownbear)
- [ ] finalize streaming FilePageIO
- [ ] compare and benchmark MmapPageIO vs streaming FilePageIO
- [ ] Check Available Disk Space for Persisted Queues  https://github.com/elastic/logstash/pull/6998 (@original-brownbear)

### Completed
- [x] optimistic recovery PR #6519 (@colinsurprenant) 
- [x] prevent PQ corruption if two logstash instances are started from the same config or location #6505 (@colinsurprenant)
- [x] Pipeline initialization vs Persistent Queue initialization #5916 (@colinsurprenant)
- [x] enable file-based tests/specs (@guyboertje)
- [x] pass existing integration tests (using the current benchmarks setup)
- [x] DLQ/eviction implementation (see #5283) - we agreed to **not** change the current event dropping behaviour for the first iteration
- [x] fix queue.open bug with empty pages
- [x] refactor Event serialization to use JSON/CBOR (@guyboertje)
- [x] add checksum support to MmapPageIO (@guyboertje)
- [x] optimize Queue.ack() page inefficient page traversal (@colinsurprenant)
- [x] optimize Queue.firstUnreadPage()  inefficient page traversal (@colinsurprenant)
- [x] clean hardcoded "checkpoint" filenames (@colinsurprenant)
- [x] handle case of single element bigger than page capacity in Queue.write()
- [x] add proper Queue.close() with Page.close() and PageIO.close() and review queue closing sequence and exception handling.
- [x] add blocking Queue.readBatch()
- [x] add timedout blocking Queue.readBatch()
- [x] timed-out blocking read_batch size maximisation #5652 
- [x] Queue Batch object integration into Logstash Batch object (@guyboertje) Rebase this into feature branch.
- [x] JRuby ext for Queue API
- [x] Shutdown/Flush signalling need to be reviewed, cannot work as-is with current persistence API #5672
- [x] add acks-side and write-side threashold checkpointing? #6225 (@colinsurprenant)
- [x] add usable queue size max capacity check using byte-size limit (e.g. 8g) (@jsvd) Issue https://github.com/elastic/logstash/issues/6293
- [x] enable existing integration tests with matrix (with PQ on) #6328 (@suyograo)
- [x] and new integration tests (@talevy)
- [x] add monitoring info and API to expose PQ stats (issue: https://github.com/elastic/logstash/issues/6182) (@talevy)
- [x] add user facing docs on PQ (@suyograo)
- [x] review queue closing sequence and exception handling. (@colinsurprenant)
- [x] investigate possible performance issue related to the number of tail pages 
- [x] Wrap AckedBatch in Batch, create Clients and move shutdown and flush signaling to pipleine level similar to Colin's prototype impl (@guyboertje)
- [x] figure how to run logstash tests/specs with PQ code? (use in-memory pages impl?)(@guyboertje)
- [x] remove ElementDeserializer class add Queue.deserialize (@colinsurprenant)
- [x] get rid of ReadElementValue?  I think it is useless since Queueable interface provides getSeqNum(). (@colinsurprenant)
- [x] add queue elements size limit (@colinsurprenant)
- [x] `queue.type` will default to `memory` with option for `persistent` see https://github.com/elastic/logstash/pull/5958#discussion_r80173672
- [x] use `version.yml` in `build.gradle`
- [x] add correct handling of empty pages created by systematic beheading on Queue.open 
- [x] refactor Queue.open(), method is big (@colinsurprenant)

**Comment by colinsurprenant** [comment]
I prioritized tasks in p1/p2 /cc @guyboertje

**Comment by colinsurprenant** [comment]
I added the **master mergability** section to track what is required before submitting a PR against master.

**Comment by colinsurprenant** [comment]
WIP PR submitted in #5958

**Comment by guyboertje** [comment]
Some numbers:
```
  queue.type: persisted
  queue.page_capacity: 512KB
  workers: 1
  events: 1000000
  took: 26.1s

  queue.type: persisted
  queue.page_capacity: 512KB
  workers: 4
  events: 1000000
  took: 18.7s

  queue.type: persisted
  queue.page_capacity: 512KB
  workers: 8
  events: 1000000
  took: 18.5s

  queue.type: persisted
  queue.page_capacity: 65536KB
  workers: 1
  events: 1000000
  took: 32.3s

  queue.type: persisted
  queue.page_capacity: 65536KB
  workers: 4
  events: 1000000
  took: 24.5s

  queue.type: persisted
  queue.page_capacity: 65536KB
  workers: 8
  events: 1000000
  took: 24.4s

  ------------------

  queue.type: memory
  queue.page_capacity: 512KB
  workers: 1
  events: 1000000
  took: 25.1s

  queue.type: memory
  queue.page_capacity: 512KB
  workers: 4
  events: 1000000
  took: 19.1s

  queue.type: memory
  queue.page_capacity: 512KB
  workers: 8
  events: 1000000
  took: 18.5s

  ------------------

  queue.type: synchronous
  workers: 1
  events: 1000000
  took: 31.4s

  queue.type: synchronous
  workers: 4
  events: 1000000
  took: 13.4s

  queue.type: synchronous
  workers: 8
  events: 1000000
  took: 12.9s
```

**Comment by colinsurprenant** [comment]
I also ran some benchmarks using an "empty" config and processing 1M events using the integration/benchmark framework:

```
input { stdin {} }
filter { clone {} }
output { stdout { codec => line } }
```

type  | page size | tps | # pages created
 :------------ | :----------- | :----------- | :----------- |
synchronous | n/a | 52500 | n/a
persisted | 1mb | 50325 | 138
persisted | 512mb | 39166 | 1

So there is in fact a slowdown related to the persisted page size. My guess is with the page bitset operations that are yet to be optimized. (P2 task, will move to P1 😄 )

**Comment by colinsurprenant** [comment]
closing this - this isn't much relevant anymore.
