### ISSUE TITLE
[META] Log4j2 logging in core

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#5650]
**Goal:**
* Unify logging across Logstash's Java and Ruby code.
* Support changing logging level dynamically at runtime through REST endpoints
* Support complete JSON logging
* Provide a strategy for reading in its own JSON logs as input for self monitoring

**Proposed Implementation:**
Migrate from Cabin to Log4j2 as the logging library for Logstash Core and its plugins.

**Reason for library change:**
Logstash and its plugin's usage of Java libraries that use Log4j/SLF4j is growing. This is leading to un-captured logging by core as it is running the pipeline. [Cabin](https://github.com/jordansissel/ruby-cabin) is the current logging library used by Logstash, but it's support for these java libraries is limited. Configuration of these java loggers is also not managed by Logstash natively, this yields confusing warning messages when using specific plugins, like Kafka. Even Logstash's core (Logstash Event in Java) is straying away from Cabin-friendly logging land.

**Tasks For 5.0-beta1:**
- [X] Implement JSON logger general Objects passed-in as secondary arguments to the log records
- [X] Support SLF4j usage in plugins
- [X] Update `@logger` usage in all plugins in `logstash-plugins` repo to be compatible with the new interface
- [X] Introduce an `ArrayListAppender` to be used by logging-related tests
- [X] `log4j2.properties` file is picked up in `logstash.lib.sh` and found in the `conf` dir.
- [x] Re-use Java Event's Javafier to safely/recursively convert between ruby and java types to be logged by Log4j2 (under debate)
- [X] Update log instances used in Core to use Log4j2 loggers, with Java-compatible arguments
- [x] re-enable `path.logs` to specify logs directory, and override log4j config at startup with it https://github.com/elastic/logstash/pull/5876
- [x] introduce log4j configuration for tests via devutils (https://github.com/elastic/logstash-devutils/pull/60)
- [ ] Fix hardcoded version of java project to rely on `version.rake` to correctly set https://github.com/elastic/logstash/pull/5882
- [x] expose log-level changing API https://github.com/elastic/logstash/pull/5871
- [ ] Logstash Event Core Java needs updating to the new logging infrastructure
- [x] --log-in-json property. until this is made.. one has to manually update the `log4j2.properties` file to log in json

Plugin PRs:

- [x] jdbc input plugin
- [x] https://github.com/logstash-plugins/logstash-input-exec/pull/10
- [x] https://github.com/logstash-plugins/logstash-codec-multiline/pull/42
- [ ] log4j-input-plugin

Open ended discussions around jar-hell:

- [ ] slf4j adapters https://github.com/elastic/logstash/issues/5781
- [ ] Support / Test different versions of Log4j in the classpath and plugins that use Log4j-1.x (relates to jar-dependencie's `require_jar` resolution of jars in classpath)

Feature Branch:
https://github.com/elastic/logstash/tree/feature/log4j2-logging
Feature PR: #5651

**Comment by talevy** [comment]
regarding compatiblity with other log4j 1.x libraries being used by plugins... just need to include the 1.x compatibility API to the classpath.

https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api/2.6.2
https://logging.apache.org/log4j/2.x/log4j-1.2-api/index.html

here is an example of a run with Kafka logging to the same logger

```json
...
{"level":"DEBUG","loggerName":"org.apache.kafka.clients.producer.internals.Sender","timeMillis":1471501845029,"thread":"kafka-producer-network-thread | producer-1","logEvent":{"message":"Beginning shutdown of Kafka producer I/O thread, sending remaining records."}}
{"level":"DEBUG","loggerName":"org.apache.kafka.common.metrics.Metrics","timeMillis":1471501845030,"thread":"kafka-producer-network-thread | producer-1","logEvent":{"message":"Removed sensor with name connections-closed:"}}
...
```

**Comment by jsvd** [comment]
@talevy I see the https://github.com/elastic/logstash/commit/1b2f7a766808957c30ac99c011f543aea39d1c24#diff-c48e88983139377e74acb3f0e25f6d18R8 commit introduced some hardcoded strings with the logstash-core version.
I was wondering if we could link these to the existing version.yml or version.rb files? All version references need to be synchronized, specially due to unified build concerns.
Want me to open an issue about this?

**Comment by talevy** [comment]
The major changes made it in. closing
