### ISSUE TITLE
[Meta] Tighten-up Output Workers for 5.0 Release

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5662]
A lot has changed in preparation for 5.0 we need to tighten up a lot of our output worker story before 5.0 . This meta issue will track those changes. Ultimately, we'd love to get rid of output workers(https://github.com/elastic/logstash/issues/5653) but that will probably have to wait till 6.0.

- [x] Educate: Performance Tuning Guide
- [x] Educate: Blog detailing changes and internals of pipeline architecture.
- [x] [Improve nomenclature and methods for 'threadsafe' outputs](https://github.com/elastic/logstash/issues/5661)
- [x] [Remove instance method version of `workers_not_supported`](https://github.com/elastic/logstash/issues/5658)
- [x] [Raise Error when output_workers set for threadsafe plugin](https://github.com/elastic/logstash/issues/5659)
- [x] [Enforce unique ID for plugins](https://github.com/elastic/logstash/issues/5754)
- [x] [Modify docs generator to correctly tag threadsafe outputs](https://github.com/elastic/logstash/issues/5660)
- [x] [Implement `Codec#multi_encode` / `Output#multi_receive_encoded`](https://github.com/elastic/logstash/issues/5768)
- [x]  [Mass update plugins to conform to new output delegator](https://github.com/elastic/logstash/issues/5663)
- [x] [Output plugins not receiving metrics](https://github.com/elastic/logstash/issues/5810)
- [x] [Add workers_not_supported obsolescence message](https://github.com/elastic/logstash/issues/5823)
- [x] [Improve OD public API](https://github.com/elastic/logstash/issues/5813)

**Comment by suyograo** [comment]
Added blog and docs item as well.
