### ISSUE TITLE
Monitoring API enhancements/cleanups for 5.0

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5732]
This issue will track the final iteration of monitoring API fixes/additions in preparation for beta1.

- **Node Stats**
 - [x] Add `duration_in_millis` metric under `/_node/stats/pipeline/events` https://github.com/elastic/logstash/issues/5731
 - [x] Add JVM GC stats under `/_node/stats/jvm` https://github.com/elastic/logstash/issues/5730
 - [x] Remove the `/_node/mem` resource as it's been properly moved under `/_node/jvm/mem` https://github.com/elastic/logstash/pull/5701#issuecomment-235728761
 - [x] Add config reload stats under new resource type /_node/stats/x #5680 (@jsvd)

- **Node Info**
 - [x] Add config reload boolean to `/_node/pipeline` https://github.com/elastic/logstash/issues/5681
 - [x] Add JVM GC strategy info under `/_node/jvm` https://github.com/elastic/logstash/issues/5755

- **Hot Threads**
 - [x] Ensure `?human` option works correctly for hot_threads API. Additionally, the output for `?human=true` appeared to be more verbose than the default format. Need to confirm scope of changes following alpha5 release. https://github.com/elastic/logstash/pull/5701#issuecomment-235728761

**Comment by ph** [comment]
@Alvin I've looked at the hot thread human format and the JSON one, and I can say that they are currently the same. I've created a PR to fixes some small issue with it and adding a test to make sure the thread count is taken into consideration in the case.

**Comment by acchen97** [comment]
@ph thanks, I'll spin up alpha5 today for a quick fact check here as well.

**Comment by acchen97** [comment]
@ph doing some testing against alpha5. A few notes below, but will update the initial issue accordingly.

- Hot threads appears mostly fixed, the ?human=false appears to still show the human format though.
- The "mem" stats are still showing up in the `/_node` top level, this (along with the `/_node/mem` resource) should be removed as its now properly under `/_node/stats/jvm`
- For adding basic stats [in/out/duration_in_millis] to specific input plugins, created a new issue (https://github.com/elastic/logstash/issues/5769) to track the 12 plugin scope. @suyograo maybe divide/conquer makes sense?
- For additional plugin level stats, let's add a few more things for Beats input and ES output. This issue (https://github.com/elastic/logstash/issues/5428) can be used as reference, but I'll let you run with the scoping based on your discretion of importance vs size of work.

**Comment by ph** [comment]
@acchen97 the human=false is fixed in #5766 that I've made today.

**Comment by ph** [comment]
@acchen97 Updated with the latest merges

**Comment by acchen97** [comment]
Awesome, great progress @ph @jsvd

**Comment by suyograo** [comment]
Closing this -- we can move to outside of this meta issue

- **Plugin Stats**
 - [ ] Add basic input plugin stats (in/out/duration_in_millis) for initial 12 plugins https://github.com/elastic/logstash/issues/5769
 - [ ] Add more plugin level stats for Beats input and Elasticsearch output https://github.com/elastic/logstash/issues/5428 https://github.com/elastic/logstash/issues/5717

**Comment by acchen97** [comment]
Moved these to a separate issue https://github.com/elastic/logstash/issues/5921.
