### ISSUE TITLE
Monitoring API feature backlog

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5759]
Backlog for tracking potential monitoring API enhancements/fixes.
- [x] Add basic input plugin stats (in/out/duration_in_millis) for initial 12 plugins https://github.com/elastic/logstash/issues/5769
- [ ] Add stats for Beats input
- [ ] Elasticsearch output stats, should add at least track ES response codes (200, 404, 501, etc.)
- [ ] Dissect filter - add matches/failures
- [ ] Date filter - add matches/failures

- [ ] Add # of concurrent ES bulk requests https://github.com/elastic/logstash/issues/6544
- [ ] Add persistent node ID to uniquely identify a node https://github.com/elastic/logstash/issues/5646 (5.1)
- [ ] Calculate and track estimated bytes ingested (potential limitation for certain input plugins) (5.1)
- [ ] Active/current operations are not counted in duration_in_millis https://github.com/elastic/logstash/issues/5683 (5.1)

**Comment by senty** [comment]
hi,
with this improvements -> will i be able to track how logstash is doing ?
Something like average time for message process, average amount of processed bytes, ... to detect problem with ingesting and react to it (prepare new logstash instance, optimalizations etc. ..).

(i have asked similar question here : https://discuss.elastic.co/t/logstash-5-x-monitoring-api-performance-check/68701)

Thank you very much !

**Comment by acchen97** [comment]
@senty yes, we have a [monitoring API](https://www.elastic.co/guide/en/logstash/current/monitoring.html).

Starting with our 5.2 release, Logstash also now has a monitoring UI. Here's some [documentation](https://www.elastic.co/guide/en/x-pack/current/monitoring-logstash.html). Please check it out!

**Comment by acchen97** [comment]
Closing in favor of https://github.com/elastic/logstash/issues/6831.
