### ISSUE TITLE
New Logstash plugins for review

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5868]
Short list of new plugins which are ready for review (most have PRs already). It would be great to get these reviewed and merged into logstash-plugins for the 5.0 GA timeframe. They are ordered by relative priority.
- [x] Dissect filter - https://github.com/logstash-plugins/logstash-filter-dissect/pull/1
- [x] Protobuf codec - https://github.com/logstash-plugins/logstash-codec-protobuf/pull/1
- [x] Language filter - https://github.com/logstash-plugins/logstash-filter-language/pull/1
- [ ] Date formatter filter - https://github.com/wiibaa/logstash-filter-date_formatter
- [ ] Bytes2human filter - https://github.com/elastic/logstash/issues/3515
- [ ] Kinesis Firehose input - https://github.com/logstash-plugins/logstash-output-firehose/pull/1
- [x] Zookeeper output - https://github.com/logstash-plugins/logstash-output-zookeeper/pull/1
- [x] Monasca Log API output - https://github.com/logstash-plugins/logstash-output-monasca_log_api/pull/1

**Comment by wiibaa** [comment]
Selfish addition ;) => [date_formatter filter](https://github.com/wiibaa/logstash-filter-date_formatter) -  https://github.com/elastic/logstash/issues/3028

**Comment by acchen97** [comment]
Good one @wiibaa thanks, will add to the list. /cc @suyograo

**Comment by moribellamy** [comment]
Also selfish addition: https://github.com/elastic/logstash/issues/5890

**Comment by acchen97** [comment]
Superceded by https://github.com/elastic/logstash/issues/7203.
