### ISSUE TITLE
Fixing the offline plugin installation workflow

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5906]
**Update: please see https://github.com/elastic/logstash/issues/6393 for the new offline plugin proposal**

There are various bugs around the overall offline plugin install/update/uninstall workflow. This meta ticket is to collate and track these issues.
- [ ] Offline install or update (with --local) still tries to connect to Rubygems https://github.com/elastic/logstash/issues/4651 https://github.com/elastic/logstash/issues/6229
- [ ] Offline update --local (update all) doesn’t give user feedback for all plugins updated https://github.com/elastic/logstash/issues/4651
- [ ] Uninstall command tries to connect to Rubygems https://github.com/elastic/logstash/issues/4522
- [ ] Offline plugin install with --no-verify still connects to Rubygems https://github.com/elastic/logstash/issues/5721 https://github.com/elastic/logstash/issues/4521
- [ ] Plugins installed locally cannot be packaged for offline installation https://github.com/elastic/logstash/issues/4644

**Comment by ph** [comment]
There is some work that has been done before to improve the situation but it did not get merged or reviewed. https://github.com/elastic/logstash/pull/4779

**Comment by colinsurprenant** [comment]
@ph some reviewing was done on #4779 but problems were found.

... also some ideas in #4787

**Comment by ph** [comment]
**HTTP_PROXY** and **HTTPS_PROXY** aren't correctly used downstream by jar-dependency when it fetches the pom files. see https://github.com/elastic/logstash/issues/6044#issuecomment-253845907

**Comment by colinsurprenant** [comment]
I suggest we update this issue with the new proposed `--prepare-offline` workflow that will use @ph's mechanism for generating self-contained plugins file that include all dependencies and is offline installable and which should replace the global  pack/unpack stuff.

**Comment by acchen97** [comment]
Good idea @colinsurprenant; I've linked the original post directly to the issue with the new proposal.

**Comment by ph** [comment]
Closing this issue since #6404 was merged.

**Comment by nikkelj** [comment]
I'm not sure you can close this issue yet.  At least when I run this on an offline, with both the old pack/unpack, and new prepare offline method, this thing still tries to connect to the internet, and bombs out with 
ERROR: Something went wrong when installing XXXXXX, message: Connection reset by peer

I am experiencing this w/ 5.2.

**Comment by ph** [comment]
Can you open a new issue including what plugin you are trying to pack and
what command you are using?

**Comment by nikkelj** [comment]
Sure thing

**Comment by nikkelj** [comment]
https://github.com/elastic/logstash/issues/6647
