### ISSUE TITLE
Review usage of info level in logstash default plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5930]
Since we're defaulting the log level to info on logstash, there are plugins that will output a lot of log messages.
This issue tracks the review process of each default process and the changes we need to make to reduce log level from info to debug when necessary.

Usage of log.info on all plugins (not just defaults): https://gist.github.com/jsvd/847c9f05707742f10d20095ba4741d13

PRs on plugins that require log level tuning:

- [x] https://github.com/logstash-plugins/logstash-output-file/pull/48
- [x] https://github.com/logstash-plugins/logstash-output-pagerduty/pull/12
- [x] https://github.com/logstash-plugins/logstash-codec-multiline/pull/43
- [x] https://github.com/logstash-plugins/logstash-codec-collectd/pull/23
- [x] https://github.com/logstash-plugins/logstash-output-cloudwatch/pull/11
- [x] https://github.com/logstash-plugins/logstash-input-syslog/pull/29
- [x] https://github.com/logstash-plugins/logstash-input-exec/pull/11
- [x] https://github.com/logstash-plugins/logstash-input-file/pull/141
- [x] https://github.com/logstash-plugins/logstash-filter-useragent/pull/34
- [x] https://github.com/logstash-plugins/logstash-filter-grok/pull/93

**Comment by jsvd** [comment]
should this be added somewhere in our docs, maybe on the sections about creating your own plugin?

**Comment by jordansissel** [comment]
++

**Comment by jsvd** [comment]
I've done a pass on all inputs and outputs, so we're still missing codecs and filters.

**Comment by jsvd** [comment]
all changed plugins have been merged and 5.0's lock file has been updated in https://github.com/elastic/logstash/commit/3968f08aa340f16fb80138f8dc2f4cb5aef900b7. closing the issue
