### ISSUE TITLE
Logstash 5.2 doc fixes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6501]
**5.2**

- [x] Add docs for prepare-offline pack - see https://github.com/elastic/logstash/pull/6404
- [x] Pack and unpack are now deprecated and will be removed in 6.0
- [x] Document monitoring API additions: 
  - [x] Added persistent queue stats to /_node/stats API - see https://github.com/elastic/logstash/issues/6182
  - [x] Added cgroup information to the stats API - see https://github.com/elastic/logstash/issues/6252
- [x] [Deb] Add monitoring UI content to X-Pack docs - see https://github.com/elastic/x-pack/issues/4511
- [x] Add 5.2 release notes
- [x] Plugin docs enhancements (as plugin pages now show version, release date, changelog, and compatibility)
  - [x] [moved to future list] "master" version of docs needs to be fixed to show latest version of all plugins. The other versions will continue to show the plugin version which was bundled with the release. 
  - [x] REMOVED FROM DOCS Compatibility currently shows all the different LS versions. To mitigate cost of continued maintenance, we could just show first and last versions e.g. "Logstash 2.4.0 - 5.1.2" with the latest version updating with each newest release. NOTE: As of Feb 6, the 5.2 docs do not yet show 5.2 as a compatible version!
  - [x] "Released on" date using "mmm dd, yyyy" may be more human readable
  - [x] Add "Installation" section: "For plugins not bundled by default, it is easy to install by running `bin/logstash-plugin install logstash-x-y`. See the [docs](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html) for more details."
  - [x] Add "Getting Help" section: "For questions about the plugin, open a topic in the [Discuss forums](https://discuss.elastic.co/c/logstash). For bugs or feature requests, open an issue in [Github](https://github.com/logstash-plugins/logstash-x-y). For the list of Elastic supported plugins, please consult the [Elastic Support Matrix](https://www.elastic.co/support/matrix#show_logstash_plugins)."

Moved backlog to this issue: https://github.com/elastic/logstash/issues/6724

**Comment by acchen97** [comment]
@dedemorton updated the original issue.

> Plugin docs enhancements (as plugin pages now show version, release date, changelog, and compatibility)
> - "master" version of docs needs to be fixed to show latest version of all plugins. The other versions will continue to show the plugin version which was bundled with the release.
> - Compatibility currently shows all the different LS versions. To mitigate cost of continued maintenance, we could just show first and last versions e.g. "Logstash 2.4.0 - 5.1.2" with the latest version updating with each newest release.
> - "Released on" date using "mmm dd, yyyy" may be more human readable
> - Add "Installation" section: "For plugins not bundled by default, it is easy to install by running `bin/logstash-plugin install logstash-x-y`. See the docs for more details."
> - Add "Getting Help" section: "For questions about the plugin, open a topic in the Discuss forums. For bugs or feature requests, open an issue in Github. For the list of Elastic supported plugins, please consult the Elastic Support Matrix."

@ph @jordansissel included above are a couple enhancement requests for the plugin docs. The first and last items here are higher priority than the rest.

**Comment by dedemorton** [comment]
@ph I thought the docgen script was going to add an installation section (see above). Did we decide not to do that after all? Just trying to close out the items from this list. I think the only remaining one is to update the docs in master (and automate the process), no?

**Comment by dedemorton** [comment]
Closing this old issue.
