### ISSUE TITLE
Refactor Agent to be more flexible with Source Loading

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6620]
I've been working on the refactoring of the **Config Loading**  in https://github.com/elastic/logstash/pull/6514 to give the ability of a universal plugins to add or remove sources of configuration.

So far this is working fine when we only deal with one pipeline and the auto-reload is off, as soon as we deal with multiple pipeline like the xpack monitoring pipeline this get a bit tricky. 

Let's say that the source of configuration is dynamic and the following happen:

- First call return pipeline1
- Second call return **no pipeline**

I would expect Logstash in this case to stop the **pipeline1** and wait until the dynamic source returns a new pipeline to run, this will even be more needed when multiples pipelines land and the dynamic source return 1 or more pipelines.

We need to do the following changes:

SOURCE_LOADER.fetch will return a **array of pipeline_configs**, the agent will take this list as the source of truth and will diff the current running pipeline into what we actually need to run and create a list of actions that the agent needs to execute to sync the running state.

Defined actions:

- Create Pipeline
- Reload pipeline
- Stop Pipeline

# TODO:
- [x] resolve action
- [x] remove register_pipeline
- [x] agent takes the source loader as a parameter
- [x] Split Action
- [x] Unit tests Actions.

**Comment by ph** [comment]
cc @jsvd

**Comment by ph** [comment]
The strategy I am intending to use is to create simple classes for each **action** that will receive the hash of the pipelines, this will allow us to test each scenario in isolation.

Conditions:

- If the pipeline_config.pipeline_id is not in the pipelines => Create
- If the pipeline_config.pipeline_id is in the pipelines id
  - the **config_hash** don't match => Reload
  - the **config_hash** match => NOOP
- If the any of the current running pipeline_id is not in the received list of pipeline_configs => Stop

**Comment by ph** [comment]
This change will remove the need of `register_pipeline` since the PipelineConfig will provide both the actual config and the settings that we need to use.

**Comment by ph** [comment]
Running 1 or multiple pipeline will use the same code and will have some kind of notion of state this will allow us to add a health status on logstash when multiple pipeline land.

**Comment by ph** [comment]
@jsvd I've been digging through the auto reload code, and I've discovered that we can create `pipeline` which are not auto-reloadable with the pipeline specific settings? 

I thought reloading was a top level concern, in the context of multiple pipelines and dynamic sources do we need that, I am just trying to figure out if we need it or not?

I can certainally skip them when I resolve the converge actions.

**Comment by ph** [comment]
OK, got the POC, working still a lot to do:

- Need to fine a better way for the metrics, they obscure the code so much.
- The tests suite hang now for some auto-reload tests.
- Revisit the rescue/logic/thread.

In general I am happy how it turn out, I have added a few `trace` statements around the code.

**Comment by ph** [comment]
#6632 is now in master.
