### ISSUE TITLE
Generate versioned plugin documentation

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6683]
**The Problem**
Currently, the documentation for Logstash plugins reflects the version of each plugin that was bundled with the release.  If the user updates a plugin after installing Logstash, it can be challenging for the user to find docs that match the specific version of the plugin that is installed.  The docs in the `master` branch contain info about the latest version of the plugin, and the docs in the `current` branch contain info about the plugin version bundled with Logstash, but what if the user has a different (intermediary) version of a plugin installed? Short of looking at the Ruby source code in GitHub, there is no easy way to figure out what is supported. 

We tried to mitigate this problem by adding version info to the published plugin docs, but that has resulted in more confusion and doesn't solve the main problem: users need to be able to access accurate documentation that reflects the version of the plugin that's installed.

**Proposal**
We need to provide versioned plugin documentation so the user can access content that accurately reflects the version of the plugin that they have installed.

To accomplish this goal, we need to:

- [x] Design the information architecture for navigating to/from the versioned content for each plugin. This might be a link that points to "Other versions" or possibly even a list of all available versions.
- [x] Determine the design and location of the versioned content:
- what the pages will look like
- where they will live
- how the user will navigate between different versions of the content (drop-down list? links in the TOC?)
- how the user will navigate back to the main Logstash doc, etc
- [x] Modify the docs infrastructure to build plugin-specific content. For every version of the plugin that's released, we should generate a new version of the plugin documentation and make it available on the docs website. We'll need to make the IDs in each file unique (possibly by including the version number) so that the book builds without errors.
- [ ] Automate the generation and publishing of the plugin documentation so that a new version of the docs is generated/published whenever a new version of a plugin is released. [moved to a #9048]

**Comment by dedemorton** [comment]
One solution for navigation would be to provide multiple versions of the plugin docs in a single book called something like "Logstash Plugin Reference". So the Doc landing page would have something like:

`````
Logstash: Collect, Enrich, and Transport

    Logstash Reference [5.2] — other versions 
    Logstash Plugin Reference

`````
(I probably need to put a bit more thought on helping users understand why the plugin docs appear in two places.)

When users click the Logstash Plugin Reference link, they will go to a book with a nav that looks something like this:
`````
Logstash Plugin Reference
This guide contains the documentation for Logstash plugins organized by plugin version. 

Input plugins
    beats
    cloudwatch
    couchdb_changes
    ...
Output plugins
    boundary
    circus
    cloud watch
    ...
Filter plugins
    aggregate
    alter
    anonymize
….
`````
If they expand a plugin in the nav, they will see the list of plugin versions
`````
    beats
        3.1.12
        3.1.11
        ...
`````
If they click a plugin in the nav, they will see a page that lists the plugin versions as links. So something like the following, with each version being an active link.
`````
beats
To see which version of the plugin you have installed, run `bin/logstash-plugin list --verbose`. 

Documentation by Version
3.1.12    Nov 30, 2015
3.1.11    date
3.1.10    date

`````

In the Logstash Reference, we could add an "Other Versions" link that points to the 
page containing the links. Then we wouldn't have to explain to users what `master` means because they would be able to see the latest version of the docs for each plugin.

Each page would also probably need to have a link back to the Logstash Reference.

**Comment by dedemorton** [comment]
I've updated the description above to reflect our ongoing discussions about how this content should be structured.

**Comment by dedemorton** [comment]
One thing I didn't think about before: if we include all versions the docs for a specific plugin in the same book, we'll need to add something to the asciidoc source files so that we get unique IDs for each version. This is going to be a bit tricky because the links that reference the IDs will also need to be updated, and that's gonna get weird for the links between plugins, especially if we update the plugin docs individually. I'm also not sure how we'll deal with links that use the cross link syntax `<<link>>` to point to topics in the LS Reference. We'll need to do more thinking about this....

**Comment by dedemorton** [comment]
@andrewvc How do we get this work added to the roadmap? Right now, there is no easy way for users to access the documentation for the specific version of the plugin that they have installed.

**Comment by dedemorton** [comment]
@jsvd Just an FYI that this is something I've been wanting to do for awhile. We are not providing our users with an optimal experience with the plugin docs. My hope is that once we have versioned plugin docs in place, we'll be able to say more about compatibility with core.

**Comment by dedemorton** [comment]
Closing because the versioned plugin reference is published! Created a separate issue for the remaining cleanup work: #9048
