### ISSUE TITLE
Logstash 5.3 doc fixes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6724]
This list is a work-in-progress. Need to meet with dev to prioritize/refine goals

**5.3:**

- [x] Document Filebeat modules (see https://github.com/elastic/logstash/issues/6542)
- [x] Generate plugin docs for 5.3. Make sure the manual tweaks made in https://github.com/elastic/logstash-docs/pull/353 get in. Make sure the docs for new plugins that got merged get generated.
- [x] Document content-type header integration compatibility (See https://github.com/elastic/logstash/issues/6718)
- [x] Add "at least once" delivery guarantees to the PQ docs.
- [x] Make remaining plugin changes (I'll move items from [here](https://github.com/elastic/logstash/issues/6501) to this list after the dust settles).
- [x] Bug fixes and enhancements tagged for 5:3, including (but not limited to):

Moved "backlog" to https://github.com/elastic/logstash/issues/6850.
