### ISSUE TITLE
Logstash 5.4 doc fixes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6850]
**5.4**
- [x] Filebeat modules docs for LS
- [x] Document popular processing capabilities of Logstash. See https://github.com/elastic/logstash/issues/6820
- [x] Better document multi line on edge recommendation https://github.com/logstash-plugins/logstash-input-beats/issues/199
- [x] Deploying and scaling guide update (Alvin)
- [x] Investigate whether Beta/Experimental flags are required:
  - [x] Persistent queues - this is GA in 5.4, rigth?
  - [x] Monitoring APIs - still experimental?
  - [x] Are there any other features that should be marked experimental or beta, but aren't?

Moved backlog to https://github.com/elastic/logstash/issues/6963

**Comment by dedemorton** [comment]
@acchen97 Will the updates that you're planning to the deployment and scaling guide cover persistent queues? I noticed that you're assigned to this issue here...just want to make sure we're covered because Jordan's marked it as a blocker for 5.4: https://github.com/elastic/logstash/issues/6875

**Comment by acchen97** [comment]
@dedemorton I'll work on a draft this weekend.

**Comment by suyograo** [comment]
@dedemorton I removed DLQ since it didn't make 5.4.0

**Comment by acchen97** [comment]
Regarding beta/experimental tags, let's go ahead and remove experimental from monitoring API. We can also consider it GA at 5.4.
