### ISSUE TITLE
Logstash 6.0 doc changes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6963]
**GA**
- [x] Add 6.0 screen shots
- [x] Update docs to reflect doctype deprecation. See related PR: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/691 and https://github.com/elastic/logstash/issues/8606
- [x] Remove doc for features/plugins that were deprecated in 5.x:
  - [x] Anonymize filter
- [x] Fix example in beats input plugin docs. https://github.com/logstash-plugins/logstash-input-beats/issues/258
- [x] Update breaking changes.
- [x] Resolve outstanding doc issues for GA: https://github.com/elastic/logstash/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Av6.0.0%20label%3Adocs

Moved backlog to: https://github.com/elastic/logstash/issues/8683

**Completed**

**Alpha 2**:

- [x] Remove offline plugin install instructions because they were deprecated in 5.x: https://www.elastic.co/guide/en/logstash/5.2/offline-plugins.html#building-offline-packages-deprecated
- [x] Add docs for multiple pipelines
**Beta 1**
- [x] Add docs for config management (central config) - X-Pack (UI plus settings). See https://github.com/elastic/x-pack-kibana/pull/501
  - [x] Document Logstash settings. See https://gist.github.com/suyograo/1b9ec40947206060bd2c1102f692c915
  - [x] Add Configuration Management container (can also be a container for talking about other tools like chef and puppet)
- [x] Add docs for new modules in a section called Modules (see https://github.com/elastic/logstash/issues/6851) 
  - [x] Add docs for netflow module
  - [x] [Alvin] Add docs for arcsight module
  - [x] Backport module docs from master to 5.6 and 6.0
- [x] Add docs for pipeline viewer
- [x] Add docs for central configuration https://github.com/elastic/x-pack-logstash/pull/188
- [x] Add docs for PV.

**Beta 1 and 2**
- [x] Add docs for config management (central config) - X-Pack (UI plus settings). See https://github.com/elastic/x-pack-kibana/pull/501
  - [x] Document Logstash settings. See https://gist.github.com/suyograo/1b9ec40947206060bd2c1102f692c915
  - [x] Add Configuration Management container (can also be a container for talking about other tools like chef and puppet)
- [x] Add docs for new modules in a section called Modules (see https://github.com/elastic/logstash/issues/6851) 
  - [x] Add docs for netflow module
  - [x] [Alvin] Add docs for arcsight module
  - [x] Backport module docs from master to 5.6 and 6.0
- [x] Add docs for pipeline viewer
- [x] Add docs for central configuration https://github.com/elastic/x-pack-logstash/pull/188
- [x] Add docs for pipeline viewer.

**RC1**
- [x] Resolve outstanding doc issues for RC1: https://github.com/elastic/logstash/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Av6.0.0-rc1%20label%3Adocs
- [x] Add docs for ingest to LS conversion tool. 
- [x] Add arcsight screenshots

**RC2**
- [x] Resolve outstanding doc issues for RC2: https://github.com/elastic/logstash/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Av6.0.0-rc2%20label%3Adocs
- [x] Make sure the breaking changes and upgrade docs are up-to-date, specifically the breaking changes for the ES output and the bundled plugins where we've changed configs from deprecated > obsolete...and possibly others.

**Comment by dedemorton** [comment]
@dedemorton test

**Comment by dedemorton** [comment]
Added container and usage info about modules in this PR: https://github.com/elastic/logstash/pull/7826

**Comment by ppf2** [comment]
@dedemorton Just to confirm.  

Does this item

>Two links for plugin version navigation: master and latest compatible version

represent a new documentation set that will map out compatible plugin versions (for all supported plugins) <-> LS core version?  If so, this is 🍾 🎆 ❤️  :)

**Comment by acchen97** [comment]
Updated with 6.0 GA outstanding issues.

@ppf2 we plan to resolve this with a compatibility statement in the LS plugins support matrix. Now with LS 2.3 and prior EOL, all the newer plugin versions should work on all LS 2.4+.

**Comment by dedemorton** [comment]
@ppf2 We do also want to make plugin docs available in multiple versions, but that's going to require some dev cycles to work on our tooling...just haven't had the time yet.

**Comment by dedemorton** [comment]
Closing out doc meta issue from 6.0. Any remaining items from the backlog and other lists have been moved to #8683
