### ISSUE TITLE
[Meta] Upgrading to JRuby 9k

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7125]
With the release of Logstash 6.0 just around the corner we want to take the opportunity to upgrade to JRuby 9k, since 1.7 is  EOL and a lot of gems are now breaking under 1.7 because they explicitely require JRuby 9k in their gemspec.

### TODO
- [x] Update Logstash to be able to run under JRuby 9k #https://github.com/elastic/logstash/issues/5606 https://github.com/elastic/logstash/pull/6713
- [x] Create a feature branch with the JRuby 9k
- [x] Update plugins .travis.yaml to build with jruby 9k https://github.com/elastic/logstash/issues/7126
- [ ] Move to `java.time` for timestamp instead of joda. https://github.com/elastic/logstash/issues/7149
- [x] Fix plugins related issues, see meta issue https://github.com/elastic/logstash/issues/7252

cc @guyboertje

**Comment by ph** [comment]
I've created a [PR](https://github.com/logstash-plugins/logstash-input-beats/pull/203) on the beats input that make sure we test the following matrix.

- Release Gems + JRuby 1.7.25
- Unreleased gems on 5.x + JRuby-1.7.25
- Logstash Master + JRuby-1.7.25
- Specific JRuby 9k Logstash feature branch + JRuby-1.7.25

You can see an example run at https://travis-ci.org/logstash-plugins/logstash-input-beats,

**Comment by guyboertje** [comment]
Created branch [feature/9000](https://github.com/elastic/logstash/tree/feature/9000) which is PR #6713 merged (kinda) to a new branch

**Comment by ph** [comment]
We decided to do Java8 time at a later date.
