### ISSUE TITLE
Logstash 5.5 doc changes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7188]
**5.5**

- [x] Add docs about about resiliency, including docs about DLQ. See https://github.com/elastic/logstash/issues/6700
  - [x] Fix the input event example to show the proper structure because the existing draft shows the output event.
  - [x] Add example that shows geopoint mapping error and how to filter on the reason field. 
- [x] Add DLQ docs.
- [x] Add section about monitoring Logstash. See https://github.com/elastic/logstash/issues/6991
- [x] Add info around upgrading Logstash with PQs enabled. See https://github.com/elastic/logstash/issues/7158
- [x] Add documentation for new queue drain option. See https://github.com/elastic/logstash/issues/6778 
- [x] Make sure docs for new plugings get generated: (waiting for plugin build)
  - [x] JMS input/output plugins. See https://github.com/elastic/logstash/issues/6667
  - [x] DLQ plugin
- [x] P1: Document grok debugger: 
  - [x] Mention grok debugger in grok plugin docs
  - [x] Mention grok debugger in Transforming Data and Getting Started sections of the LS Reference
  - [x] Mention grok debugger in the ingest node docs
  - [x] Add install and usage docs to X-Pack 
- [x] Edit DLQ input docs.
- [x] Finalize the plugin docs and cherry-pick them into 5.x.
- [x] Add section about looking up data. See https://github.com/elastic/logstash/issues/6687

**Post-5.5 (soon after)**
- [x] The plugin docs for 5.5 required a number of manual hacks due to content that got incorrectly extracted. Need to apply these changes asap to the repos so we don't have to make the manual hacks again.

**Backlog**
Moved backlog to https://github.com/elastic/logstash/issues/7653

**Comment by breml** [comment]
In the documentation about the [event api](https://www.elastic.co/guide/en/logstash/current/event-api.html) (respectively [asciidoc](https://github.com/elastic/logstash-docs/blob/master/docs/static/event-api.asciidoc) there are several important methods missing, which are defined on [event](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java). For example:

* `cancel`
* `uncancel`
* `cancelled?`
* `include?`
* `remove`
* `tag`

Maybe there could be a link to the right source file, for the interested folks (so they do not have to search on their own).

**Comment by dedemorton** [comment]
The "Add DLQ policy section to Elasticsearch output docs" got marked as complete at some point, but it isn't. I'll add this to the source documentation (and patch the generated docs) after we get the plugin docs building successfully.

**Comment by dedemorton** [comment]
@suyograo I don't see any real code in the DBC_static plugin repo, so I'm moving work items related to that plugin out of this list for 5.5.

**Comment by acchen97** [comment]
@dedemorton should we close this out and move outstanding items to a 5.6 meta issue? Additionally, I'd like for us to bump the priority of the Windows service/install page as the demand is growing.

https://github.com/elastic/logstash/issues/4005

**Comment by dedemorton** [comment]
Closing...moved all incomplete work items to #7653

**Comment by dedemorton** [comment]
Moved backlog back to the 6.0 issues for tacking: https://github.com/elastic/logstash/issues/6963
