### ISSUE TITLE
Next round of new Logstash plugins 

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7203]
This tracks a short list of new plugins to attend to next. It would be great to get these reviewed and merged into logstash-plugins. They are ordered by relative priority.

- [ ] Date formatter filter - https://github.com/elastic/logstash/issues/3028
- [ ] CEPH output - https://github.com/elastic/logstash/issues/7021 (needs dev)
- [ ] CSV input - https://github.com/elastic/logstash/issues/2088 (needs dev)
- [ ] Okta input - https://github.com/elastic/logstash/issues/6752
- [ ] Denormalize filter - https://github.com/elastic/logstash/issues/5110
- [ ] Bytes2human filter - https://github.com/elastic/logstash/issues/3515
- [ ] JMX pipe input - https://github.com/elastic/logstash/issues/6690
- [ ] Cloud Foundry filter - https://github.com/elastic/logstash/issues/5977
- [ ] RethinkDB input - https://github.com/elastic/logstash/issues/6839
- [ ] VMWare Log Insight output - https://github.com/elastic/logstash/issues/6809
- [ ] Amazon Kinesis firehose output - https://github.com/logstash-plugins/logstash-output-firehose/pull/1

/cc @suyograo

**Comment by shurik-io** [comment]
Any plans/ideas when the #3028 plugin is comming? As I saw in #5868 it didn't make it into that round. I guess many users would like to format their timestamps with their preferred timezone than UTC. 
If testing is needed, I could help with :)

**Comment by aagupta1** [comment]
Any chance of building a CEPH input plugin anytime soon ?
