### ISSUE TITLE
[Meta] LIR Execution

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7291]
This issue is a meta issue to track LIR execution progress.

## Goals

(In no particular order)

* Performance
* Removing duplicate grammars
* Javaifying more of the pipeline
* Modularized execution
* Combine filters/outputs in the pipeline code into one 'processor' notion

### Now

NOTE: This strategy is a little out of date, some of it is in flux. @original-brownbear has an evolving initial approach here: https://github.com/elastic/logstash/pull/7950 (WIP). This checklist may be updated as that progresses.

- [ ] Implement LIR Execution Using Janino #7358
- [ ] Make sure quote escaping from #7442 is ported to lscl.rb
- [ ] Wrap LIR into an execution class #7361
- [ ] Implement Expression execution using Janino to compile to java bytecode #7358
- [ ] Define Pipeline State machine #7364
- [ ] Define the Read client interaction with the processor stage of the pipeline
- [ ] Define the Write client interface with the input stage #7363
- [ ] Pipeline Shutdown Reporter #7365

**Comment by ph** [comment]
Some of my original thoughts are in https://github.com/elastic/logstash/issues/6301

**Comment by original-brownbear** [comment]
@ph reading :)

**Comment by ph** [comment]
I've updated the goals with our discussion from yesterday

**Comment by ph** [comment]
I am doing a spike to see the amount of work to rewrite directly the pipeline.rb class to java, this class does so many things but I think we can get a minimal pipeline quickly.
