### ISSUE TITLE
[meta] streamline and harmonize plugins with jars build and publish processes

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7627]
This is somewhat a postmortem of the problems we had last Friday trying to fix and release a new dissect filter version. The bundled dissect 1.0.9 in LS 5.5.0 is missing its jar file. This is a list of issues we should look at to avoid similar problems.

- [ ] revew/decide on uniform jar handling in the plugin gem. The dissect problem was fixed by adding `vendor/jars/**/*` is the gemspec `files`, see PR https://github.com/logstash-plugins/logstash-filter-dissect/pull/32.  Another strategy in other plugins is to [handle this in gradle](https://github.com/logstash-plugins/logstash-filter-dissect/compare/master...jakelandis:master).

- [ ] fix the build and release rake tasks to correctly propagate error conditions, see PR https://github.com/logstash-plugins/logstash-filter-dissect/pull/29

- [ ] review the *jarvis* publish command tasks sequence and error handling.

- [ ] add smoke test which just loads all bundled plugins to quickly identify any plugin with missing dependencies / initialization errors.

- [ ] review plugins repos permissions for *jarvis* "write" access for the publish task.

**Comment by colinsurprenant** [comment]
The listed java plugins above have been validated against #7666 and no other plugin than `dissect` and `dead_letter_queue` are missing jars
