### ISSUE TITLE
Review plugin docs containing build fixes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7630]
I had to make quite a few manual hacks to get the plugin does to build in 5.5. I've made the changes in the following PRs. I'd like someone to give them a quick review and merge them. Here are the PRs: 

- [x] https://github.com/logstash-plugins/logstash-output-rackspace/pull/5

- [x] https://github.com/logstash-plugins/logstash-input-rackspace/pull/7

- [x] https://github.com/logstash-plugins/logstash-filter-metaevent/pull/6

- [x] https://github.com/logstash-plugins/logstash-codec-oldlogstashjson/pull/1

- [x] https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/71

- [x] https://github.com/logstash-plugins/logstash-output-kafka/pull/137

- [x] https://github.com/logstash-plugins/logstash-input-kafka/pull/208

- [x] https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/6

- [x] https://github.com/logstash-plugins/logstash-input-kinesis/pull/31

- [x] https://github.com/logstash-plugins/logstash-codec-dots/pull/7

- [x] https://github.com/logstash-plugins/logstash-output-stomp/pull/18

- [x] https://github.com/logstash-plugins/logstash-output-lumberjack/pull/25

- [x] https://github.com/logstash-plugins/logstash-output-librato/pull/8

- [x] https://github.com/logstash-plugins/logstash-output-http/pull/65

- [x] https://github.com/logstash-plugins/logstash-output-email/pull/43

- [x] https://github.com/logstash-plugins/logstash-output-datadog/pull/14

- [x] https://github.com/logstash-plugins/logstash-output-circonus/pull/4

- [x] https://github.com/logstash-plugins/logstash-input-log4j/pull/42

- [x] https://github.com/logstash-plugins/logstash-codec-msgpack/pull/9

- [x] https://github.com/logstash-plugins/logstash-codec-edn_lines/pull/4

- [x] https://github.com/logstash-plugins/logstash-codec-edn/pull/4

- [x] https://github.com/logstash-plugins/logstash-filter-aggregate/pull/71

**Comment by jordansissel** [comment]
@dedemorton all the checkboxes in this issue are checked: is this good to close?
