### ISSUE TITLE
Logstash 5.6.x doc changes

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7653]
**5.6.x**
- [x] Update Kafka compat matrix. See Alvin's comment below.

**5.6**

- [x] Doc page for Logstash modules and how they work
- [x] Docs for netflow and arcsight modules need to be ported to 5.6
- [x] Lots of other stuff that didn't appear on this list. :-P

**Soon after 5.5**
- [x] Update docs about running Filebeat Modules. Include docs for new modules. Make sure the steps are still correct and that the syslog example works. Run tool to update configs. See https://github.com/elastic/logstash/issues/6542
- [x] Add DLQ policy section to Elasticsearch output docs (can add this after 5.5 releases). See https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/617.
- [x] Document how to limit DLQ disk usage. See https://github.com/elastic/logstash/issues/7658
- [x] Get the plugin docs building in master.
- [x] Add links to DLQ plugin when the docs are building (need to wait until DLQ plugin docs are available in master and 5.x branches)

Moved backlog to https://github.com/elastic/logstash/issues/6963

**Comment by acchen97** [comment]
Just noting down here to include updating the Kafka plugin compatibility matrices through Kafka v0.11 for LS 5.6:
- https://github.com/logstash-plugins/logstash-input-kafka/issues/214
- https://github.com/logstash-plugins/logstash-output-kafka/issues/142

**Comment by dedemorton** [comment]
Changing label to close out this PR since 5.6 has shipped.

**Comment by dedemorton** [comment]
@acchen97 Speaking of the Kafka matrix. Where are we at with that? Can I close the open item here and move it to another issue? Or close it completely?

**Comment by dedemorton** [comment]
Never closed this out, so I'm doing it now.

**Comment by acchen97** [comment]
@jordansissel is tracking and handling the Kafka matrix enhancement. Thanks for closing this.
