### ISSUE TITLE
Move Travis builds to Jenkins

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8079]
Meta issue to move Logstash core builds from Travis to Jenkins.

Current Inventory of Jenkins builds
-----------------------
https://logstash-ci.elastic.co/view/Logstash/

A check mark means that the job currently exists in Jenkins, not necessarily that it works. 

## [Pull Requests](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+pull-request)
- [x] [Unit Tests](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-linux-intake) - TODO: Rename ?
- [ ] Unit Tests with PQ - TODO: Add ?
- [x] [Integration Tests](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration) - TODO: Actually run the tests
- [x] [Integration Tests with PQ](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-pq/) -  TODO: Actually run the tests
- [ ] Unix compatibility - TODO: Add ?
- [x] [Windows compatibilty](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-windows-compatibility) - TODO: Run Ruby Tests https://github.com/elastic/logstash/issues/7767
- [ ] Acceptance Tests - TODO: Add ?
- N/A Periodic Docker Tests

## [7.x / master](https://logstash-ci.elastic.co/view/Logstash/job/elastic-logstash-master)
- [x] [Unit Tests](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-intake) - TODO: Rename ?
- [ ] Unit Tests with PQ - TODO: Add ?
- [ ] Integration Tests - TODO: Add ?
- [ ] Integration Tests with PQ - TODO: Add ?
- [x] [Unix compatibility](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility)
- [x] [Windows compatibilty](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-windows-compatibility) - TODO: Run Ruby Tests https://github.com/elastic/logstash/issues/7767
- [x] [Acceptance Tests](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance) - TODO: Why haven't these run in a while ?
- [x] [Periodic Docker Tests](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+master+dockerubuntu-periodic)

## [6.x](https://logstash-ci.elastic.co/view/Logstash/job/elastic-logstash-6.x)
- [x] [Unit Tests](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-intake) - TODO: Rename ?
- [ ] Unit Tests with PQ - TODO: Add ?
- [ ] Integration Tests - TODO: Add ?
- [ ] Integration Tests with PQ - TODO: Add ?
- [x] [Unix compatibility](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility)
- [ ] [Windows compatibilty](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-windows-compatibility) - TODO: Run Ruby Tests https://github.com/elastic/logstash/issues/7767
- [ ] [Acceptance Tests](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-acceptance) - TODO: Why haven't these run in a while ?
- [x] [Periodic Docker Tests](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+6.x+dockerubuntu-periodic)

## [6.0](https://logstash-ci.elastic.co/view/Logstash/job/elastic-logstash-6.0)
- [x] [Unit Tests](https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-intake) - TODO: Rename ?
- [ ] Unit Tests with PQ - TODO: Add ?
- [ ] Integration Tests - TODO: Add ?
- [ ] Integration Tests with PQ - TODO: Add
- [x] [Unix compatibility](https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-unix-compatibility) 
- [x] [Windows compatibilty](https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-windows-compatibility) - TODO: Run Ruby Tests https://github.com/elastic/logstash/issues/7767
- [x] [Acceptance Tests](https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-acceptance) - TODO: Why haven't these run in a while ?
- [x] [Periodic Docker Tests](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+6.0+dockerubuntu-periodic)

## [5.6](https://logstash-ci.elastic.co/view/Logstash/job/elastic-logstash-5.6)
- [x] [Unit Tests](https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-intake)
- [ ] Unit Tests with PQ - TODO: Add ?
- [ ] Integration Tests - TODO: Add ?
- [ ] Integration Tests with PQ - TODO: Add ?
- [x] [Unix compatibility](https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-unix-compatibility)
- [x] [Windows compatibilty](https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-windows-compatibility)  - TODO: Run Ruby Tests https://github.com/elastic/logstash/issues/7767
- [x] [Acceptance Tests](https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-acceptance) - TODO: Why have these never been run ?
- [x] [Periodic Docker Tests](https://logstash-ci.elastic.co/view/Logstash/job/elastic+logstash+5.6+dockerubuntu-periodic)

Final Burn Down List 
-----------
A checkmark here means that that pipeline is done and no further immediate work.

- [ ] Pull Requests
- [ ] 7.x / Master
- [ ] 6.x
- [ ] 6.0
- [ ] 5.6

**Comment by jakelandis** [comment]
Spoke with @andrewvc on Slack, and have the following proposal:

* Remove `Unit Tests with PQ`. Travis currently does this, but not sure why. @ph / @colinsurprenant - is there any reason to keep running the unit tests with and without PQ environment variable ?
* Attempt to re-purpose the Windows and Unix Compatibility tests to run the integration tests instead of the unit tests. 
   * This may be problematic if the sub containers running the underlying OS gets re-used. 
   * This may be problematic if the sub containers running the underlying OS does not properly support docker and/or some of the other 3rd party systems that may get installed for the integration tests. 
* Figure out why the acceptance tests are not running as they should be. 

I will dig into how the the Compatibility tests so we can have informed discussions with infra.

The end result will be that all branches and and PR's will run the same suite of tests, in parallel, and hopefully take no longer then existing Travis tests. 

@suyograo @jordansissel - thoughts ?

**Comment by jakelandis** [comment]
I looked at the 'sub-containers'... and they aren't really sub-containers, they are simply Jenkins's slaves with the given OS. 

I was made an incorrect assumption that the Compatibility tests were run inside an isolated container, but they are not. So re-purposing the Compatibility tests vs. simply running on the Jenkins Slaves isn't solving any immediate problems of isolation. _(though it would make the compatibility tests more valuable)_ 

Isolation is the real problem here. For example, if two integration tests were running on the same host at the same time, one of the would fail. 

Clean environment is also an issue. If for some reason Logstash doesn't clean up properly, one test can negatively effect the next test. 

Isolation and clean environment are 2 things that Travis did well. 

We basically have 3 choices w/r/t to isolation:
* 1) Use Jenkins functionality to [limit concurrent tests](https://wiki.jenkins.io/display/JENKINS/Throttle+Concurrent+Builds+Plugin) 
* 2) Update the tests to better support multiple instances
* 3) Use a container based approach (vagrant or docker) and run the integration tests there. 

IMO, 
1) Slows things way down and is difficult to maintain
2) Is throwing good money after bad
3) Gets both isolation and clean environment, but comes at a higher cost. 

New proposal: we meet discuss with infra next week to discuss how best to solve isolation and clean environments.

**Comment by jakelandis** [comment]
Final state:

## Pull Requests
- [x] Unit Tests - Run via Docker
- [x] Integration Tests - split in 2 parts Run via Docker
- [x] Integration Tests with PQ - split in 2 parts Run via Docker

## Current Branch builds 
- [x] Unit Tests - Run via Docker
- [x] Integration Tests - split in 2 parts Run via Docker
- [x] Integration Tests with PQ - split in 2 parts Run via Docker
- [x] Unix compatibility
- [x] Windows compatibility
- [x] Acceptance Tests

## Non-Current Branch builds
- Unit Tests (no Docker)
- Unix compatibility
- Acceptance Tests
(note - no integration and no Windows tests)
