### ISSUE TITLE
[Meta] Move from rake to gradle to build Logstash

### ISSUE THREAD

**Issue by ph** [elastic/logstash#8235]
We want to move from rake to Gradle to achieve the following goals:

- Be a better java citizen
- Easier to create project dependencies
- Reduce dependencies needed to build logstash
- Faster build
- Eliminate double launch of ruby.

**Steps required:**

- [ ] Download JRuby with gradle instead of Rake https://github.com/elastic/logstash/issues/8234
- [ ] Download the minimal gems with gradle
- [ ] Remove the rake `test:install-core`
- [ ] Make gradle invoke _bundle install_.
- [ ] Evaluate the **rake artifact** build tasks, we have done a lot of work with it and FPM has been great so far.
- [ ] Fix environment initialization and loading https://github.com/elastic/logstash/issues/8207

**Comment by ph** [comment]
I have great progress on this, I've cleanup most of the rake tasks related to downloading and installing gems. By reducing the bundler calls I've improved the bootstrap speed from 310s to 210s.
