### ISSUE TITLE
Review plugin doc PRs

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#8325]
These PRs need to be reviewed:

- [x] https://github.com/logstash-plugins/logstash-input-http_poller/pull/85
- [x] https://github.com/logstash-plugins/logstash-output-rabbitmq/pull/70
- [x] https://github.com/logstash-plugins/logstash-input-dead_letter_queue/pull/13
- [x]  https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/77
- [x]  https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/671
- [x] https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/670
- [x] https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/677
- [x] https://github.com/logstash-plugins/logstash-input-http_poller/pull/86

(added backports to make it easier for you to review)

**Comment by ph** [comment]
logstash-input-http_poller need backport to 3.x
logstash-output-rabbitmq need backport to 4.x
logstash-output-elasticsearch 7.x

**Comment by dedemorton** [comment]
Backported changes in logstash-input-http_poller to 3.x and logstash-output-elasticsearch to 7x . 

The problem in logstash-output-rabbitmq is already fixed in 4.x, so I didn't have to backport.

**Comment by ph** [comment]
@dedemorton all of theses changes are reviewed, merged and published.
