### ISSUE TITLE
Logstash 6.x doc changes 

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#8683]
**6.3 Release**
- Monitoring UI (https://github.com/elastic/x-pack-kibana/pull/4711)
  - [ ] New screenshot for PQ disk stats
  - [ ] New screenshot for pipeline viewer - time series viz in detail drawer
- [x] Pipeline-to-Pipeline Communication (#9385)
- [x] Centralized pipeline management - new pipeline settings (https://github.com/elastic/x-pack-kibana/pull/4620, https://github.com/elastic/x-pack-logstash/issues/327). (WIP - PR #9649)
- [x]  Centralized Management errors out if ES security is disabled. Note: Security disabled by default with Trial license in 6.2  (https://github.com/elastic/private-logstash/pull/34)
- [x] ArcSight module documentation updates (#9472) 

**Between 6.3 and 6.4**
- [x] Azure plugins and monitoring module  (WIP #9510)
- [x] Cherrypick PQ upgrade info to 6.x. (Originally only merged into 6.2 and 6.3) - Content in #9580. Notes in #9644 

**6.4 Release**
- [ ] SNMP Poller input plugin
- [ ] Centralized management v2 updates - https://github.com/elastic/x-pack-logstash/issues/327, https://github.com/elastic/x-pack-kibana/issues/4334
- [x] Update setup of monitoring and centralized management UIs with impending changes

**Other**
- [ ] Document how to use TLS/SSL settings with LS modules (#9290 )
- [ ] Modules generator and contributor guide
- [ ] Document permissions/roles required for running X-Pack features (#9146)
- [ ] Document running Logstash on Windows - https://github.com/elastic/logstash/issues/4005
- [ ] Improve the getting started guide; perhaps have a quickstart (e.g. modules) and general getting started
  - [ ] Include info about modules so users know there are easier ways to get started.
  - [ ] Mention multiple pipelines and centralized pipeline management so users know that the example configs shown in the  getting started guide are simplified and that other options exist for specifying configs.
  - [ ] Decide whether to add more input examples (jdbc, http, ES + SJ, etc)
- [ ] (Dev) Create doc for setting java heap size (https://github.com/elastic/logstash/issues/7727, https://github.com/elastic/logstash/issues/6970), and reference that page from the performance troubleshooting section.
  - [x] Dead references to LS_HEAP_SIZE (#6970) Fix #9335
- [ ] Add pipelines.yml to Config Settings Files page and other places (#8564)
  - [x] Update config files list (add pipelines.yml and jvm.log4j2.properties; update jvm.options) #9321 
  - [ ] Running LS from command line
  - [ ] Advanced pipeline topic (expand info)
- [ ] Document plugin installation in deb/rpm environs: https://github.com/elastic/logstash/issues/8040
- [ ] Clarify info in plugins-filters-dissect.html
- [ ] Add content from blogs to Logstash docs (#6283)
- [ ] Decide on best approach for referencing older release versions in docs. Clean up accordingly.
- [ ] Performance tuning info from blog to doc (https://github.com/elastic/blog/issues/201)

## Backlog
- [ ] Fix quality issues in plugin docs, as time allows (see https://github.com/elastic/logstash/issues/6693).
- [ ] Document that config directory should only contain config files: https://github.com/elastic/logstash/issues/9613
- [ ] Make sure [monitoring APIs](https://www.elastic.co/guide/en/logstash/current/monitoring.html) are up-to-date wrt examples of what they return.
  - New fields for Elasticsearch output plugin level stats
- [ ] Add section "Adding & Collecting New Plugin Metrics" - adding guidance on how to add metrics to collect in plugins along with new metrics style guide https://github.com/elastic/logstash/issues/5716
- [ ] Pull topics about contributing to Logstash into a separate book (developer guide). Include info about generating a module and the Event API. The Event API docs should probably appear in both the LS Ref and the Dev Guide. Quick fix: move topic about generating modules to the contributing to logstash section.
- [x] Clean up cross references to match link style used in other books in the library. See https://github.com/elastic/logstash/issues/7571
- [ ] Make plugin descriptions consistent across plugin docs. See https://github.com/elastic/logstash/issues/6086
- [x] Update plugin docs to use the new Event API (looks like we missed some examples in the plugin docs). For example https://github.com/elastic/logstash/issues/6459
- [x] Plugin docs:
  - [x] "master" version of docs needs to be fixed to show latest version of all plugins. The other versions will continue to show the plugin version which was bundled with the release.
- [ ] New windows doc page - just under the install scope

**Completed**

**6.2**

- [x] Add docs for JDBC_static plugin  when content is available. Also  update "Transforming Data" section to mention JDBC_static plugin
- [x]  Document secret store
- [x] Publish versioned plugin reference
- [x] Enhance docs about pipeline viewer to show new overview page (backport to 6.2).
- [x] Edit JDBC_static docs.
- [x] [DeDe] Fix defaults shown for  default codec in redis input and output plugin docs. This will require some conditional coding. See https://github.com/logstash-plugins/logstash-output-redis/issues/47 and https://github.com/logstash-plugins/logstash-input-redis/issues/57 

**6.1 GA**
- [x] Make sure usage of Cloud ID is clearly documented
- [x] Clarify docs about tuning options. See related issue: #7027

**Comment by dedemorton** [comment]
Closing because this is an old tracking document.
