### ISSUE TITLE
[META] PQ Disk Size 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8936]
This is a meta issue to regroup and track related PQ disk size issues. 

- [x] Logging when queue.max_bytes is reached https://github.com/elastic/logstash/pull/8400 
  - closed, should be done through API checks
  <br/>
- [x] Logging when queue.max_bytes is reached https://github.com/elastic/logstash/issues/7491
  * closed, in #8400 it was decided to drop that idea
  <br/>
- [x] add queue_size_on_disk stat to persisted queue node stats https://github.com/elastic/logstash/pull/7010
  * introduced  getPersistedByteSize
  <br/>
- [x] Check Available Disk Space for Persisted Queues https://github.com/elastic/logstash/pull/6998
  * proposes a new PQ bootstrap check
  * implements ensureDiskAvailable and uses it in Queue.open
  * we should iron out the last details and merge this
  * rebooted into #8978
  <br/>
- [x] Add bootstrap checks to persistent queue https://github.com/elastic/logstash/issues/6552
  * Issue which will be fixed by #6998
  <br/>
- [x] queue.max_bytes isn't respected at start up time https://github.com/elastic/logstash/issues/6625
  * Issue which will be fixed by #6998
  <br/>
- [x] queue.max_bytes isn't compared against queue.page_capacity https://github.com/elastic/logstash/issues/6627
  * Issue which will be fixed by #6998 
  <br/>
- [x] Modify queue API response https://github.com/elastic/logstash/issues/6508
  * suggests to remove current_size_in_bytes and replace it with queue_size_on_disk which is a percent value calculated from current_size_in_bytes (the accurate value, not logical) and max_queue_size_in_bytes
  * need to assess if still valid?
  <br/>
- [x] Disk level stats for monitoring API https://github.com/elastic/logstash/issues/6884
  * Porposes various PQ/DLQ disk usage stats API
  <br/>
- [x] [DISCUSS] PQ disk size usage APIs #8986 
  <br/>
- [x] Add PQ disk size fields in x-pack monitoring payload

**Comment by colinsurprenant** [comment]
It seems that from #6508, #6518 and #7010 we have settled to using the sum of the actual persisted bytes (head position) for each sparsely allocated page of the queue to compute the queue disk size. This strategy is consistent with what `du` on Linux would report but may show different sizes than `ls`.  As a first step I will go ahead and remove `currentByteSize`, `getCurrentByteSize` and `current_byte_size`.

**Comment by colinsurprenant** [comment]
Submitted #8958 to remove `currentByteSize` support.

**Comment by colinsurprenant** [comment]
Looked again at #6998 and good to move forward, just need rebasing.

**Comment by colinsurprenant** [comment]
Rebooted #6998 in #8978

**Comment by colinsurprenant** [comment]
Created #8986 to discuss PQ disk size usage APIs strategy.

**Comment by colinsurprenant** [comment]
merged #8978 which closed a bunch open issues referenced above. 🎉

**Comment by colinsurprenant** [comment]
I will close this issue since since everything is completed and merged.
