### ISSUE TITLE
JAVAFICATION: Kibana Cient

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#9526]
https://github.com/elastic/logstash/pull/9420

Currently, we have a Kibana client that's implemented in JRuby: https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/modules/kibana_client.rb.

We should port it over to Java. I imagine a series of three separate PRs:
* [ ] Create a Java HTTP client implementation that's fairly simple to consume. https://github.com/elastic/logstash/pull/9420
* [ ] Use the simple HTTP client to implement a higher-level Kibana client in Java.
* [ ] Remove the JRuby Kibana client and replace its usage with the Java Kibana client.
