### ISSUE TITLE
Integration plugins as first class citizens

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#9802]
Currently logstash has the ability to install a plugin that contains multiple plugins inside it.
We can leverage this to group together plugins with similar technologies together, what we're calling integration plugins.

Example: installing a `logstash-integration-elasticsearch` integration plugin would provide:
- logstash-input-elasticsearch
- logstash-filter-elasticsearch
- logstash-output-elasticsearch

Some POC examples: [logstash-integration-rabbitmq](https://github.com/jsvd/logstash-integration-rabbitmq) and [logstash-integration-aws](https://github.com/logstash-plugins/logstash-integration-aws/pull/3)

Grouping the plugins this way allows us to move similar plugins into a single github repo, increasing code share and consistency of vision across an "integration".

There are, however, some missing elements in logstash so that an integration plugin can be treated as a first class citizen:
- [x] establish convention of gemspec metadata for an integration plugin
- [x] show plugins contained in an integration when listing plugins w/ plugin manager
- [x] installing an integration plugin should replace or conflict with currently installed plugins
- [ ] support integration plugin documentation in elastic.co
