### ISSUE TITLE
[META] hybrid Ruby/Java plugin model definition and documentation

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#9823]
This is a meta issue about the work required to establish and document the new hybrid Ruby/Java plugin model so that the community can use some reference model and documentation to contribute such plugins.

Most recent plugin development has involved hybrid Ruby/Java work and the model has evolved as we moved forward with the new model. At this point we should be able to better define what that model is and circle back to all plugins that evolved from this and make then consistent. 

[This is not yet complete and will be adding new tasks and link related issues]

- [ ] Standardize the Gradle `build.grade` configuration for handling external jar dependencies and local jar from local java code. Related discuss issue #9741
- [ ] Define the testing setup using docker. 
- [ ] Update the plugin generator for new model

**Comment by jsvd** [comment]
One note, whatever we decide the setup/testing/packaging workflow to be here, we should have a common interface for all plugins.
By interface here I mean that when we want to publish, we know that doing `bundle install && bundle exec rake vendor && bundle exec rspec && rake publish_gem` will result in a packaged plugin being pushed to rubygems and the git tag added to the github repo, I'd like to continue to have this 1 "command" api for the most common tasks, regardless of the plugin being ruby or ruby+java hybrid.
